# Bash completion for fplaunchwrapper commands
# Provides intelligent tab completion for all fplaunch-* commands

# Get config directory and bin directory
_fplaunch_get_dirs() {
    local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
    local bin_dir_file="$config_dir/bin_dir"
    local bin_dir="$HOME/.local/bin"
    if [ -f "$bin_dir_file" ]; then
        bin_dir=$(cat "$bin_dir_file" 2>/dev/null || echo "$bin_dir")
    fi
    echo "$config_dir|$bin_dir"
}

# Get list of wrapper names
_fplaunch_wrappers() {
    local dirs bin_dir
    dirs=$(_fplaunch_get_dirs)
    bin_dir="${dirs#*|}"
    
    if [ -d "$bin_dir" ]; then
        for f in "$bin_dir"/*; do
            if [ -f "$f" ] && [ -x "$f" ] && head -n 5 "$f" 2>/dev/null | grep -q "Generated by fplaunchwrapper"; then
                basename "$f"
            fi
        done
    fi
}

# Get list of blocked IDs
_fplaunch_blocked() {
    local dirs config_dir
    dirs=$(_fplaunch_get_dirs)
    config_dir="${dirs%|*}"
    
    if [ -f "$config_dir/blocklist" ]; then
        cat "$config_dir/blocklist" 2>/dev/null
    fi
}

# Get list of aliases
_fplaunch_aliases() {
    local dirs config_dir
    dirs=$(_fplaunch_get_dirs)
    config_dir="${dirs%|*}"
    
    if [ -f "$config_dir/aliases" ]; then
        awk '{print $2}' "$config_dir/aliases" 2>/dev/null
    fi
}

# Completion for fplaunch-manage
_fplaunch_manage() {
    local cur prev words cword
    _init_completion || return

    # List of all commands
    local commands="help list search remove remove-pref set-pref set-env remove-env list-env set-pref-all set-script set-post-script remove-script remove-post-script set-alias remove-alias export-prefs import-prefs export-config import-config block unblock list-blocked install launch info manifest regenerate files uninstall"

    # If we're completing the first argument (command)
    if [ "$cword" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return
    fi

    # Get the command (first argument)
    local command="${words[1]}"

    case "$command" in
        # Commands that take a wrapper name as second argument
        remove|remove-pref|list-env|remove-script|remove-post-script|info|launch)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_wrappers)" -- "$cur") )
            fi
            ;;
        
        # set-pref: wrapper name, then system|flatpak
        set-pref)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_wrappers)" -- "$cur") )
            elif [ "$cword" -eq 3 ]; then
                COMPREPLY=( $(compgen -W "system flatpak" -- "$cur") )
            fi
            ;;
        
        # set-pref-all: system|flatpak
        set-pref-all)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "system flatpak" -- "$cur") )
            fi
            ;;
        
        # set-env: wrapper name, var name, value (no completion for value)
        set-env)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_wrappers)" -- "$cur") )
            fi
            ;;
        
        # remove-env: wrapper name, var name
        remove-env)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_wrappers)" -- "$cur") )
            fi
            ;;
        
        # set-script/set-post-script: wrapper name, then file path
        set-script|set-post-script)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_wrappers)" -- "$cur") )
            elif [ "$cword" -eq 3 ]; then
                _filedir
            fi
            ;;
        
        # set-alias: wrapper name, then alias name
        set-alias)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_wrappers)" -- "$cur") )
            fi
            ;;
        
        # remove-alias: alias name
        remove-alias)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_aliases)" -- "$cur") )
            fi
            ;;
        
        # block: could complete with installed flatpak IDs
        block)
            if [ "$cword" -eq 2 ]; then
                if command -v flatpak >/dev/null 2>&1; then
                    local flatpak_ids=$(flatpak list --app --columns=application 2>/dev/null)
                    COMPREPLY=( $(compgen -W "$flatpak_ids" -- "$cur") )
                fi
            fi
            ;;
        
        # unblock: blocked IDs
        unblock)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_blocked)" -- "$cur") )
            fi
            ;;
        
        # manifest: wrapper name, then remote|local
        manifest)
            if [ "$cword" -eq 2 ]; then
                COMPREPLY=( $(compgen -W "$(_fplaunch_wrappers)" -- "$cur") )
            elif [ "$cword" -eq 3 ]; then
                COMPREPLY=( $(compgen -W "remote local" -- "$cur") )
            fi
            ;;
        
        # export/import: file paths
        export-prefs|import-prefs|export-config|import-config)
            if [ "$cword" -eq 2 ]; then
                _filedir
            fi
            ;;
        
        # search: no completion
        search)
            ;;
        
        # install: could complete with available flatpak apps (complex, skip)
        install)
            ;;
    esac
}

# Completion for fplaunch-generate
_fplaunch_generate() {
    local cur prev
    _init_completion || return
    
    # Only complete directory paths
    _filedir -d
}

# Completion for fplaunch-cleanup
_fplaunch_cleanup() {
    local cur prev
    _init_completion || return
    
    case "$prev" in
        --bin-dir)
            _filedir -d
            ;;
        *)
            COMPREPLY=( $(compgen -W "-y --yes --dry-run --bin-dir -h --help" -- "$cur") )
            ;;
    esac
}

# Completion for fplaunch-setup-systemd (no arguments)
_fplaunch_setup_systemd() {
    return 0
}

# Register completions
complete -F _fplaunch_manage fplaunch-manage
complete -F _fplaunch_generate fplaunch-generate
complete -F _fplaunch_cleanup fplaunch-cleanup
complete -F _fplaunch_setup_systemd fplaunch-setup-systemd