#!/bin/bash

BIN_DIR="${1:-$HOME/bin}"
mkdir -p "$BIN_DIR"

# Save BIN_DIR to config
CONFIG_DIR="$HOME/.config/flatpak-wrappers"
mkdir -p "$CONFIG_DIR"
echo "$BIN_DIR" > "$CONFIG_DIR/bin_dir"

# Get list of installed Flatpak app IDs (user and system)
if ! installed_ids=$( (flatpak list --app --columns=application 2>/dev/null; flatpak list --app --columns=application --system 2>/dev/null) | sort | uniq ); then
    echo "Error: Flatpak not installed or command failed."
    exit 1
fi

# Get list of existing wrapper scripts
shopt -s nullglob
existing_scripts=("$BIN_DIR"/*)
shopt -u nullglob

# Cleanup: Remove wrappers for uninstalled apps
for script in "${existing_scripts[@]}"; do
    script_path="$BIN_DIR/$script"
    if [ -f "$script_path" ] && grep -q "Generated by fplaunchwrapper" "$script_path"; then
        # Extract ID from script content
        id=$(grep "flatpak run" "$script_path" | head -1 | awk '{print $4}' | tr -d '"' || true)
        if [ -n "$id" ] && ! echo "$installed_ids" | grep -q "^$id$"; then
            rm "$script_path"
            pref_file="$HOME/.config/flatpak-wrappers/$script.pref"
            [ -f "$pref_file" ] && rm "$pref_file"
            # Remove aliases pointing to this wrapper
            sed -i "/^$script /d" "$HOME/.config/flatpak-wrappers/aliases" 2>/dev/null
            for alias in "$BIN_DIR"/*; do
                if [ -L "$alias" ] && [ "$(readlink "$alias" 2>/dev/null)" = "$script_path" ]; then
                    rm "$alias"
                fi
            done
            echo "Removed obsolete wrapper, preference, and aliases: $script"
        fi
    fi
done

# Create wrappers for installed apps
echo "$installed_ids" | while read -r id; do
    if [ -z "$id" ]; then continue; fi
    # Check blocklist
    if grep -q "^$id$" "$HOME/.config/flatpak-wrappers/blocklist" 2>/dev/null; then
        echo "Skipping blocked $id"
        continue
    fi
    name=$(echo "$id" | awk -F. '{print tolower($NF)}')
    if [ -z "$name" ] || [[ "$name" =~ [^a-z0-9_-] ]]; then
        echo "Skipping invalid name for $id"
        continue
    fi
    script_path="$BIN_DIR/$name"
    cat > "$script_path" << EOF
#!/bin/bash
# Generated by fplaunchwrapper

NAME="$name"
ID="$id"
PREF_DIR="\$HOME/.config/flatpak-wrappers"
PREF_FILE="\$PREF_DIR/\$NAME.pref"
SCRIPT_BIN_DIR="$BIN_DIR"

mkdir -p "\$PREF_DIR"

if [ "\$1" = "--help" ]; then
    echo "Wrapper for \$NAME"
    echo "Usage: \$0 [args]"
    echo "Run '\$0 --fpwrapper-help' for more options."
    exit 0
elif [ "\$1" = "--fpwrapper-help" ]; then
    echo "Wrapper for \$NAME"
    echo "Flatpak ID: \$ID"
    pref=\$(cat "\$PREF_FILE" 2>/dev/null || echo "none")
    echo "Current preference: \$pref"
    echo ""
    echo "Available options:"
    echo "  --help                       Show basic usage"
    echo "  --fpwrapper-help             Show this detailed help"
    echo "  --fpwrapper-info             Show wrapper info"
    echo "  --fpwrapper-config-dir       Show Flatpak data directory"
    echo "  --fpwrapper-sandbox-info     Show Flatpak sandbox details"
    echo "  --fpwrapper-edit-sandbox     Edit Flatpak permissions
  --fpwrapper-sandbox-yolo     Grant all permissions (dangerous)
  --fpwrapper-sandbox-reset   Reset sandbox to defaults
  --fpwrapper-set-override [system|flatpak]  Set launch preference"
    echo ""
    echo "Examples:"
    echo "  \$0 --fpwrapper-info"
    echo "  cd \$(\$0 --fpwrapper-config-dir)"
    echo "  \$0 --fpwrapper-sandbox-info"
    echo "  \$0 --fpwrapper-edit-sandbox
  $0 --fpwrapper-sandbox-yolo
  $0 --fpwrapper-sandbox-reset
  $0 --fpwrapper-set-override system"
    exit 0
elif [ "\$1" = "--fpwrapper-info" ]; then
    echo "Wrapper for \$NAME"
    echo "Flatpak ID: \$ID"
    pref=\$(cat "\$PREF_FILE" 2>/dev/null || echo "none")
    echo "Preference: \$pref"
    echo "Usage: \$0 [args]"
    exit 0
elif [ "\$1" = "--fpwrapper-config-dir" ]; then
    config_dir="\$HOME/.var/app/\$ID"
    echo "\$config_dir"
    exit 0
elif [ "\$1" = "--fpwrapper-sandbox-info" ]; then
    flatpak info "\$ID"
    exit 0
elif [ "\$1" = "--fpwrapper-edit-sandbox" ]; then
    echo "Flatpak Sandbox Editor for \$ID"
    echo "Common permissions:"
    echo "1. Allow filesystem access (e.g., ~/Documents)"
    echo "2. Allow device access (e.g., --device=dri)"
    echo "3. Allow network access"
    echo "4. Reset all overrides"
    echo "5. Show current overrides"
    echo "6. YOLO mode (open all permissions)"
    read -p "Choose an option (1-6): " opt
    case \$opt in
        1)
            read -p "Enter path (e.g., ~/Documents): " path
            flatpak override "\$ID" --filesystem="\$path"
            ;;
        2)
            read -p "Enter device (e.g., dri): " dev
            flatpak override "\$ID" --device="\$dev"
            ;;
        3)
            flatpak override "\$ID" --share=network
            ;;
        4)
            flatpak override --reset "\$ID"
            ;;
        5)
            flatpak override "\$ID"
            ;;
        6)
            echo "WARNING: YOLO mode grants extensive permissions and may pose security risks!"
            read -p "Are you sure? (yes/no): " confirm
            if [ "\$confirm" = "yes" ]; then
                flatpak override "\$ID" --filesystem=host --share=network --device=all --allow=devel
                echo "YOLO mode applied. Use 'flatpak override --reset \$ID' to reset."
            else
                echo "Cancelled."
            fi
            ;;
        *)
            echo "Invalid option"
            ;;
    esac
    exit 0
elif [ "\$1" = "--fpwrapper-sandbox-yolo" ]; then
    echo "WARNING: YOLO mode grants extensive permissions and may pose security risks!"
    read -p "Are you sure? (yes/no): " confirm
    if [ "\$confirm" = "yes" ]; then
        flatpak override "\$ID" --filesystem=host --share=network --device=all --allow=devel
        echo "YOLO mode applied. Use 'flatpak override --reset \$ID' to reset."
    else
        echo "Cancelled."
    fi
    exit 0
elif [ "\$1" = "--fpwrapper-set-override" ]; then
    if [ -z "\$2" ]; then
        echo "Choose override:"
        echo "1. system"
        echo "2. flatpak"
        read -r -p "Choice (1/2): " choice
        if [ "\$choice" = "1" ]; then
            pref="system"
        elif [ "\$choice" = "2" ]; then
            pref="flatpak"
        else
            echo "Invalid choice"
            exit 1
        fi
    else
        pref="\$2"
    fi
    if [ "\$pref" = "system" ] || [ "\$pref" = "flatpak" ]; then
        echo "\$pref" > "\$PREF_FILE"
        echo "Preference set to \$pref"
    else
        echo "Invalid override: use 'system' or 'flatpak'"
    fi
    exit 0
fi

if [ -f "\$PREF_FILE" ]; then
    PREF=\$(cat "\$PREF_FILE")
else
    PREF=""
fi

# Check for system command at launch time
SYSTEM_EXISTS=false
if command -v "\$NAME" >/dev/null 2>&1; then
    CMD_PATH=\$(which "\$NAME")
    if [[ "\$CMD_PATH" != "\$SCRIPT_BIN_DIR/\$NAME" ]]; then
        SYSTEM_EXISTS=true
    fi
fi

if [ "\$PREF" = "system" ]; then
    if [ "\$SYSTEM_EXISTS" = true ]; then
        exec "\$NAME" "\$@"
    else
        # System command gone, fall back to flatpak
        PREF="flatpak"
        echo "flatpak" > "\$PREF_FILE"
        exec flatpak run $id "\$@"
    fi
elif [ "\$PREF" = "flatpak" ]; then
    exec flatpak run $id "\$@"
else
    # No pref set
    if [ "\$SYSTEM_EXISTS" = true ]; then
        echo "Multiple options for '\$NAME':"
        echo "1. System package (\$CMD_PATH)"
        echo "2. Flatpak app (\$ID)"
        read -r -p "Choose (1/2, default 1): " choice
        choice=\${choice:-1}
        if [ "\$choice" = "1" ]; then
            PREF="system"
            echo "\$PREF" > "\$PREF_FILE"
            exec "\$NAME" "\$@"
        elif [ "\$choice" = "2" ]; then
            PREF="flatpak"
            echo "\$PREF" > "\$PREF_FILE"
            exec flatpak run $id "\$@"
        else
            echo "Invalid choice, defaulting to system."
            PREF="system"
            echo "\$PREF" > "\$PREF_FILE"
            exec "\$NAME" "\$@"
        fi
    else
        PREF="flatpak"
        echo "\$PREF" > "\$PREF_FILE"
        exec flatpak run $id "\$@"
    fi
fi
EOF
    chmod +x "$script_path"
    echo "Created/updated wrapper: $name"
done

echo "Flatpak wrapper generation complete."