#!/usr/bin/env bash

# Uninstall script for Flatpak Launch Wrappers

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
BIN_DIR_FILE="$CONFIG_DIR/bin_dir"
BIN_DIR="$HOME/.local/bin"  # default
if [ -f "$BIN_DIR_FILE" ]; then
    BIN_DIR=$(cat "$BIN_DIR_FILE")
fi

# Validate BIN_DIR is within user's home directory
case "$BIN_DIR" in
    "$HOME"/*|"$HOME")
        # Valid: within home directory
        ;;
    *)
        echo "Error: Uninstallation directory must be within your home directory ($HOME)"
        echo "Found: $BIN_DIR"
        echo "This script only operates on user installations."
        exit 1
        ;;
esac

read -r -p "Uninstall Flatpak Launch Wrappers from '$BIN_DIR'? This will remove all wrappers and preferences. (y/n): " confirm
if [[ ! $confirm =~ ^[Yy]$ ]]; then
    echo "Uninstallation cancelled."
    exit 0
fi

echo "Uninstalling Flatpak Launch Wrappers from $BIN_DIR..."

# Stop and disable systemd units
systemctl --user stop flatpak-wrappers.service 2>/dev/null || true
systemctl --user stop flatpak-wrappers.path 2>/dev/null || true
systemctl --user stop flatpak-wrappers.timer 2>/dev/null || true
systemctl --user disable flatpak-wrappers.service 2>/dev/null || true
systemctl --user disable flatpak-wrappers.path 2>/dev/null || true
systemctl --user disable flatpak-wrappers.timer 2>/dev/null || true

# Remove systemd unit files
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
rm -f "$UNIT_DIR/flatpak-wrappers.service"
rm -f "$UNIT_DIR/flatpak-wrappers.path"
rm -f "$UNIT_DIR/flatpak-wrappers.timer"
systemctl --user daemon-reload 2>/dev/null || true

# Remove cron job if exists
if command -v crontab &> /dev/null; then
    crontab -l 2>/dev/null | grep -v "$SCRIPT_DIR/fplaunch-generate" | crontab -
fi

# Remove wrappers, aliases, and manager
for script in "$BIN_DIR"/*; do
    if [ -f "$script" ] && grep -q "Generated by fplaunchwrapper" "$script" 2>/dev/null; then
        rm "$script"
    elif [ -L "$script" ] && [ -f "$script" ] && grep -q "Generated by fplaunchwrapper" "$script" 2>/dev/null; then
        # Check if symlink target is our wrapper
        rm "$script"
    elif [ "$script" = "$BIN_DIR/fplaunch-manage" ]; then
        rm "$script"
    fi
done

# Remove installed scripts and lib directory
rm -f "$BIN_DIR/fplaunch-generate"
rm -f "$BIN_DIR/fplaunch-setup-systemd"
rm -f "$BIN_DIR/fplaunch-cleanup"
if [ -n "$BIN_DIR" ] && [ -d "$BIN_DIR/lib" ]; then
    rm -rf "${BIN_DIR:?}/lib"
fi

# Remove bash completion
rm -f "$HOME/.bashrc.d/fplaunch_completion.bash"

# Remove man pages
MAN_DIR="$HOME/.local/share/man"
if [ -d "$MAN_DIR" ]; then
    rm -f "$MAN_DIR/man1/fplaunch-"*.1 2>/dev/null || true
    rm -f "$MAN_DIR/man7/fplaunchwrapper."* 2>/dev/null || true
    # Clean up empty directories
    rmdir "$MAN_DIR/man1" 2>/dev/null || true
    rmdir "$MAN_DIR/man7" 2>/dev/null || true
    rmdir "$MAN_DIR" 2>/dev/null || true
fi

# Remove config directory
rm -rf "$CONFIG_DIR"

echo "Uninstallation complete. All wrappers, preferences, man pages, and systemd units removed."