#!/bin/bash

# Uninstall script for Flatpak Launch Wrappers

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.config/flatpak-wrappers"
BIN_DIR_FILE="$CONFIG_DIR/bin_dir"
BIN_DIR="$HOME/bin"  # default
if [ -f "$BIN_DIR_FILE" ]; then
    BIN_DIR=$(cat "$BIN_DIR_FILE")
fi

echo "Uninstalling Flatpak Launch Wrappers from $BIN_DIR..."

# Stop and disable systemd units
systemctl --user stop flatpak-wrappers.service 2>/dev/null || true
systemctl --user stop flatpak-wrappers.path 2>/dev/null || true
systemctl --user stop flatpak-wrappers.timer 2>/dev/null || true
systemctl --user disable flatpak-wrappers.service 2>/dev/null || true
systemctl --user disable flatpak-wrappers.path 2>/dev/null || true
systemctl --user disable flatpak-wrappers.timer 2>/dev/null || true

# Remove systemd unit files
UNIT_DIR="$HOME/.config/systemd/user"
rm -f "$UNIT_DIR/flatpak-wrappers.service"
rm -f "$UNIT_DIR/flatpak-wrappers.path"
rm -f "$UNIT_DIR/flatpak-wrappers.timer"
systemctl --user daemon-reload 2>/dev/null || true

# Remove cron job if exists
if command -v crontab &> /dev/null; then
    crontab -l 2>/dev/null | grep -v "$SCRIPT_DIR/generate_flatpak_wrappers.sh" | crontab -
fi

# Remove wrappers, aliases, and manager
for script in "$BIN_DIR"/*; do
    if [ -f "$script" ] && grep -q "Generated by fplaunchwrapper" "$script" 2>/dev/null; then
        rm "$script"
    elif [ -L "$script" ] && [ -f "$script" ] && grep -q "Generated by fplaunchwrapper" "$script" 2>/dev/null; then
        # Check if symlink target is our wrapper
        rm "$script"
    elif [ "$script" = "$BIN_DIR/fplaunch-manage" ]; then
        rm "$script"
    fi
done

# Remove config directory
rm -rf "$CONFIG_DIR"

echo "Uninstallation complete. Wrappers, preferences, and systemd units removed."