#!/usr/bin/env bash
# Integration tests - testing complete workflows
# Self-contained end-to-end testing

set -e

TEST_DIR="/tmp/fplaunch-integration-test-$$"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0

cleanup() {
    rm -rf "$TEST_DIR"
}
trap cleanup EXIT

log_test() {
    echo -e "${BLUE}[TEST]${NC} $1"
}

log_pass() {
    echo -e "${GREEN}✓${NC} $1"
    ((TESTS_PASSED++))
}

log_fail() {
    echo -e "${RED}✗${NC} $1"
    ((TESTS_FAILED++))
}

# Integration Test 1: Complete wrapper lifecycle
test_wrapper_lifecycle() {
    log_test "Complete wrapper lifecycle (create, use, update, remove)"
    
    local test_bin="$TEST_DIR/bin"
    local test_config="$TEST_DIR/config"
    mkdir -p "$test_bin" "$test_config"
    
    # Step 1: Create wrapper
    cat > "$test_bin/myapp" << 'EOF'
#!/usr/bin/env bash
# Generated by fplaunchwrapper
NAME="myapp"
ID="com.example.MyApp"
VERSION="1.0"
echo "Running $NAME version $VERSION"
EOF
    chmod +x "$test_bin/myapp"
    
    if [ -x "$test_bin/myapp" ]; then
        log_pass "Wrapper created and executable"
    else
        log_fail "Wrapper not created properly"
    fi
    
    # Step 2: Set preference
    echo "flatpak" > "$test_config/myapp.pref"
    if [ "$(cat "$test_config/myapp.pref")" = "flatpak" ]; then
        log_pass "Preference saved"
    else
        log_fail "Preference not saved"
    fi
    
    # Step 3: Update wrapper (version change)
    sed -i 's/VERSION="1.0"/VERSION="1.1"/' "$test_bin/myapp"
    if grep -q 'VERSION="1.1"' "$test_bin/myapp"; then
        log_pass "Wrapper updated"
    else
        log_fail "Wrapper update failed"
    fi
    
    # Step 4: Preference persists after update
    if [ "$(cat "$test_config/myapp.pref")" = "flatpak" ]; then
        log_pass "Preference persisted after update"
    else
        log_fail "Preference lost after update"
    fi
    
    # Step 5: Remove wrapper and cleanup
    rm "$test_bin/myapp"
    rm "$test_config/myapp.pref"
    
    if [ ! -f "$test_bin/myapp" ] && [ ! -f "$test_config/myapp.pref" ]; then
        log_pass "Wrapper and config removed"
    else
        log_fail "Cleanup incomplete"
    fi
}

# Integration Test 2: Multi-wrapper with collision
test_multi_wrapper_collision() {
    log_test "Multiple wrappers with name collision handling"
    
    local test_bin="$TEST_DIR/bin2"
    mkdir -p "$test_bin"
    
    # Simulate installing multiple apps
    declare -A wrapper_names
    local installed_ids="com.google.Chrome
org.chromium.Chromium
com.microsoft.edge
org.mozilla.Firefox
com.brave.Browser"
    
    local created=0
    local skipped=0
    
    while read -r id; do
        [ -z "$id" ] && continue
        name=$(echo "$id" | awk -F. '{print tolower($NF)}')
        
        if [ -n "${wrapper_names[$name]}" ]; then
            ((skipped++))
            continue
        fi
        
        wrapper_names[$name]=$id
        cat > "$test_bin/$name" << EOF
#!/bin/bash
ID="$id"
EOF
        chmod +x "$test_bin/$name"
        ((created++))
    done < <(echo "$installed_ids")
    
    if [ $created -eq 5 ] && [ $skipped -eq 0 ]; then
        log_pass "All 5 unique wrappers created"
    else
        log_fail "Expected 5 created, 0 skipped; got $created created, $skipped skipped"
    fi
    
    # Verify each wrapper exists
    for name in chrome chromium edge firefox browser; do
        if [ -f "$test_bin/$name" ]; then
            log_pass "Wrapper exists: $name"
        else
            log_fail "Wrapper missing: $name"
        fi
    done
}

# Integration Test 3: Preference override workflow
test_preference_override_workflow() {
    log_test "Preference override and fallback workflow"
    
    local test_config="$TEST_DIR/config3"
    mkdir -p "$test_config"
    
    # User chooses system
    echo "system" > "$test_config/editor.pref"
    log_pass "User chose 'system'"
    
    # Simulate system package removed (fallback to flatpak)
    pref=$(cat "$test_config/editor.pref")
    if [ "$pref" = "system" ]; then
        # System command gone, fallback
        echo "flatpak" > "$test_config/editor.pref"
        log_pass "Fallback to flatpak after system removed"
    fi
    
    # Verify new preference
    if [ "$(cat "$test_config/editor.pref")" = "flatpak" ]; then
        log_pass "Preference updated to flatpak"
    else
        log_fail "Preference not updated"
    fi
}

# Integration Test 4: Alias chain
test_alias_chain() {
    log_test "Alias creation and resolution"
    
    local test_bin="$TEST_DIR/bin4"
    local test_config="$TEST_DIR/config4"
    mkdir -p "$test_bin" "$test_config"
    
    # Create base wrapper
    cat > "$test_bin/chrome" << 'EOF'
#!/bin/bash
echo "Chrome wrapper"
EOF
    chmod +x "$test_bin/chrome"
    
    # Create aliases
    ln -s "$test_bin/chrome" "$test_bin/browser"
    ln -s "$test_bin/chrome" "$test_bin/web"
    
    echo "browser chrome" >> "$test_config/aliases"
    echo "web chrome" >> "$test_config/aliases"
    
    if [ -L "$test_bin/browser" ] && [ -L "$test_bin/web" ]; then
        log_pass "Aliases created"
    else
        log_fail "Aliases not created"
    fi
    
    # Verify aliases point to correct target
    if [ "$(readlink "$test_bin/browser")" = "$test_bin/chrome" ]; then
        log_pass "Alias 'browser' points to chrome"
    else
        log_fail "Alias 'browser' incorrect"
    fi
    
    # Test alias execution
    output=$("$test_bin/browser" 2>&1)
    if echo "$output" | grep -q "Chrome wrapper"; then
        log_pass "Alias execution works"
    else
        log_fail "Alias execution failed"
    fi
}

# Integration Test 5: Environment and script combination
test_env_and_script_combo() {
    log_test "Environment variables + pre-launch script integration"
    
    local test_bin="$TEST_DIR/bin5"
    local test_config="$TEST_DIR/config5"
    mkdir -p "$test_bin" "$test_config/scripts/testapp"
    
    # Create env file
    cat > "$test_config/testapp.env" << 'EOF'
export MY_VAR="from_env"
export MY_PATH="/custom/path"
EOF
    
    # Create pre-launch script
    cat > "$test_config/scripts/testapp/pre-launch.sh" << 'EOF'
#!/bin/bash
echo "Pre-launch: MY_VAR=$MY_VAR"
echo "Pre-launch: MY_PATH=$MY_PATH"
EOF
    chmod +x "$test_config/scripts/testapp/pre-launch.sh"
    
    # Create wrapper that loads env and runs pre-launch
    cat > "$test_bin/testapp" << 'EOF'
#!/bin/bash
NAME="testapp"
CONFIG_DIR="${1:-/tmp}"

# Load env
ENV_FILE="$CONFIG_DIR/testapp.env"
if [ -f "$ENV_FILE" ]; then
    source "$ENV_FILE"
fi

# Run pre-launch
PRE_SCRIPT="$CONFIG_DIR/scripts/testapp/pre-launch.sh"
if [ -f "$PRE_SCRIPT" ] && [ -x "$PRE_SCRIPT" ]; then
    "$PRE_SCRIPT"
fi

echo "App: MY_VAR=$MY_VAR"
EOF
    chmod +x "$test_bin/testapp"
    
    output=$("$test_bin/testapp" "$test_config" 2>&1)
    
    if echo "$output" | grep -q "Pre-launch: MY_VAR=from_env"; then
        log_pass "Pre-launch script has access to environment variables"
    else
        log_fail "Pre-launch script missing environment variables"
    fi
    
    if echo "$output" | grep -q "App: MY_VAR=from_env"; then
        log_pass "Main app has access to environment variables"
    else
        log_fail "Main app missing environment variables"
    fi
}

# Integration Test 6: Blocklist with regeneration
test_blocklist_regeneration() {
    log_test "Blocklist prevents wrapper regeneration"
    
    local test_bin="$TEST_DIR/bin6"
    local test_config="$TEST_DIR/config6"
    mkdir -p "$test_bin" "$test_config"
    
    # Create blocklist
    cat > "$test_config/blocklist" << 'EOF'
com.blocked.App1
com.blocked.App2
EOF
    
    # Simulate wrapper generation with blocklist check
    local apps="com.allowed.App
com.blocked.App1
com.another.Allowed
com.blocked.App2"
    
    local created=0
    local blocked=0
    
    while read -r id; do
        [ -z "$id" ] && continue
        
        if grep -q "^$id$" "$test_config/blocklist"; then
            ((blocked++))
            continue
        fi
        
        name=$(echo "$id" | awk -F. '{print tolower($NF)}')
        cat > "$test_bin/$name" << EOF
#!/bin/bash
ID="$id"
EOF
        chmod +x "$test_bin/$name"
        ((created++))
    done < <(echo "$apps")
    
    if [ $created -eq 2 ] && [ $blocked -eq 2 ]; then
        log_pass "Blocklist correctly filtered apps (2 created, 2 blocked)"
    else
        log_fail "Blocklist filtering incorrect: $created created, $blocked blocked"
    fi
    
    if [ -f "$test_bin/app" ] && [ -f "$test_bin/allowed" ]; then
        log_pass "Allowed wrappers created"
    else
        log_fail "Allowed wrappers not created"
    fi
    
    if [ ! -f "$test_bin/app1" ] && [ ! -f "$test_bin/app2" ]; then
        log_pass "Blocked wrappers not created"
    else
        log_fail "Blocked wrappers were created"
    fi
}

# Integration Test 7: Export, modify, import workflow
test_export_modify_import() {
    log_test "Export-modify-import configuration workflow"
    
    local test_config="$TEST_DIR/config7"
    mkdir -p "$test_config"
    
    # Create initial config
    echo "system" > "$test_config/app1.pref"
    echo "flatpak" > "$test_config/app2.pref"
    echo "com.blocked.App" > "$test_config/blocklist"
    
    # Export
    tar -czf "$TEST_DIR/backup.tar.gz" -C "$test_config" . 2>/dev/null
    
    if [ -f "$TEST_DIR/backup.tar.gz" ]; then
        log_pass "Configuration exported"
    else
        log_fail "Export failed"
    fi
    
    # Modify
    rm -rf "$test_config"/*
    echo "flatpak" > "$test_config/app1.pref"  # Changed
    
    # Import
    tar -xzf "$TEST_DIR/backup.tar.gz" -C "$test_config" 2>/dev/null
    
    if [ "$(cat "$test_config/app1.pref")" = "system" ]; then
        log_pass "Original configuration restored"
    else
        log_fail "Configuration not restored correctly"
    fi
    
    if [ -f "$test_config/blocklist" ]; then
        log_pass "Blocklist restored"
    else
        log_fail "Blocklist not restored"
    fi
}

# Main test runner
main() {
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}Integration Test Suite${NC}"
    echo -e "${BLUE}======================================${NC}"
    echo ""
    
    test_wrapper_lifecycle
    echo ""
    test_multi_wrapper_collision
    echo ""
    test_preference_override_workflow
    echo ""
    test_alias_chain
    echo ""
    test_env_and_script_combo
    echo ""
    test_blocklist_regeneration
    echo ""
    test_export_modify_import
    
    echo ""
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}Integration Test Results${NC}"
    echo -e "${BLUE}======================================${NC}"
    echo -e "${GREEN}Passed: $TESTS_PASSED${NC}"
    echo -e "${RED}Failed: $TESTS_FAILED${NC}"
    echo "Total:  $((TESTS_PASSED + TESTS_FAILED))"
    echo -e "${BLUE}======================================${NC}"
    
    if [ $TESTS_FAILED -eq 0 ]; then
        echo -e "${GREEN}All integration tests passed!${NC}"
        exit 0
    else
        echo -e "${RED}Some integration tests failed!${NC}"
        exit 1
    fi
}

main "$@"
