#!/usr/bin/env bash

# Test suite for wrapper --fpwrapper-* options functionality
# Tests all wrapper command-line options and features
#
# WHY THESE TESTS MATTER:
# - --fpwrapper-* options: Core user-facing wrapper functionality
#   If broken: Users can't manage wrappers, edit permissions, or get info
# - Sandbox editing: Critical security feature for permission management
#   If broken: Users can't customize app permissions or troubleshoot issues
# - Script management: Pre/post launch scripts for automation
#   If broken: Automation workflows fail, custom integrations broken
# - Force interactive: Testing and debugging capability
#   If broken: Developers can't test wrapper behavior reliably

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Test counters
PASSED=0
FAILED=0

pass() {
    echo -e "${GREEN}✓${NC} $1"
    PASSED=$((PASSED + 1))
}

fail() {
    echo -e "${RED}✗${NC} $1"
    FAILED=$((FAILED + 1))
}

info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Developer workstation safety check
ensure_developer_safety() {
    # Never run on production systems
    if [ "${CI:-}" != "1" ] && [ "${TESTING:-}" != "1" ]; then
        # Check if we're in a development environment
        if [ ! -f "$PROJECT_ROOT/README.md" ] || [ ! -d "$PROJECT_ROOT/tests" ]; then
            echo "ERROR: This test must be run from the project root directory"
            echo "Run with: TESTING=1 tests/test_wrapper_options.sh"
            exit 1
        fi
    fi
    
    # Ensure we're not running as root
    if [ "$(id -u)" = "0" ]; then
        echo "ERROR: Refusing to run tests as root for safety"
        exit 1
    fi
    
    # Set testing environment
    export TESTING=1
    export CI=1
}

# Create isolated test environment
setup_test_env() {
    local test_home="/tmp/fplaunch-wrapper-options-test-$$"
    
    # Clean up any existing test directory
    rm -rf "$test_home"
    
    # Create test directory structure
    mkdir -p "$test_home"/{bin,.config,.local/share/applications}
    
    # Override environment for test isolation
    export HOME="$test_home"
    export XDG_CONFIG_HOME="$test_home/.config"
    export XDG_DATA_HOME="$test_home/.local"
    export PATH="$test_home/bin:$PATH"
    
    # Create mock flatpak command
    cat > "$test_home/bin/flatpak" << 'EOF'
#!/usr/bin/env bash
case "$1" in
    "list")
        echo "com.test.App"
        echo "com.example.TestApp"
        ;;
    "run")
        echo "Mock flatpak run $*"
        exit 0
        ;;
    "info")
        echo "Mock flatpak info for $2"
        exit 0
        ;;
    *)
        echo "Mock flatpak $*"
        exit 0
        ;;
esac
EOF
    chmod +x "$test_home/bin/flatpak"
    
    echo "$test_home"
}

# Cleanup test environment
cleanup_test_env() {
    local test_home="$1"
    rm -rf "$test_home"
}

# Create a test wrapper
create_test_wrapper() {
    local test_home="$1"
    local name="testapp"
    local id="com.test.App"
    local bin_dir="$test_home/bin"
    
    # Create wrapper script
    cat > "$bin_dir/$name" << EOF
#!/usr/bin/env bash
# Generated by fplaunchwrapper

NAME="$name"
ID="$id"
PREF_DIR="$1/.config/flatpak-wrappers"
PREF_FILE="\$PREF_DIR/\$NAME.pref"
SCRIPT_BIN_DIR="$bin_dir"

echo "DEBUG: PREF_DIR=\$PREF_DIR" >&2
mkdir -p "\$PREF_DIR"

# Check if running in interactive CLI
is_interactive() {
    [ "\${FPWRAPPER_FORCE:-}" = "interactive" ] || ([ -t 0 ] && [ -t 1 ] && [ "\${FPWRAPPER_FORCE:-}" != "desktop" ])
}

# Check for force flag for testing
if [ "\$1" = "--fpwrapper-force-interactive" ]; then
    export FPWRAPPER_FORCE=interactive
    shift
fi

if [ "\$1" = "--fpwrapper-help" ]; then
    echo "Wrapper for \$NAME"
    echo "Flatpak ID: \$ID"
    pref=\$(cat "\$PREF_FILE" 2>/dev/null || echo "none")
    echo "Current preference: \$pref"
    echo ""
    echo "Available options:"
    echo "  --help                          Show basic usage"
    echo "  --fpwrapper-help             Show this detailed help"
    echo "  --fpwrapper-info             Show wrapper info"
    echo "  --fpwrapper-config-dir       Show Flatpak data directory"
    echo "  --fpwrapper-sandbox-info     Show Flatpak sandbox details"
    echo "  --fpwrapper-edit-sandbox     Edit Flatpak permissions"
    echo "  --fpwrapper-sandbox-yolo     Grant all permissions (dangerous)"
    echo "  --fpwrapper-sandbox-reset    Reset sandbox to defaults"
    echo "  --fpwrapper-run-unrestricted Run with unrestricted permissions (transient)"
    echo "  --fpwrapper-force-interactive    Force interactive mode for testing"
    echo "  --fpwrapper-set-override [system|flatpak]  Set launch preference"
    echo "  --fpwrapper-set-pre-script <script>        Set pre-launch script"
    echo "  --fpwrapper-set-post-script <script>       Set post-run script"
    echo "  --fpwrapper-remove-pre-script               Remove pre-launch script"
    echo "  --fpwrapper-remove-post-script              Remove post-run script"
    echo ""
    echo "Examples:"
    echo "  \$NAME --fpwrapper-info"
    echo "  cd \"\\\$(\\\$NAME --fpwrapper-config-dir)\""
    echo "  \$NAME --fpwrapper-sandbox-info"
    echo "  \$NAME --fpwrapper-edit-sandbox"
    echo "  \$NAME --fpwrapper-sandbox-yolo"
    echo "  \$NAME --fpwrapper-sandbox-reset"
    echo "  \$NAME --fpwrapper-run-unrestricted"
    echo "  \$NAME --fpwrapper-force-interactive"
    echo "  \$NAME --fpwrapper-set-override system"
    echo "  \$NAME --fpwrapper-set-pre-script ~/scripts/my-pre-script.sh"
    echo "  \$NAME --fpwrapper-set-post-script ~/scripts/my-post-script.sh"
    echo "  \$NAME --fpwrapper-remove-pre-script"
    echo "  \$NAME --fpwrapper-remove-post-script"
    exit 0
elif [ "\$1" = "--fpwrapper-info" ]; then
    echo "Wrapper for \$NAME"
    echo "Flatpak ID: \$ID"
    pref=\$(cat "\$PREF_FILE" 2>/dev/null || echo "none")
    echo "Preference: \$pref"
    echo "Usage: \$0 [args]"
    exit 0
elif [ "\$1" = "--fpwrapper-config-dir" ]; then
    config_dir="\${XDG_DATA_HOME:-\${HOME}/.local}/share/applications/\$ID"
    echo "\$config_dir"
    exit 0
elif [ "\$1" = "--fpwrapper-sandbox-info" ]; then
    flatpak info "\$ID"
    exit 0
elif [ "\$1" = "--fpwrapper-edit-sandbox" ]; then
    if ! is_interactive; then
        echo "Error: Sandbox editing requires interactive CLI" >&2
        exit 1
    fi
    echo "Flatpak Sandbox Editor for \$ID"
    echo "Common permissions:"
    echo "  --filesystem=home"
    echo "  --filesystem=host"
    echo "  --share=network"
    echo "  --share=ipc"
    echo "  --device=dri"
    echo "  --socket=pulseaudio"
    echo "  --socket=wayland"
    echo "  --socket=x11"
    echo ""
    echo "Enter permissions (one per line, empty line to finish):"
    exit 0
elif [ "\$1" = "--fpwrapper-sandbox-yolo" ]; then
    if ! is_interactive; then
        echo "Error: YOLO mode requires interactive CLI" >&2
        exit 1
    fi
    echo "WARNING: YOLO mode will grant ALL permissions to \$ID"
    echo "This is dangerous and should only be used for testing!"
    echo ""
    read -p "Are you sure you want to continue? [y/N] " response
    case "\$response" in
        [yY]|[yY][eE][sS])
            echo "Granting all permissions to \$ID..."
            echo "YOLO mode activated - use responsibly!"
            ;;
        *)
            echo "Cancelled YOLO mode"
            exit 0
            ;;
    esac
    exit 0
elif [ "\$1" = "--fpwrapper-sandbox-reset" ]; then
    echo "Resetting sandbox permissions for \$ID to defaults"
    exit 0
elif [ "\$1" = "--fpwrapper-run-unrestricted" ]; then
    echo "Running \$ID with unrestricted permissions (transient)"
    exec flatpak run "\$ID" "\$@"
elif [ "\$1" = "--fpwrapper-set-override" ]; then
    override="\${2:-}"
    if [ -z "\$override" ]; then
        echo "Error: Must specify override type (system|flatpak)" >&2
        exit 1
    fi
    case "\$override" in
        "system"|"flatpak")
            echo "\$override" > "\$PREF_FILE"
            echo "Set launch preference for \$NAME to: \$override"
            ;;
        *)
            echo "Error: Invalid override type '\$override'. Use 'system' or 'flatpak'" >&2
            exit 1
            ;;
    esac
    exit 0
elif [ "\$1" = "--fpwrapper-set-pre-script" ]; then
    script_path="\${2:-}"
    if [ -z "\$script_path" ]; then
        echo "Error: Must specify script path" >&2
        exit 1
    fi
    if [ ! -f "\$script_path" ]; then
        echo "Error: Script not found: \$script_path" >&2
        exit 1
    fi
    mkdir -p "\$PREF_DIR"
    echo "\$script_path" > "\$PREF_DIR/\$NAME.pre-script"
    echo "Set pre-launch script for \$NAME to: \$script_path"
    exit 0
elif [ "\$1" = "--fpwrapper-set-post-script" ]; then
    script_path="\${2:-}"
    if [ -z "\$script_path" ]; then
        echo "Error: Must specify script path" >&2
        exit 1
    fi
    if [ ! -f "\$script_path" ]; then
        echo "Error: Script not found: \$script_path" >&2
        exit 1
    fi
    mkdir -p "\$PREF_DIR"
    echo "\$script_path" > "\$PREF_DIR/\$NAME.post-script"
    echo "Set post-run script for \$NAME to: \$script_path"
    exit 0
elif [ "\$1" = "--fpwrapper-remove-pre-script" ]; then
    if [ -f "\$PREF_DIR/\$NAME.pre-script" ]; then
        rm "\$PREF_DIR/\$NAME.pre-script"
        echo "Removed pre-launch script for \$NAME"
    else
        echo "No pre-launch script found for \$NAME"
    fi
    exit 0
elif [ "\$1" = "--fpwrapper-remove-post-script" ]; then
    if [ -f "\$PREF_DIR/\$NAME.post-script" ]; then
        rm "\$PREF_DIR/\$NAME.post-script"
        echo "Removed post-run script for \$NAME"
    else
        echo "No post-run script found for \$NAME"
    fi
    exit 0
fi

# Non-interactive bypass: skip wrapper and continue PATH search
if ! is_interactive; then
    # Find next executable in PATH (skip our wrapper)
    IFS=: read -ra PATH_DIRS <<< "\$PATH"
    for dir in "\${PATH_DIRS[@]}"; do
        if [ -x "\$dir/\$NAME" ] && [ "\$dir/\$NAME" != "\$SCRIPT_BIN_DIR/\$NAME" ]; then
            exec "\$dir/\$NAME" "\$@"
        fi
    done
    
    # If no system command found, run flatpak
    exec flatpak run "\$ID" "\$@"
fi

# Default behavior: run flatpak
exec flatpak run "\$ID" "\$@"
EOF
    
    chmod +x "$bin_dir/$name"
}

# Test wrapper help functionality
test_wrapper_help() {
    local test_home="$1"

    info "Testing --fpwrapper-help option"

    local output
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-force-interactive --fpwrapper-help 2>&1)
    
    if echo "$output" | grep -q "Wrapper for testapp"; then
        pass "Help shows wrapper name"
    else
        fail "Help missing wrapper name"
    fi
    
    if echo "$output" | grep -q "Flatpak ID: com.test.App"; then
        pass "Help shows Flatpak ID"
    else
        fail "Help missing Flatpak ID"
    fi
    
    if echo "$output" | grep -q "Available options:"; then
        pass "Help shows available options"
    else
        fail "Help missing options list"
    fi
    
    if echo "$output" | grep -q "fpwrapper-edit-sandbox"; then
        pass "Help includes sandbox editing option"
    else
        fail "Help missing sandbox editing option"
    fi
}

# Test wrapper info functionality
test_wrapper_info() {
    local test_home="$1"

    info "Testing --fpwrapper-info option"

    local output
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-force-interactive --fpwrapper-info 2>&1)
    
    if echo "$output" | grep -q "Wrapper for testapp"; then
        pass "Info shows wrapper name"
    else
        fail "Info missing wrapper name"
    fi
    
    if echo "$output" | grep -q "Flatpak ID: com.test.App"; then
        pass "Info shows Flatpak ID"
    else
        fail "Info missing Flatpak ID"
    fi
    
    if echo "$output" | grep -q "Preference: none"; then
        pass "Info shows default preference"
    else
        fail "Info missing preference"
    fi
}

# Test config directory functionality
test_config_dir() {
    local test_home="$1"

    info "Testing --fpwrapper-config-dir option"

    local output
    output=$(HOME="$test_home" XDG_DATA_HOME="$test_home/.local" "$test_home/bin/testapp" --fpwrapper-force-interactive --fpwrapper-config-dir 2>&1)

    local expected_dir="$test_home/.local/share/applications/com.test.App"
    if [ "$output" = "$expected_dir" ]; then
        pass "Config directory path is correct"
    else
        fail "Config directory path incorrect: expected $expected_dir, got $output"
    fi
}

# Test sandbox info functionality
test_sandbox_info() {
    local test_home="$1"

    info "Testing --fpwrapper-sandbox-info option"

    local output
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-force-interactive --fpwrapper-sandbox-info 2>&1)
    
    if echo "$output" | grep -q "Mock flatpak info for com.test.App"; then
        pass "Sandbox info calls flatpak info"
    else
        fail "Sandbox info not calling flatpak info correctly"
    fi
}

# Test sandbox editing functionality
test_sandbox_edit() {
    local test_home="$1"

    info "Testing --fpwrapper-edit-sandbox option"

    # Ensure environment is set
    export HOME="$test_home"
    export XDG_CONFIG_HOME="$test_home/.config"
    export XDG_DATA_HOME="$test_home/.local"
    export PATH="$test_home/bin:$PATH"

    # Test interactive mode (force interactive)
    local output
    output=$("$test_home/bin/testapp" --fpwrapper-force-interactive --fpwrapper-edit-sandbox 2>&1)
    
    if echo "$output" | grep -q "Flatpak Sandbox Editor for com.test.App"; then
        pass "Sandbox edit shows correct app"
    else
        fail "Sandbox edit not showing correct app"
    fi
    
    if echo "$output" | grep -q "Common permissions:"; then
        pass "Sandbox edit shows permission options"
    else
        fail "Sandbox edit missing permission options"
    fi
    
    # Test non-interactive mode rejection
    output=$(echo "" | "$test_home/bin/testapp" --fpwrapper-edit-sandbox 2>&1 || true)
    
    if echo "$output" | grep -q "Error: Sandbox editing requires interactive CLI"; then
        pass "Sandbox edit rejects non-interactive mode"
    else
        fail "Sandbox edit should reject non-interactive mode"
    fi
}

# Test YOLO mode functionality
test_sandbox_yolo() {
    local test_home="$1"

    info "Testing --fpwrapper-sandbox-yolo option"

    # Ensure environment is set
    export HOME="$test_home"
    export XDG_CONFIG_HOME="$test_home/.config"
    export XDG_DATA_HOME="$test_home/.local"
    export PATH="$test_home/bin:$PATH"

    # Test interactive mode shows warning (with input to avoid hanging)
    local output
    output=$(echo "n" | "$test_home/bin/testapp" --fpwrapper-force-interactive --fpwrapper-sandbox-yolo 2>&1)
    
    if echo "$output" | grep -q "WARNING: YOLO mode will grant ALL permissions"; then
        pass "YOLO mode shows warning"
    else
        fail "YOLO mode missing warning"
    fi
    
    if echo "$output" | grep -q "This is dangerous"; then
        pass "YOLO mode shows danger warning"
    else
        fail "YOLO mode missing danger warning"
    fi
    
    if echo "$output" | grep -q "Cancelled YOLO mode"; then
        pass "YOLO mode can be cancelled"
    else
        fail "YOLO mode cancellation not working"
    fi
    
    # Test non-interactive mode rejection
    output=$(echo "" | "$test_home/bin/testapp" --fpwrapper-sandbox-yolo 2>&1 || true)
    
    if echo "$output" | grep -q "Error: YOLO mode requires interactive CLI"; then
        pass "YOLO mode rejects non-interactive mode"
    else
        fail "YOLO mode should reject non-interactive mode"
    fi
}

# Test sandbox reset functionality
test_sandbox_reset() {
    local test_home="$1"

    info "Testing --fpwrapper-sandbox-reset option"

    local output
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-sandbox-reset 2>&1)
    
    if echo "$output" | grep -q "Resetting sandbox permissions for com.test.App to defaults"; then
        pass "Sandbox reset shows correct message"
    else
        fail "Sandbox reset not working correctly"
    fi
}

# Test unrestricted run functionality
test_unrestricted_run() {
    local test_home="$1"

    info "Testing --fpwrapper-run-unrestricted option"
    
    local output
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-run-unrestricted --help 2>&1)
    
    if echo "$output" | grep -q "Mock flatpak run com.test.App --help"; then
        pass "Unrestricted run passes arguments to flatpak"
    else
        fail "Unrestricted run not passing arguments correctly"
    fi
}

# Test override setting functionality
test_set_override() {
    local test_home="$1"

    info "Testing --fpwrapper-set-override option"

    # Ensure environment is set
    export HOME="$test_home"
    export XDG_CONFIG_HOME="$test_home/.config"
    export XDG_DATA_HOME="$test_home/.local"
    export PATH="$test_home/bin:$PATH"

    # Test setting system override
    local output
    output=$("$test_home/bin/testapp" --fpwrapper-set-override system 2>&1)
    
    if echo "$output" | grep -q "Set launch preference for testapp to: system"; then
        pass "System override set correctly"
    else
        fail "System override not working"
    fi
    
    # Verify preference file was created
    if [ -f "$test_home/.config/flatpak-wrappers/testapp.pref" ]; then
        pass "Preference file created"
    else
        fail "Preference file not created"
    fi
    
    if [ "$(cat "$test_home/.config/flatpak-wrappers/testapp.pref")" = "system" ]; then
        pass "Preference file contains correct value"
    else
        fail "Preference file contains incorrect value"
    fi
    
    # Test setting flatpak override
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-set-override flatpak 2>&1)
    
    if echo "$output" | grep -q "Set launch preference for testapp to: flatpak"; then
        pass "Flatpak override set correctly"
    else
        fail "Flatpak override not working"
    fi
    
    # Test invalid override
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-set-override invalid 2>&1 || true)

    if echo "$output" | grep -q "Error: Invalid override type"; then
        pass "Invalid override rejected correctly"
    else
        fail "Invalid override should be rejected"
    fi

    # Test missing override argument
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-set-override 2>&1 || true)
    
    if echo "$output" | grep -q "Error: Must specify override type"; then
        pass "Missing override argument rejected"
    else
        fail "Missing override argument should be rejected"
    fi
}

# Test script management functionality
test_script_management() {
    local test_home="$1"
    
    info "Testing script management options"
    
    # Create test scripts
    mkdir -p "$test_home/scripts"
    echo "#!/bin/bash" > "$test_home/scripts/pre.sh"
    echo "echo 'Pre-launch script'" >> "$test_home/scripts/pre.sh"
    chmod +x "$test_home/scripts/pre.sh"
    
    echo "#!/bin/bash" > "$test_home/scripts/post.sh"
    echo "echo 'Post-run script'" >> "$test_home/scripts/post.sh"
    chmod +x "$test_home/scripts/post.sh"
    
    # Test setting pre-script
    local output
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-set-pre-script "$test_home/scripts/pre.sh" 2>&1)
    
    if echo "$output" | grep -q "Set pre-launch script for testapp to:"; then
        pass "Pre-launch script set correctly"
    else
        fail "Pre-launch script not working"
    fi
    
    # Verify pre-script file was created
    if [ -f "$test_home/.config/flatpak-wrappers/testapp.pre-script" ]; then
        pass "Pre-script file created"
    else
        fail "Pre-script file not created"
    fi
    
    # Test setting post-script
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-set-post-script "$test_home/scripts/post.sh" 2>&1)
    
    if echo "$output" | grep -q "Set post-run script for testapp to:"; then
        pass "Post-run script set correctly"
    else
        fail "Post-run script not working"
    fi
    
    # Verify post-script file was created
    if [ -f "$test_home/.config/flatpak-wrappers/testapp.post-script" ]; then
        pass "Post-script file created"
    else
        fail "Post-script file not created"
    fi
    
    # Test removing pre-script
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-remove-pre-script 2>&1)
    
    if echo "$output" | grep -q "Removed pre-launch script for testapp"; then
        pass "Pre-launch script removed correctly"
    else
        fail "Pre-launch script removal not working"
    fi
    
    if [ ! -f "$test_home/.config/flatpak-wrappers/testapp.pre-script" ]; then
        pass "Pre-script file actually removed"
    else
        fail "Pre-script file not actually removed"
    fi
    
    # Test removing post-script
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-remove-post-script 2>&1)
    
    if echo "$output" | grep -q "Removed post-run script for testapp"; then
        pass "Post-run script removed correctly"
    else
        fail "Post-run script removal not working"
    fi
    
    if [ ! -f "$test_home/.config/flatpak-wrappers/testapp.post-script" ]; then
        pass "Post-script file actually removed"
    else
        fail "Post-script file not actually removed"
    fi
    
    # Test setting non-existent script
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-set-pre-script "/non/existent/script.sh" 2>&1 || true)
    
    if echo "$output" | grep -q "Error: Script not found:"; then
        pass "Non-existent script rejected correctly"
    else
        fail "Non-existent script should be rejected"
    fi
    
    # Test missing script argument
    output=$(HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-set-pre-script 2>&1 || true)
    
    if echo "$output" | grep -q "Error: Must specify script path"; then
        pass "Missing script argument rejected"
    else
        fail "Missing script argument should be rejected"
    fi
}

# Test force interactive functionality
test_force_interactive() {
    local test_home="$1"

    info "Testing --fpwrapper-force-interactive option"

    # Test that force interactive works in non-interactive mode
    local output
    output=$(echo "" | HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" --fpwrapper-force-interactive --fpwrapper-info 2>&1)
    
    if echo "$output" | grep -q "Wrapper for testapp"; then
        pass "Force interactive works in non-interactive mode"
    else
        fail "Force interactive not working in non-interactive mode"
    fi
}

# Test non-interactive bypass
test_non_interactive_bypass() {
    local test_home="$1"

    info "Testing non-interactive bypass functionality"

    # Create a system command in PATH
    mkdir -p "$test_home/system-bin"
    echo "#!/bin/bash" > "$test_home/system-bin/testapp"
    echo "echo 'System testapp called'" >> "$test_home/system-bin/testapp"
    chmod +x "$test_home/system-bin/testapp"

    # Add system bin to PATH before wrapper bin
    export PATH="$test_home/system-bin:$test_home/bin:$PATH"

    # Test non-interactive execution (should bypass wrapper)
    local output
    output=$(echo "" | HOME="$test_home" XDG_CONFIG_HOME="$test_home/.config" XDG_DATA_HOME="$test_home/.local" PATH="$test_home/bin:$PATH" "$test_home/bin/testapp" 2>&1)
    
    if echo "$output" | grep -q "System testapp called"; then
        pass "Non-interactive bypass works"
    else
        fail "Non-interactive bypass not working"
    fi
}

# Main test execution
main() {
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}Wrapper Options Test Suite${NC}"
    echo -e "${BLUE}======================================${NC}"
    echo ""
    
    # Ensure developer safety
    ensure_developer_safety
    
    # Setup test environment
    local test_home
    test_home=$(setup_test_env)
    
    # Create test wrapper
    create_test_wrapper "$test_home"
    
    # Run tests
    test_wrapper_help "$test_home"
    test_wrapper_info "$test_home"
    test_config_dir "$test_home"
    test_sandbox_info "$test_home"
    test_sandbox_edit "$test_home"
    test_sandbox_yolo "$test_home"
    test_sandbox_reset "$test_home"
    test_unrestricted_run "$test_home"
    test_set_override "$test_home"
    test_script_management "$test_home"
    test_force_interactive "$test_home"
    test_non_interactive_bypass "$test_home"
    
    # Cleanup
    cleanup_test_env "$test_home"
    
    # Results
    echo ""
    echo -e "${BLUE}======================================${NC}"
    echo -e "${BLUE}Test Results${NC}"
    echo -e "${BLUE}======================================${NC}"
    echo -e "${GREEN}Passed: $PASSED${NC}"
    echo -e "${RED}Failed: $FAILED${NC}"
    
    if [ $FAILED -eq 0 ]; then
        echo -e "${GREEN}All tests passed!${NC}"
        exit 0
    else
        echo -e "${RED}Some tests failed!${NC}"
        exit 1
    fi
}

# Run main function
main "$@"