#!/usr/bin/env bash
# Test suite for lib/common.sh utility functions
# Tests critical security and helper functions

TEST_DIR="/tmp/fplaunch-common-test-$$"
TEST_BIN="$TEST_DIR/bin"
TEST_CONFIG="$TEST_DIR/config/flatpak-wrappers"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Source the common library
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0

cleanup() {
    rm -rf "$TEST_DIR"
}
trap cleanup EXIT

pass() {
    echo -e "${GREEN}✓${NC} $1"
    ((TESTS_PASSED++))
}

fail() {
    echo -e "${RED}✗${NC} $1"
    ((TESTS_FAILED++))
}

# Test 1: validate_home_dir accepts valid paths
test_validate_home_dir_valid() {
    echo "Test 1: validate_home_dir accepts valid home paths"
    
    # Test home directory itself
    if validate_home_dir "$HOME" "test" 2>/dev/null; then
        pass "Accepts HOME directory itself"
    else
        fail "Should accept HOME directory itself"
    fi
    
    # Test subdirectory of home
    if validate_home_dir "$HOME/.local/bin" "test" 2>/dev/null; then
        pass "Accepts subdirectory of HOME"
    else
        fail "Should accept subdirectory of HOME"
    fi
    
    # Test deep subdirectory
    if validate_home_dir "$HOME/some/deep/path" "test" 2>/dev/null; then
        pass "Accepts deep subdirectory of HOME"
    else
        fail "Should accept deep subdirectory of HOME"
    fi
}

# Test 2: validate_home_dir rejects system paths
test_validate_home_dir_invalid() {
    echo "Test 2: validate_home_dir rejects system paths"
    
    # Test /usr/bin
    if ! validate_home_dir "/usr/bin" "test" 2>/dev/null; then
        pass "Rejects /usr/bin"
    else
        fail "Should reject /usr/bin"
    fi
    
    # Test /opt
    if ! validate_home_dir "/opt/bin" "test" 2>/dev/null; then
        pass "Rejects /opt/bin"
    else
        fail "Should reject /opt/bin"
    fi
    
    # Test /usr/local/bin
    if ! validate_home_dir "/usr/local/bin" "test" 2>/dev/null; then
        pass "Rejects /usr/local/bin"
    else
        fail "Should reject /usr/local/bin"
    fi
    
    # Test /bin
    if ! validate_home_dir "/bin" "test" 2>/dev/null; then
        pass "Rejects /bin"
    else
        fail "Should reject /bin"
    fi
    
    # Test /tmp (not in HOME)
    if ! validate_home_dir "/tmp/test" "test" 2>/dev/null; then
        pass "Rejects /tmp paths"
    else
        fail "Should reject /tmp paths"
    fi
}

# Test 3: is_wrapper_file detects generated wrappers
test_is_wrapper_file() {
    echo "Test 3: is_wrapper_file detects wrapper files"
    
    mkdir -p "$TEST_BIN"
    
    # Create a valid wrapper file
    cat > "$TEST_BIN/test-wrapper" << 'EOF'
#!/usr/bin/env bash
# Generated by fplaunchwrapper

NAME="test-wrapper"
ID="com.example.Test"
EOF
    
    if is_wrapper_file "$TEST_BIN/test-wrapper"; then
        pass "Detects valid wrapper file"
    else
        fail "Should detect valid wrapper file"
    fi
    
    # Create a non-wrapper file
    cat > "$TEST_BIN/not-wrapper" << 'EOF'
#!/usr/bin/env bash
# Just a regular script
echo "Hello"
EOF
    
    if ! is_wrapper_file "$TEST_BIN/not-wrapper"; then
        pass "Rejects non-wrapper file"
    else
        fail "Should reject non-wrapper file"
    fi
    
    # Test non-existent file
    if ! is_wrapper_file "$TEST_BIN/nonexistent"; then
        pass "Rejects non-existent file"
    else
        fail "Should reject non-existent file"
    fi
}

# Test 4: get_wrapper_id extracts correct ID
test_get_wrapper_id() {
    echo "Test 4: get_wrapper_id extracts Flatpak ID"
    
    mkdir -p "$TEST_BIN"
    
    # Create wrapper with ID
    cat > "$TEST_BIN/test-app" << 'EOF'
#!/usr/bin/env bash
# Generated by fplaunchwrapper

NAME="test-app"
ID="org.example.TestApp"
PREF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
EOF
    
    local extracted_id
    extracted_id=$(get_wrapper_id "$TEST_BIN/test-app")
    
    if [ "$extracted_id" = "org.example.TestApp" ]; then
        pass "Extracted correct ID: $extracted_id"
    else
        fail "Expected 'org.example.TestApp', got '$extracted_id'"
    fi
    
    # Test wrapper with different ID format
    cat > "$TEST_BIN/another-app" << 'EOF'
#!/usr/bin/env bash
# Generated by fplaunchwrapper
NAME="another-app"
ID="com.github.Developer.App"
EOF
    
    extracted_id=$(get_wrapper_id "$TEST_BIN/another-app")
    
    if [ "$extracted_id" = "com.github.Developer.App" ]; then
        pass "Extracted ID with dots: $extracted_id"
    else
        fail "Expected 'com.github.Developer.App', got '$extracted_id'"
    fi
}

# Test 5: init_paths sets up correct paths
test_init_paths() {
    echo "Test 5: init_paths initializes paths correctly"
    
    mkdir -p "$TEST_CONFIG"
    echo "$TEST_BIN" > "$TEST_CONFIG/bin_dir"
    
    # Set environment to use test config
    XDG_CONFIG_HOME="$TEST_DIR/config"
    
    # Call init_paths
    init_paths
    
    if [ "$CONFIG_DIR" = "$TEST_CONFIG" ]; then
        pass "CONFIG_DIR set correctly: $CONFIG_DIR"
    else
        fail "Expected CONFIG_DIR=$TEST_CONFIG, got $CONFIG_DIR"
    fi
    
    if [ "$BIN_DIR" = "$TEST_BIN" ]; then
        pass "BIN_DIR loaded from config: $BIN_DIR"
    else
        fail "Expected BIN_DIR=$TEST_BIN, got $BIN_DIR"
    fi
}

# Test 6: ensure_config_dir creates directory
test_ensure_config_dir() {
    echo "Test 6: ensure_config_dir creates config directory"
    
    local test_config="$TEST_DIR/new-config/flatpak-wrappers"
    CONFIG_DIR="$test_config"
    
    ensure_config_dir
    
    if [ -d "$test_config" ]; then
        pass "Config directory created: $test_config"
    else
        fail "Config directory not created"
    fi
}

# Test 7: get_systemd_unit_dir returns correct path
test_get_systemd_unit_dir() {
    echo "Test 7: get_systemd_unit_dir returns correct path"
    
    local unit_dir
    unit_dir=$(get_systemd_unit_dir)
    
    local expected="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
    
    if [ "$unit_dir" = "$expected" ]; then
        pass "Systemd unit dir correct: $unit_dir"
    else
        fail "Expected $expected, got $unit_dir"
    fi
}

# Test 8: cleanup_systemd_units removes units  
test_cleanup_systemd_units() {
    echo "Test 8: cleanup_systemd_units removes unit files"
    
    # Test the file removal part in isolation since systemctl won't work in container
    local unit_dir="$TEST_DIR/systemd/user"
    mkdir -p "$unit_dir"
    
    # Create test unit files
    touch "$unit_dir/test-units.service"
    touch "$unit_dir/test-units.path"
    touch "$unit_dir/test-units.timer"
    
    # Mock systemctl globally for this subshell
    systemctl() { return 0; }
    export -f systemctl
    
    # Temporarily override XDG_CONFIG_HOME to use test directory
    XDG_CONFIG_HOME="$TEST_DIR" cleanup_systemd_units "test-units" 2>/dev/null
    
    if [ ! -f "$unit_dir/test-units.service" ]; then
        pass "Service unit removed"
    else
        fail "Service unit not removed"
    fi
    
    if [ ! -f "$unit_dir/test-units.path" ]; then
        pass "Path unit removed"
    else
        fail "Path unit not removed"
    fi
    
    if [ ! -f "$unit_dir/test-units.timer" ]; then
        pass "Timer unit removed"
    else
        fail "Timer unit not removed"
    fi
}

# Test 9: get_wrapper_name returns basename
test_get_wrapper_name() {
    echo "Test 9: get_wrapper_name returns correct name"
    
    local name
    name=$(get_wrapper_name "/path/to/wrapper/firefox")
    
    if [ "$name" = "firefox" ]; then
        pass "Extracted wrapper name: $name"
    else
        fail "Expected 'firefox', got '$name'"
    fi
}

# Run all tests
echo "Common Library Test Suite"
echo "========================="
echo

test_validate_home_dir_valid
echo
test_validate_home_dir_invalid
echo
test_is_wrapper_file
echo
test_get_wrapper_id
echo
test_init_paths
echo
test_ensure_config_dir
echo
test_get_systemd_unit_dir
echo
test_cleanup_systemd_units
echo
test_get_wrapper_name
echo

# Summary
echo "======================================"
echo "Test Results"
echo "======================================"
echo "Passed: $TESTS_PASSED"
echo "Failed: $TESTS_FAILED"
echo "Total:  $((TESTS_PASSED + TESTS_FAILED))"
echo "======================================"

if [ $TESTS_FAILED -eq 0 ]; then
    echo -e "${GREEN}✓${NC} Common library tests passed"
    exit 0
else
    echo -e "${RED}✗${NC} Some common library tests failed"
    exit 1
fi
