#!/usr/bin/env bash
set -euo pipefail

# Edge Case Test Suite for fplaunchwrapper
# Covers: Unicode/space names, long names, alias cycles, symlink loops, systemd setup smoke

# Developer workstation safety check - never run as root
if [ "$(id -u)" = "0" ] && [ -z "${CI:-}" ] && [ "${TESTING:-}" != "1" ]; then
    echo "ERROR: Refusing to run tests as root for safety"
    echo "This project should never be run with root privileges"
    exit 1
fi

# Set testing environment
export TESTING=1
export CI=1

PROJECT_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
LIB_DIR="$PROJECT_ROOT/lib"
BIN_DIR_BASE="/tmp/fplaunch-edge-$$/bin"
CONFIG_DIR_BASE="/tmp/fplaunch-edge-$$/config/flatpak-wrappers"
mkdir -p "$BIN_DIR_BASE" "$CONFIG_DIR_BASE"

# Source libs (functions expect BIN_DIR/CONFIG_DIR globals)
# shellcheck source=../lib/common.sh disable=SC1091
source "$LIB_DIR/common.sh"
# shellcheck source=../lib/wrapper.sh disable=SC1091
source "$LIB_DIR/wrapper.sh"
# shellcheck source=../lib/alias.sh disable=SC1091
source "$LIB_DIR/alias.sh"
# shellcheck source=../lib/pref.sh disable=SC1091
source "$LIB_DIR/pref.sh"
# shellcheck source=../lib/env.sh disable=SC1091
source "$LIB_DIR/env.sh"

pass_count=0
fail_count=0

echo "======================================"
echo "Edge Case Test Suite"
echo "======================================"

report_pass() {
  echo "✓ $1"
  pass_count=$((pass_count+1))
}
report_fail() {
  echo "✗ $1"
  fail_count=$((fail_count+1))
}

# Helper: reset test env
reset_env() {
  rm -rf "$BIN_DIR_BASE" "$CONFIG_DIR_BASE"
  mkdir -p "$BIN_DIR_BASE" "$CONFIG_DIR_BASE"
  export BIN_DIR="$BIN_DIR_BASE"
  export CONFIG_DIR="$CONFIG_DIR_BASE"
}

# Helper: create a simple wrapper for a given Flatpak ID
create_wrapper_for_id() {
  local id="$1"
  local name
  name=$(echo "$id" | awk -F. '{print tolower($NF)}')
  # Enforce naming spec: non-empty, allowed chars only, no spaces, no leading/trailing hyphens
  if [ -z "$name" ] || [[ "$name" =~ [^a-z0-9_\-] ]] || [[ "$name" == *" "* ]] || [[ "$name" == -* ]] || [[ "$name" == *- ]]; then
    return 1
  fi
  cat > "$BIN_DIR/$name" << 'EOF'
#!/usr/bin/env bash
# Generated by fplaunchwrapper
NAME="$name"
ID="$id"
echo "Running $ID"
EOF
  chmod +x "$BIN_DIR/$name"
}

# Test 1: Unicode and space-containing wrapper names
reset_env
UNICODE_ID="org.example.测试浏览器"
SPACE_ID="org.example.My App"

create_wrapper_for_id "$UNICODE_ID" || true
# Expect Unicode last-segment names to be rejected by naming spec
if [[ ! -f "$BIN_DIR_BASE/测试浏览器" ]]; then
  report_pass "Unicode app ID correctly treated as invalid"
else
  report_fail "Unicode app name should not be generated"
fi

create_wrapper_for_id "$SPACE_ID" || true
# Expect invalid name to be skipped (contains space)
if [[ ! -f "$BIN_DIR_BASE/app" && ! -f "$BIN_DIR_BASE/my app" ]]; then
  report_pass "Space-containing app ID correctly treated as invalid"
else
  report_fail "Space-containing app name incorrectly generated"
fi

# Test 2: Extremely long application name handling
reset_env
LONG_SEG="verylongsegment"
LONG_ID="org.example.${LONG_SEG}${LONG_SEG}${LONG_SEG}${LONG_SEG}${LONG_SEG}${LONG_SEG}${LONG_SEG}${LONG_SEG}"
# Ensure name truncation or safe handling
if create_wrapper_for_id "$LONG_ID"; then
  if [[ $(find "$BIN_DIR_BASE" -type f | wc -l) -ge 1 ]]; then
    report_pass "Long app name handled safely"
  else
    report_fail "Long app name generated no file"
  fi
else
  report_fail "Long app name generation failed"
fi

# Test 3: Alias cycle detection and prevention
reset_env
# Create two wrappers
create_wrapper_for_id "org.example.alpha"
create_wrapper_for_id "org.example.beta"
# Create alias cycle alpha -> beta -> alpha
set_alias "alpha" "beta" || true
set_alias "beta" "alpha" || true
# Resolve alias, expecting detection or safe resolution without infinite loop
if OUTPUT=$(readlink -f "$BIN_DIR_BASE/alpha" 2>/dev/null); then
  # Collapse to basename
  OUTPUT=$(basename "$OUTPUT")
  if [[ "$OUTPUT" == "beta" || "$OUTPUT" == "alpha" ]]; then
    report_pass "Alias cycle did not cause infinite loop"
  else
    report_fail "Alias resolution returned unexpected value: $OUTPUT"
  fi
else
  report_pass "Alias cycle correctly prevented"
fi

# Test 4: Symlink loop detection for BIN_DIR
reset_env
ln -s "$BIN_DIR_BASE" "$BIN_DIR_BASE/loop"
# Attempt wrapper generation with path that includes symlink loop
if create_wrapper_for_id "org.example.loop" 2>/dev/null; then
  # Depending on implementation, generation may still succeed if loop not traversed
  report_pass "Symlink loop did not crash generation"
else
  report_pass "Symlink loop detected and prevented"
fi

# Test 5: Systemd setup smoke test (non-destructive)
reset_env
# Just ensure script is invocable and doesn't create units without explicit flags
# Non-destructive check: script exists and is executable
if [[ -x "$PROJECT_ROOT/fplaunch-setup-systemd" ]]; then
  report_pass "Systemd setup script is present and executable"
else
  report_fail "Systemd setup script missing or not executable"
fi

# Summary
TOTAL=$((pass_count+fail_count))
printf "\n======================================\n"
echo "Edge Case Test Results"
echo "======================================"
echo "Passed: $pass_count"
echo "Failed: $fail_count"
echo "Total:  $TOTAL"
echo "======================================"

# Exit non-zero if any failures
[[ $fail_count -eq 0 ]]
