#!/usr/bin/env python3
"""Test stdout/stderr output for fplaunch manage subcommands.

This test suite ensures that:
1. User-facing output (info, success, tables) appears on stdout
2. Error and warning messages appear on stderr
3. Emit-mode messages appear on stdout
4. Plain-text fallback works when Rich is unavailable
5. No silent failures when output libraries are unavailable
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

try:
    from fplaunch.manage import WrapperManager
    MANAGE_AVAILABLE = True
except ImportError:
    MANAGE_AVAILABLE = False


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestManageOutputStreams:
    """Test that manage commands output to correct streams (stdout vs stderr)."""

    def setup_method(self) -> None:
        """Set up temporary test environment."""
        self.temp_dir = Path(tempfile.mkdtemp(prefix="fpwrapper_output_test_"))
        self.bin_dir = self.temp_dir / "bin"
        self.config_dir = self.temp_dir / "config"
        
        self.bin_dir.mkdir(parents=True)
        self.config_dir.mkdir(parents=True)
        
        self._create_test_wrapper("firefox", "org.mozilla.firefox")
        self._create_test_wrapper("chrome", "com.google.Chrome")

    def teardown_method(self) -> None:
        """Clean up test environment."""
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def _create_test_wrapper(self, name: str, app_id: str) -> None:
        """Create a test wrapper script."""
        wrapper_path = self.bin_dir / name
        wrapper_content = f"""#!/bin/bash
# Generated by fplaunchwrapper
ID="{app_id}"
# Test wrapper script
"""
        wrapper_path.write_text(wrapper_content)
        wrapper_path.chmod(0o755)

    # ========== Display/List Tests ==========

    def test_display_wrappers_outputs_to_stdout(self, capsys) -> None:
        """Test that display_wrappers() outputs wrapper list to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        manager.display_wrappers()
        captured = capsys.readouterr()
        
        # Should output to stdout, not stderr
        assert "firefox" in captured.out or "Flatpak" in captured.out
        assert captured.err == ""

    def test_display_wrappers_shows_wrapper_count(self, capsys) -> None:
        """Test that display_wrappers() shows number of wrappers."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        manager.display_wrappers()
        captured = capsys.readouterr()
        
        # Should indicate 2 wrappers found
        assert "2" in captured.out or "wrappers" in captured.out.lower()

    def test_display_wrappers_no_wrappers_to_stdout(self, capsys) -> None:
        """Test that 'no wrappers' message goes to stdout, not stderr."""
        empty_bin = self.temp_dir / "empty_bin"
        empty_bin.mkdir()
        
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(empty_bin),
        )
        
        manager.display_wrappers()
        captured = capsys.readouterr()
        
        # "No wrappers found" message should be on stdout
        assert "No" in captured.out or "wrappers" in captured.out.lower()
        assert captured.err == ""

    # ========== Show Info Tests ==========

    def test_show_info_outputs_to_stdout(self, capsys) -> None:
        """Test that show_info() outputs wrapper details to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        result = manager.show_info("firefox")
        captured = capsys.readouterr()
        
        assert result is True
        # Output should be on stdout
        assert "firefox" in captured.out or "Wrapper" in captured.out
        assert captured.err == ""

    def test_show_info_missing_wrapper_to_stderr(self, capsys) -> None:
        """Test that error for missing wrapper goes to stderr."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        result = manager.show_info("nonexistent")
        captured = capsys.readouterr()
        
        assert result is False
        # Error should be on stderr
        assert "ERROR" in captured.err or "not found" in captured.err.lower()

    # ========== Set Preference Tests ==========

    def test_set_preference_success_to_stdout(self, capsys) -> None:
        """Test that success message for set_preference goes to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        result = manager.set_preference("firefox", "system")
        captured = capsys.readouterr()
        
        assert result is True
        # Success message should be on stdout
        assert "firefox" in captured.out or "preference" in captured.out.lower()
        assert captured.err == ""

    def test_set_preference_error_to_stderr(self, capsys) -> None:
        """Test that error messages for set_preference go to stderr."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        # Invalid preference (contains space which is not allowed)
        result = manager.set_preference("firefox", "invalid pref")
        captured = capsys.readouterr()
        
        assert result is False
        # Error should be on stderr
        assert "ERROR" in captured.err or "Invalid" in captured.err

    def test_set_preference_creates_file(self, capsys) -> None:
        """Test that set_preference actually creates preference file."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        result = manager.set_preference("firefox", "flatpak")
        
        assert result is True
        pref_file = self.config_dir / "firefox.pref"
        assert pref_file.exists()
        assert pref_file.read_text().strip() == "flatpak"

    # ========== Discover Features Tests ==========

    def test_discover_features_outputs_to_stdout(self, capsys) -> None:
        """Test that discover_features() outputs feature list to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        manager.discover_features()
        captured = capsys.readouterr()
        
        # Should output feature table to stdout
        assert "Feature" in captured.out or "Generation" in captured.out
        assert captured.err == ""

    def test_discover_features_includes_examples(self, capsys) -> None:
        """Test that discover_features() includes usage examples."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        manager.discover_features()
        captured = capsys.readouterr()
        
        # Should include examples like 'fplaunch generate'
        assert "generate" in captured.out.lower() or "fplaunch" in captured.out

    # ========== Remove Wrapper Tests ==========

    def test_remove_wrapper_success_to_stdout(self, capsys) -> None:
        """Test that success message for remove_wrapper goes to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            verbose=True,  # Enable output
        )
        
        result = manager.remove_wrapper("firefox", force=True)
        captured = capsys.readouterr()
        
        assert result is True
        # Success message should be on stdout
        assert "Removed" in captured.out or "firefox" in captured.out
        assert captured.err == ""

    def test_remove_wrapper_missing_to_stderr(self, capsys) -> None:
        """Test that error for missing wrapper goes to stderr."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        result = manager.remove_wrapper("nonexistent", force=True)
        captured = capsys.readouterr()
        
        assert result is False
        # Error should be on stderr
        assert "ERROR" in captured.err or "not found" in captured.err.lower()

    def test_remove_wrapper_actually_deletes(self, capsys) -> None:
        """Test that remove_wrapper actually removes the wrapper file."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        wrapper_path = self.bin_dir / "firefox"
        assert wrapper_path.exists()
        
        result = manager.remove_wrapper("firefox", force=True)
        
        assert result is True
        assert not wrapper_path.exists()

    # ========== Emit Mode Tests ==========

    def test_emit_mode_set_preference_to_stdout(self, capsys) -> None:
        """Test that emit mode set_preference outputs to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            emit_mode=True,
            verbose=True,
        )
        
        result = manager.set_preference("firefox", "flatpak")
        captured = capsys.readouterr()
        
        assert result is True
        # EMIT message should be on stdout
        assert "EMIT" in captured.out or "firefox" in captured.out
        # Should not create actual file in emit mode
        pref_file = self.config_dir / "firefox.pref"
        assert not pref_file.exists()

    def test_emit_mode_remove_wrapper_to_stdout(self, capsys) -> None:
        """Test that emit mode remove_wrapper outputs to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            emit_mode=True,
            verbose=True,
        )
        
        result = manager.remove_wrapper("firefox")
        captured = capsys.readouterr()
        
        assert result is True
        # EMIT message should be on stdout
        assert "EMIT" in captured.out or "firefox" in captured.out
        # Should not actually delete file in emit mode
        wrapper_path = self.bin_dir / "firefox"
        assert wrapper_path.exists()

    def test_emit_verbose_shows_file_content(self, capsys) -> None:
        """Test that emit_verbose mode shows file content."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            emit_mode=True,
            emit_verbose=True,
            verbose=True,
        )
        
        result = manager.set_preference("firefox", "system")
        captured = capsys.readouterr()
        
        assert result is True
        # Should show the preference value in verbose emit mode
        assert "system" in captured.out or "EMIT" in captured.out

    # ========== Log Level Tests ==========

    def test_log_error_always_prints(self, capsys) -> None:
        """Test that error level messages always print (even non-verbose)."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            verbose=False,  # Not verbose
        )
        
        manager.log("Test error message", level="error")
        captured = capsys.readouterr()
        
        # Error should print even without verbose
        assert "error" in captured.err.lower() or "Test error" in captured.err

    def test_log_warning_always_prints(self, capsys) -> None:
        """Test that warning level messages always print (even non-verbose)."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            verbose=False,  # Not verbose
        )
        
        manager.log("Test warning message", level="warning")
        captured = capsys.readouterr()
        
        # Warning should print even without verbose
        assert "warn" in captured.err.lower() or "Test warning" in captured.err

    def test_log_success_prints_always(self, capsys) -> None:
        """Test that success level messages always print."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            verbose=False,  # Not verbose
        )
        
        manager.log("Test success message", level="success")
        captured = capsys.readouterr()
        
        # Success should print even without verbose
        assert "success" in captured.out.lower() or "Test success" in captured.out

    def test_log_info_prints_always(self, capsys) -> None:
        """Test that info level messages print (should not require verbose)."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            verbose=False,  # Not verbose
        )
        
        manager.log("Test info message", level="info")
        captured = capsys.readouterr()
        
        # Info should print to stdout
        assert "Test info" in captured.out or "info" in captured.out.lower()

    # ========== Rich Unavailable Tests ==========

    @patch("fplaunch.manage.RICH_AVAILABLE", False)
    def test_display_wrappers_fallback_no_rich(self, capsys) -> None:
        """Test that display_wrappers works without Rich library."""
        # Create a new manager with mocked Rich unavailable
        with patch("fplaunch.manage.console", None):
            manager = WrapperManager(
                config_dir=str(self.config_dir),
                bin_dir=str(self.bin_dir),
            )
            
            manager.display_wrappers()
            captured = capsys.readouterr()
            
            # Should still output something to stdout (plain text fallback)
            assert "firefox" in captured.out or "chrome" in captured.out or "Wrapper" in captured.out
            assert captured.err == ""

    @patch("fplaunch.manage.RICH_AVAILABLE", False)
    def test_show_info_fallback_no_rich(self, capsys) -> None:
        """Test that show_info works without Rich library."""
        with patch("fplaunch.manage.console", None):
            manager = WrapperManager(
                config_dir=str(self.config_dir),
                bin_dir=str(self.bin_dir),
            )
            
            result = manager.show_info("firefox")
            captured = capsys.readouterr()
            
            assert result is True
            # Should still output something to stdout (plain text fallback)
            assert "firefox" in captured.out or "Wrapper" in captured.out
            assert captured.err == ""

    @patch("fplaunch.manage.RICH_AVAILABLE", False)
    def test_discover_features_fallback_no_rich(self, capsys) -> None:
        """Test that discover_features works without Rich library."""
        with patch("fplaunch.manage.console", None):
            manager = WrapperManager(
                config_dir=str(self.config_dir),
                bin_dir=str(self.bin_dir),
            )
            
            manager.discover_features()
            captured = capsys.readouterr()
            
            # Should still output something to stdout (plain text fallback)
            assert "Feature" in captured.out or "generate" in captured.out.lower()
            assert captured.err == ""

    @patch("fplaunch.manage.RICH_AVAILABLE", False)
    def test_log_fallback_no_rich(self, capsys) -> None:
        """Test that log works without Rich library."""
        with patch("fplaunch.manage.console", None):
            manager = WrapperManager(
                config_dir=str(self.config_dir),
                bin_dir=str(self.bin_dir),
            )
            
            manager.log("Test message", level="info")
            captured = capsys.readouterr()
            
            # Should still output to stdout
            assert "Test message" in captured.out
            
            manager.log("Test error", level="error")
            captured = capsys.readouterr()
            
            # Error should go to stderr
            assert "Test error" in captured.err

    # ========== Integration Tests ==========

    def test_set_preference_all_outputs_summary(self, capsys) -> None:
        """Test that set_preference_all outputs summary to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            verbose=True,
        )
        
        count = manager.set_preference_all("flatpak")
        captured = capsys.readouterr()
        
        assert count == 2
        # Should output summary to stdout
        assert "Set preference" in captured.out or "flatpak" in captured.out

    def test_block_app_success_to_stdout(self, capsys) -> None:
        """Test that block_app success message goes to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        result = manager.block_app("org.mozilla.firefox")
        captured = capsys.readouterr()
        
        assert result is True
        # Success message should be on stdout
        assert "Blocked" in captured.out or "firefox" in captured.out

    def test_unblock_app_success_to_stdout(self, capsys) -> None:
        """Test that unblock_app success message goes to stdout."""
        manager = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )
        
        # First block the app
        manager.block_app("org.mozilla.firefox")
        capsys.readouterr()  # Clear previous output
        
        # Then unblock it
        result = manager.unblock_app("org.mozilla.firefox")
        captured = capsys.readouterr()
        
        assert result is True
        # Success message should be on stdout
        assert "Unblocked" in captured.out or "firefox" in captured.out


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
