#!/usr/bin/env python3
"""Additional pytest tests for lib.manage to boost coverage."""

import shutil
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

try:
    from lib.manage import WrapperManager, main

    MANAGE_AVAILABLE = True
except ImportError:
    MANAGE_AVAILABLE = False


@pytest.fixture
def temp_env():
    """Create isolated bin_dir + config_dir for testing."""
    temp_dir = Path(tempfile.mkdtemp(prefix="fpwrapper_mgmt_cov_"))
    bin_dir = temp_dir / "bin"
    config_dir = temp_dir / "config"
    bin_dir.mkdir()
    config_dir.mkdir()
    yield {"temp_dir": temp_dir, "bin_dir": bin_dir, "config_dir": config_dir}
    shutil.rmtree(temp_dir, ignore_errors=True)


def _make_wrapper(bin_dir: Path, name: str, flatpak_id: str = None) -> Path:
    """Create a valid wrapper file in bin_dir."""
    wrapper = bin_dir / name
    flatpak_id = flatpak_id or f"org.test.{name}"
    wrapper.write_text(
        f"#!/usr/bin/env bash\n"
        f"# Generated by fplaunchwrapper\n"
        f'NAME="{name}"\n'
        f'ID="{flatpak_id}"\n'
        f"echo {name}\n"
    )
    wrapper.chmod(0o755)
    return wrapper


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerEmitMode:
    """Test emit mode paths."""

    def test_init_with_bin_dir_only_in_emit_mode(self, temp_env):
        """Test init with bin_dir but no config_dir in emit mode."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            emit_mode=True,
        )
        assert manager.bin_dir == temp_env["bin_dir"]
        assert manager.config_dir is None

    def test_init_emit_mode_no_dirs(self):
        """Test init with no dirs in emit mode creates temp dirs."""
        manager = WrapperManager(emit_mode=True)
        assert manager.config_dir is not None
        assert manager.bin_dir is not None
        assert "fpmgmt_" in str(manager.config_dir)
        assert "fpbin_" in str(manager.bin_dir)

    def test_init_no_emit_no_dirs_creates_temp(self):
        """Test init with no dirs and emit=False creates temp dirs."""
        manager = WrapperManager()
        assert manager.config_dir is not None
        assert manager.bin_dir is not None

    def test_remove_wrapper_in_emit_mode(self, temp_env):
        """Test remove_wrapper in emit mode doesn't actually remove."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
            emit_mode=True,
        )
        result = manager.remove_wrapper("firefox", force=True)
        assert result is True
        # File should still exist
        assert (temp_env["bin_dir"] / "firefox").exists()

    def test_set_preference_in_emit_mode(self, temp_env):
        """Test set_preference in emit mode."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
            emit_mode=True,
        )
        result = manager.set_preference("firefox", "flatpak")
        assert result is True
        # No file should be created
        assert not (temp_env["config_dir"] / "firefox.pref").exists()


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerShowInfo:
    """Test show_info method."""

    def test_show_info_success(self, temp_env):
        """Test show_info for a valid wrapper."""
        _make_wrapper(temp_env["bin_dir"], "firefox", "org.mozilla.firefox")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.show_info("firefox") is True

    def test_show_info_nonexistent(self, temp_env):
        """Test show_info for nonexistent wrapper returns False."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.show_info("nonexistent") is False

    def test_show_info_no_bin_dir(self):
        """Test show_info when bin_dir is None returns False."""
        manager = WrapperManager(emit_mode=True)
        # Override bin_dir to None
        manager.bin_dir = None
        assert manager.show_info("firefox") is False

    def test_show_info_non_wrapper_file(self, temp_env):
        """Test show_info for a non-wrapper file returns False."""
        (temp_env["bin_dir"] / "regular").write_text("#!/bin/bash\necho hi\n")
        (temp_env["bin_dir"] / "regular").chmod(0o755)
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.show_info("regular") is False

    def test_show_info_with_preference(self, temp_env):
        """Test show_info includes preference when set."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        (temp_env["config_dir"] / "firefox.pref").write_text("flatpak")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.show_info("firefox") is True

    def test_show_info_without_preference(self, temp_env):
        """Test show_info works without preference file."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.show_info("firefox") is True


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerListWrappers:
    """Test list_wrappers edge cases."""

    def test_list_wrappers_with_legacy_marker(self, temp_env):
        """Test list_wrappers picks up legacy Generated by markers."""
        legacy = temp_env["bin_dir"] / "old"
        legacy.write_text("#!/bin/bash\n# Generated by fplaunchwrapper\necho old\n")
        legacy.chmod(0o755)
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        wrappers = manager.list_wrappers()
        names = [w["name"] for w in wrappers]
        assert "old" in names

    def test_list_wrappers_no_bin_dir(self):
        """Test list_wrappers returns empty when bin_dir is None."""
        manager = WrapperManager(emit_mode=True)
        manager.bin_dir = None
        assert manager.list_wrappers() == []

    def test_list_wrappers_nonexistent_dir(self, temp_env):
        """Test list_wrappers returns empty for nonexistent bin_dir."""
        manager = WrapperManager(
            bin_dir=str(temp_env["temp_dir"] / "nonexistent"),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.list_wrappers() == []


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerSetPreferenceAll:
    """Test set_preference_all method."""

    def test_set_preference_all_updates_all(self, temp_env):
        """Test set_preference_all updates every wrapper."""
        for name in ["firefox", "chrome", "vlc"]:
            _make_wrapper(temp_env["bin_dir"], name)
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        count = manager.set_preference_all("flatpak")
        assert count == 3
        for name in ["firefox", "chrome", "vlc"]:
            pref = (temp_env["config_dir"] / f"{name}.pref").read_text().strip()
            assert pref == "flatpak"

    def test_set_preference_all_invalid(self, temp_env):
        """Test set_preference_all with invalid preference returns 0."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.set_preference_all("bogus") == 0


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerCreateAlias:
    """Test create_alias edge cases."""

    def test_create_alias_empty_alias_name(self, temp_env):
        """Test create_alias rejects empty alias name."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.create_alias("", "firefox") is False
        assert manager.create_alias("  ", "firefox") is False

    def test_create_alias_empty_target(self, temp_env):
        """Test create_alias rejects empty target."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.create_alias("browser", "") is False

    def test_create_alias_invalid_chars(self, temp_env):
        """Test create_alias rejects names with invalid characters."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.create_alias("bad name", "firefox") is False
        assert manager.create_alias("bad/name", "firefox") is False

    def test_create_alias_collision_with_wrapper(self, temp_env):
        """Test create_alias warns when colliding with existing wrapper."""
        _make_wrapper(temp_env["bin_dir"], "browser")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        result = manager.create_alias("browser", "firefox")
        # Should still succeed (alias created) but warn
        assert result is True

    def test_create_alias_with_validation_missing_target(self, temp_env):
        """Test create_alias with validate_target=True checks target exists."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        result = manager.create_alias("browser", "nonexistent", validate_target=True)
        assert result is False

    def test_create_alias_with_validation_valid_target(self, temp_env):
        """Test create_alias with validate_target=True succeeds for valid target."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        result = manager.create_alias("browser", "firefox", validate_target=True)
        assert result is True

    def test_create_alias_duplicate(self, temp_env):
        """Test create_alias returns False for duplicate alias."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.create_alias("browser", "firefox") is True
        assert manager.create_alias("browser", "chrome") is False


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerListManagedFiles:
    """Test list_managed_files method."""

    def test_list_managed_files_no_wrappers(self, temp_env):
        """Test list_managed_files returns empty when no wrappers."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        assert manager.list_managed_files() == {}

    def test_list_managed_files_with_app_filter(self, temp_env):
        """Test list_managed_files filters by app_name."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        _make_wrapper(temp_env["bin_dir"], "chrome")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        result = manager.list_managed_files(app_name="firefox")
        assert "firefox" in result
        assert "chrome" not in result

    def test_list_managed_files_with_prefs(self, temp_env):
        """Test list_managed_files includes pref files."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        (temp_env["config_dir"] / "firefox.pref").write_text("flatpak")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        result = manager.list_managed_files(file_type="prefs")
        assert "firefox" in result
        assert any(f["type"] == "pref" for f in result["firefox"])

    def test_list_managed_files_with_env(self, temp_env):
        """Test list_managed_files includes env files."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        (temp_env["config_dir"] / "firefox.env").write_text("FOO=bar")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        result = manager.list_managed_files(file_type="env")
        assert "firefox" in result
        assert any(f["type"] == "env" for f in result["firefox"])

    def test_list_managed_files_no_bin_dir(self, temp_env):
        """Test list_managed_files returns empty when bin_dir is None."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        manager.bin_dir = None
        assert manager.list_managed_files() == {}

    def test_list_managed_files_with_aliases(self, temp_env):
        """Test list_managed_files includes aliases file when present."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        (temp_env["config_dir"] / "aliases").write_text("browser:firefox\n")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        result = manager.list_managed_files()
        assert "_aliases" in result


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerDisplay:
    """Test display_wrappers and discover_features."""

    def test_display_wrappers_no_wrappers(self, temp_env):
        """Test display_wrappers with no wrappers shows message."""
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        manager.display_wrappers()  # Should not raise

    def test_display_wrappers_with_wrappers(self, temp_env):
        """Test display_wrappers with wrappers renders table."""
        _make_wrapper(temp_env["bin_dir"], "firefox", "org.mozilla.firefox")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        manager.display_wrappers()  # Should not raise

    def test_discover_features(self, temp_env):
        """Test discover_features prints features and wrappers."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        manager = WrapperManager(
            bin_dir=str(temp_env["bin_dir"]),
            config_dir=str(temp_env["config_dir"]),
        )
        manager.discover_features()  # Should not raise


@pytest.mark.skipif(not MANAGE_AVAILABLE, reason="WrapperManager not available")
class TestWrapperManagerMain:
    """Test the main() CLI entry point."""

    def test_main_no_args_returns_0(self, capsys):
        """Test main() with no args hits the list branch and returns 0."""
        with patch("sys.argv", ["fplaunch-manage"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                result = main()
        assert result == 0
        mock_manager.display_wrappers.assert_called_once()

    def test_main_list_command(self, capsys, temp_env):
        """Test main() with 'list' command."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        with patch("sys.argv", ["fplaunch-manage", "list"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                result = main()
        assert result == 0
        mock_manager.display_wrappers.assert_called_once()

    def test_main_search_command(self, capsys, temp_env):
        """Test main() with 'search' command."""
        with patch("sys.argv", ["fplaunch-manage", "search"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                result = main()
        assert result == 0
        mock_manager.discover_features.assert_called_once()

    def test_main_discover_command(self, capsys):
        """Test main() with 'discover' command (alias)."""
        with patch("sys.argv", ["fplaunch-manage", "discover"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                result = main()
        assert result == 0
        mock_manager.discover_features.assert_called_once()

    def test_main_rm_command_success(self, capsys):
        """Test main() with 'rm' command on success."""
        with patch("sys.argv", ["fplaunch-manage", "rm", "firefox"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                mock_manager.remove_wrapper.return_value = True
                result = main()
        assert result == 0

    def test_main_rm_command_failure(self, capsys):
        """Test main() with 'rm' command on failure."""
        with patch("sys.argv", ["fplaunch-manage", "rm", "firefox"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                mock_manager.remove_wrapper.return_value = False
                result = main()
        assert result == 1

    def test_main_cleanup_command(self, capsys):
        """Test main() with 'cleanup' command."""
        with patch("sys.argv", ["fplaunch-manage", "cleanup"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                result = main()
        assert result == 0

    def test_main_set_pref_command_success(self, capsys):
        """Test main() with 'set-pref' on success."""
        with patch("sys.argv", ["fplaunch-manage", "set-pref", "firefox", "flatpak"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                mock_manager.set_preference.return_value = True
                result = main()
        assert result == 0

    def test_main_set_pref_command_failure(self, capsys):
        """Test main() with 'set-pref' on failure."""
        with patch("sys.argv", ["fplaunch-manage", "set-pref", "firefox", "flatpak"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                mock_manager.set_preference.return_value = False
                result = main()
        assert result == 1

    def test_main_unknown_command(self, capsys):
        """Test main() with unknown command returns 0."""
        # We can't easily get to the 'unknown' branch since argparse rejects unknown args,
        # but with no subcommand we hit the list branch.
        with patch("sys.argv", ["fplaunch-manage"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                result = main()
        assert result == 0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
