#!/usr/bin/env python3
"""Additional pytest tests for lib.cleanup to boost coverage."""

import shutil
import subprocess
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

try:
    from lib.cleanup import CleanupConfig, WrapperCleanup, main

    CLEANUP_AVAILABLE = True
except ImportError:
    CLEANUP_AVAILABLE = False


@pytest.fixture
def temp_env(monkeypatch):
    """Create isolated dirs for testing cleanup."""
    temp_dir = Path(tempfile.mkdtemp(prefix="fpwrapper_cleanup_"))
    home = temp_dir / "home"
    bin_dir = temp_dir / "bin"
    config_dir = temp_dir / "config"
    data_dir = temp_dir / "data"
    home.mkdir()
    bin_dir.mkdir()
    config_dir.mkdir()
    data_dir.mkdir()
    # Redirect Path.home to our test home
    monkeypatch.setattr(Path, "home", lambda: home)
    yield {
        "temp_dir": temp_dir,
        "home": home,
        "bin_dir": bin_dir,
        "config_dir": config_dir,
        "data_dir": data_dir,
    }
    shutil.rmtree(temp_dir, ignore_errors=True)


@pytest.mark.skipif(not CLEANUP_AVAILABLE, reason="WrapperCleanup not available")
class TestWrapperCleanupScanning:
    """Test scanning methods."""

    def test_scan_wrapper_directory_with_symlinks(self, temp_env):
        """Test scanning picks up symlinks pointing to valid wrappers.

        Note: this is conditional on UTILS_AVAILABLE in cleanup.py.
        """
        # Create a real wrapper target
        real = temp_env["bin_dir"] / "real_wrapper"
        real.write_text(
            '#!/bin/bash\n# Generated by fplaunchwrapper\nNAME="real"\nID="org.test.real"\n'
        )
        real.chmod(0o755)
        # Create a symlink to it
        link = temp_env["bin_dir"] / "my_link"
        link.symlink_to("real_wrapper")

        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        cleanup._scan_wrapper_directory()
        # Just verify the scan ran without error; symlink detection depends
        # on UTILS_AVAILABLE (the safety module's is_wrapper_file)
        # which may or may not be importable depending on environment.
        assert "symlinks" in cleanup.cleanup_items

    def test_scan_wrapper_directory_with_broken_symlink(self, temp_env):
        """Test scanning handles broken symlinks gracefully."""
        broken = temp_env["bin_dir"] / "broken"
        broken.symlink_to("/nonexistent/path")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        # Should not raise
        cleanup._scan_wrapper_directory()

    def test_scan_man_pages(self, temp_env):
        """Test scanning finds man pages in man1 and man7."""
        man_dir = temp_env["home"] / ".local" / "share" / "man"
        man1 = man_dir / "man1"
        man1.mkdir(parents=True)
        (man1 / "fplaunch-foo.1").write_text("foo")
        man7 = man_dir / "man7"
        man7.mkdir(parents=True)
        (man7 / "fplaunchwrapper.bar.7").write_text("bar")

        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        cleanup._scan_man_pages()
        assert any("fplaunch-foo.1" in str(p) for p in cleanup.cleanup_items["man_pages"])
        assert any("fplaunchwrapper.bar.7" in str(p) for p in cleanup.cleanup_items["man_pages"])

    def test_scan_completion_files_bash(self, temp_env):
        """Test scanning finds bash completion."""
        bash_dir = temp_env["home"] / ".bashrc.d"
        bash_dir.mkdir(parents=True)
        (bash_dir / "fplaunch_completion.bash").write_text("complete foo")

        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        cleanup._scan_completion_files()
        assert any(
            "fplaunch_completion.bash" in str(p) for p in cleanup.cleanup_items["completion_files"]
        )

    def test_scan_completion_files_zsh(self, temp_env):
        """Test scanning finds zsh completion files."""
        zsh_dir = temp_env["home"] / ".zsh" / "completions"
        zsh_dir.mkdir(parents=True)
        (zsh_dir / "_fplaunch").write_text("compdef foo")

        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        cleanup._scan_completion_files()
        assert any("_fplaunch" in str(p) for p in cleanup.cleanup_items["completion_files"])

    def test_scan_completion_files_fish(self, temp_env):
        """Test scanning finds fish completion files."""
        fish_dir = temp_env["home"] / ".config" / "fish" / "completions"
        fish_dir.mkdir(parents=True)
        (fish_dir / "fplaunch.fish").write_text("complete -c foo")

        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        cleanup._scan_completion_files()
        assert any("fplaunch.fish" in str(p) for p in cleanup.cleanup_items["completion_files"])

    def test_scan_systemd_units(self, temp_env):
        """Test scanning finds systemd units."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        systemd_dir = cleanup.systemd_unit_dir
        systemd_dir.mkdir(parents=True, exist_ok=True)
        unit = systemd_dir / "fplaunch-wrapper.service"
        unit.write_text("[Unit]\nDescription=test\n")
        cleanup._scan_systemd_units()
        assert any(
            "fplaunch-wrapper.service" in str(p) for p in cleanup.cleanup_items["systemd_units"]
        )

    def test_scan_cron_entries_with_entries(self, temp_env):
        """Test scanning finds cron entries with fplaunch references."""
        mock_result = subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="0 * * * * /usr/bin/fplaunch-generate\n# other line\n",
            stderr="",
        )
        with patch("lib.cleanup.shutil.which", return_value="/usr/bin/crontab"):
            with patch("lib.cleanup.run_crontab", return_value=mock_result):
                cleanup = WrapperCleanup(
                    config=CleanupConfig(
                        bin_dir=str(temp_env["bin_dir"]),
                        config_dir=str(temp_env["config_dir"]),
                        data_dir=str(temp_env["data_dir"]),
                    )
                )
                cleanup._scan_cron_entries()
        assert len(cleanup.cleanup_items["cron_entries"]) == 1
        assert "fplaunch-generate" in cleanup.cleanup_items["cron_entries"][0]

    def test_scan_cron_entries_no_crontab(self, temp_env):
        """Test scanning with no crontab available."""
        with patch("lib.cleanup.shutil.which", return_value=None):
            cleanup = WrapperCleanup(
                config=CleanupConfig(
                    bin_dir=str(temp_env["bin_dir"]),
                    config_dir=str(temp_env["config_dir"]),
                    data_dir=str(temp_env["data_dir"]),
                )
            )
            cleanup._scan_cron_entries()  # Should not raise
        assert cleanup.cleanup_items["cron_entries"] == []

    def test_scan_cron_entries_subprocess_error(self, temp_env):
        """Test scanning handles subprocess errors gracefully."""
        with patch("lib.cleanup.shutil.which", return_value="/usr/bin/crontab"):
            with patch("lib.cleanup.run_crontab", side_effect=OSError("crontab crashed")):
                cleanup = WrapperCleanup(
                    config=CleanupConfig(
                        bin_dir=str(temp_env["bin_dir"]),
                        config_dir=str(temp_env["config_dir"]),
                        data_dir=str(temp_env["data_dir"]),
                    )
                )
                cleanup._scan_cron_entries()  # Should not raise
        assert cleanup.cleanup_items["cron_entries"] == []

    def test_has_cron_entries_true(self, temp_env):
        """Test _has_cron_entries returns True when entries exist."""
        mock_result = subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="0 * * * * /usr/bin/fplaunch-generate\n",
            stderr="",
        )
        with patch("lib.cleanup.shutil.which", return_value="/usr/bin/crontab"):
            with patch("lib.cleanup.run_crontab", return_value=mock_result):
                cleanup = WrapperCleanup(
                    config=CleanupConfig(
                        bin_dir=str(temp_env["bin_dir"]),
                        config_dir=str(temp_env["config_dir"]),
                        data_dir=str(temp_env["data_dir"]),
                    )
                )
                assert cleanup._has_cron_entries() is True

    def test_has_cron_entries_no_crontab(self, temp_env):
        """Test _has_cron_entries returns False when crontab unavailable."""
        with patch("lib.cleanup.shutil.which", return_value=None):
            cleanup = WrapperCleanup(
                config=CleanupConfig(
                    bin_dir=str(temp_env["bin_dir"]),
                    config_dir=str(temp_env["config_dir"]),
                    data_dir=str(temp_env["data_dir"]),
                )
            )
            assert cleanup._has_cron_entries() is False

    def test_has_cron_entries_subprocess_error(self, temp_env):
        """Test _has_cron_entries returns False on subprocess error."""
        with patch("lib.cleanup.shutil.which", return_value="/usr/bin/crontab"):
            with patch("lib.cleanup.run_crontab", side_effect=OSError("crontab failed")):
                cleanup = WrapperCleanup(
                    config=CleanupConfig(
                        bin_dir=str(temp_env["bin_dir"]),
                        config_dir=str(temp_env["config_dir"]),
                        data_dir=str(temp_env["data_dir"]),
                    )
                )
                assert cleanup._has_cron_entries() is False


@pytest.mark.skipif(not CLEANUP_AVAILABLE, reason="WrapperCleanup not available")
class TestWrapperCleanupConfirm:
    """Test confirm_cleanup method."""

    def test_confirm_cleanup_no_items(self, temp_env):
        """Test confirm_cleanup with no items returns True."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        assert cleanup.confirm_cleanup() is True

    def test_confirm_cleanup_dry_run(self, temp_env):
        """Test confirm_cleanup in dry-run mode returns True."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                dry_run=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        assert cleanup.confirm_cleanup() is True

    def test_confirm_cleanup_interactive_yes(self, temp_env):
        """Test confirm_cleanup interactive mode with yes answer."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                interactive=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        with patch("lib.cleanup.Confirm.ask", return_value=True):
            assert cleanup.confirm_cleanup() is True

    def test_confirm_cleanup_interactive_no(self, temp_env):
        """Test confirm_cleanup interactive mode with no answer."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                interactive=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        with patch("lib.cleanup.Confirm.ask", return_value=False):
            assert cleanup.confirm_cleanup() is False

    def test_confirm_cleanup_non_interactive_auto_yes(self, temp_env):
        """Test confirm_cleanup non-interactive auto-yes returns True."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        assert cleanup.confirm_cleanup() is True

    def test_confirm_cleanup_with_cron_entries(self, temp_env):
        """Test confirm_cleanup counts cron entries."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        cleanup.cleanup_items["cron_entries"].append("0 * * * * /usr/bin/fplaunch-generate")
        assert cleanup.confirm_cleanup() is True

    def test_confirm_cleanup_with_config_dir(self, temp_env):
        """Test confirm_cleanup shows config dir count."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        cleanup.cleanup_items["config_dir"].append(temp_env["config_dir"])
        assert cleanup.confirm_cleanup() is True


@pytest.mark.skipif(not CLEANUP_AVAILABLE, reason="WrapperCleanup not available")
class TestWrapperCleanupPerform:
    """Test perform_cleanup method."""

    def test_perform_cleanup_dry_run(self, temp_env):
        """Test perform_cleanup in dry-run mode."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                dry_run=True,
                assume_yes=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        result = cleanup.perform_cleanup()
        assert result is True
        # File should still exist
        assert (temp_env["bin_dir"] / "firefox").exists()

    def test_perform_cleanup_with_backup(self, temp_env):
        """Test perform_cleanup with backup enabled."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                create_backup=True,
                backup_dir=str(temp_env["temp_dir"] / "backup"),
                assume_yes=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        result = cleanup.perform_cleanup()
        assert result is True
        # Backup should exist
        assert (temp_env["temp_dir"] / "backup").exists()

    def test_perform_cleanup_exception(self, temp_env):
        """Test perform_cleanup returns False on exception."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        with patch.object(cleanup, "_cleanup_systemd_units", side_effect=OSError("boom")):
            result = cleanup.perform_cleanup()
        assert result is False

    def test_perform_cleanup_removes_wrappers(self, temp_env):
        """Test perform_cleanup removes wrappers."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                remove_wrappers=True,
                assume_yes=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        result = cleanup.perform_cleanup()
        assert result is True

    def test_perform_cleanup_keeps_wrappers_when_disabled(self, temp_env):
        """Test perform_cleanup keeps wrappers when remove_wrappers=False."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                remove_wrappers=False,
                remove_systemd=False,
                remove_prefs=False,
                remove_data=False,
                assume_yes=True,
            )
        )
        cleanup.scan_for_cleanup_items()
        result = cleanup.perform_cleanup()
        assert result is True
        # The wrapper should still be in cleanup_items
        assert len(cleanup.cleanup_items["wrappers"]) >= 0


@pytest.mark.skipif(not CLEANUP_AVAILABLE, reason="WrapperCleanup not available")
class TestWrapperCleanupHelpers:
    """Test helper methods."""

    def test_remove_file(self, temp_env):
        """Test _remove_file removes a file."""
        f = temp_env["bin_dir"] / "test"
        f.write_text("x")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        cleanup._remove_file(f, "Removing test")
        assert not f.exists()

    def test_remove_file_dry_run(self, temp_env):
        """Test _remove_file in dry-run mode doesn't remove."""
        f = temp_env["bin_dir"] / "test"
        f.write_text("x")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                dry_run=True,
            )
        )
        cleanup._remove_file(f, "Removing test")
        assert f.exists()

    def test_remove_file_error(self, temp_env):
        """Test _remove_file handles errors gracefully."""
        f = temp_env["bin_dir"] / "nonexistent"
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        # Should not raise
        cleanup._remove_file(f, "Removing nonexistent")
        # Note: unlink(missing_ok=True) doesn't raise, so had_errors stays False

    def test_remove_directory(self, temp_env):
        """Test _remove_directory removes a directory."""
        d = temp_env["bin_dir"] / "subdir"
        d.mkdir()
        (d / "f").write_text("x")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        cleanup._remove_directory(d, "Removing subdir")
        assert not d.exists()

    def test_command_available(self, temp_env):
        """Test _command_available returns True for available commands."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        # sh should always be available
        assert cleanup._command_available("sh") is True
        assert cleanup._command_available("definitely-not-a-command-xyz") is False


@pytest.mark.skipif(not CLEANUP_AVAILABLE, reason="WrapperCleanup not available")
class TestWrapperCleanupLifecycle:
    """Test lifecycle methods (run, cleanup, cleanup_app, cleanup_all)."""

    def test_run_dry_run(self, temp_env):
        """Test run() with dry_run returns 0."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                dry_run=True,
                assume_yes=True,
            )
        )
        result = cleanup.run()
        assert result == 0

    def test_run_exception(self, temp_env):
        """Test run() returns 1 on exception."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        with patch.object(cleanup, "scan_for_cleanup_items", side_effect=OSError("boom")):
            assert cleanup.run() == 1

    def test_cleanup_method_dry_run(self, temp_env):
        """Test cleanup() method in dry-run mode returns True."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                dry_run=True,
                assume_yes=True,
            )
        )
        assert cleanup.cleanup() is True

    def test_cleanup_method_exception(self, temp_env):
        """Test cleanup() method returns False on exception."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        with patch.object(cleanup, "scan_for_cleanup_items", side_effect=OSError("boom")):
            assert cleanup.cleanup() is False

    def test_cleanup_all(self, temp_env):
        """Test cleanup_all returns True."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
            )
        )
        assert cleanup.cleanup_all() is True

    def test_cleanup_app_existing(self, temp_env):
        """Test cleanup_app removes existing wrapper."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        result = cleanup.cleanup_app("org.mozilla.firefox")
        assert result is True
        assert not (temp_env["bin_dir"] / "firefox").exists()

    def test_cleanup_app_missing(self, temp_env):
        """Test cleanup_app returns True when wrapper doesn't exist."""
        cleanup = WrapperCleanup(
            config=CleanupConfig(
                bin_dir=str(temp_env["bin_dir"]),
                config_dir=str(temp_env["config_dir"]),
                data_dir=str(temp_env["data_dir"]),
                assume_yes=True,
            )
        )
        result = cleanup.cleanup_app("org.nonexistent.app")
        assert result is True


@pytest.mark.skipif(not CLEANUP_AVAILABLE, reason="WrapperCleanup not available")
class TestCleanupMain:
    """Test cleanup main() CLI."""

    def test_main_help(self, capsys):
        """Test main() with --help exits 0."""
        with patch("sys.argv", ["fplaunch-cleanup", "--help"]):
            try:
                result = main()
                assert result == 0
            except SystemExit as e:
                # argparse may raise SystemExit on --help
                assert e.code == 0

    def test_main_dry_run(self, temp_env, capsys):
        """Test main() with --dry-run runs cleanup in dry-run mode."""
        with patch(
            "sys.argv",
            [
                "fplaunch-cleanup",
                "--dry-run",
                "--bin-dir",
                str(temp_env["bin_dir"]),
                "--config-dir",
                str(temp_env["config_dir"]),
            ],
        ):
            with patch("lib.cleanup.Path.home", return_value=temp_env["home"]):
                result = main()
        assert result == 0

    def test_main_with_yes(self, temp_env, capsys):
        """Test main() with --yes runs cleanup non-interactively."""
        (temp_env["bin_dir"] / "firefox").write_text("#!/bin/bash\n")
        with patch(
            "sys.argv",
            [
                "fplaunch-cleanup",
                "--yes",
                "--bin-dir",
                str(temp_env["bin_dir"]),
                "--config-dir",
                str(temp_env["config_dir"]),
            ],
        ):
            with patch("lib.cleanup.Path.home", return_value=temp_env["home"]):
                result = main()
        assert result == 0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
