#!/usr/bin/env python3
"""Additional edge-path coverage tests for lib/manage.WrapperManager.

Targets the gaps reported by the coverage tool (88% baseline) and the
explicit edge cases listed in the task:

  - list_wrappers with no wrappers found
  - show_info success / failure / emit-mode / verbose warnings
  - set_preference (existing, missing, invalid preference value, OSError)
  - set_preference_all (happy path, no wrappers, partial failure)
  - create_alias (happy path, duplicate, non-existent source, OSError)
  - remove_wrapper (missing, force=True, user-cancelled, OSError)
  - discover_features

Tests use isolated temp directories and unittest.mock.patch where the
filesystem or interactive prompt would otherwise leak into the host.
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

from lib.manage import WrapperManager, main


# ---------------------------------------------------------------------------
# Fixtures and helpers
# ---------------------------------------------------------------------------


@pytest.fixture
def temp_env() -> dict[str, Path]:
    """Create an isolated bin_dir + config_dir pair for the test."""
    temp_dir = Path(tempfile.mkdtemp(prefix="fpwrapper_mgmt_extra_"))
    bin_dir = temp_dir / "bin"
    config_dir = temp_dir / "config"
    bin_dir.mkdir()
    config_dir.mkdir()
    yield {"temp_dir": temp_dir, "bin_dir": bin_dir, "config_dir": config_dir}
    shutil.rmtree(temp_dir, ignore_errors=True)


def _make_wrapper(bin_dir: Path, name: str, flatpak_id: str | None = None) -> Path:
    """Create a valid-looking wrapper script in bin_dir."""
    wrapper = bin_dir / name
    flatpak_id = flatpak_id or f"org.test.{name}"
    wrapper.write_text(
        "#!/usr/bin/env bash\n"
        "# Generated by fplaunchwrapper\n"
        f'NAME="{name}"\n'
        f'ID="{flatpak_id}"\n'
        f"echo {name}\n"
    )
    wrapper.chmod(0o755)
    return wrapper


def _make_manager(temp_env: dict[str, Path], **kwargs: object) -> WrapperManager:
    """Build a WrapperManager bound to the isolated temp directories."""
    return WrapperManager(
        bin_dir=str(temp_env["bin_dir"]),
        config_dir=str(temp_env["config_dir"]),
        **kwargs,
    )


# ---------------------------------------------------------------------------
# list_wrappers
# ---------------------------------------------------------------------------


class TestListWrappersEdgeCases:
    """Cover the lines 104-106 verbose-warning branch and the empty case."""

    def test_list_wrappers_empty_directory(self, temp_env: dict[str, Path]) -> None:
        """Empty bin_dir should produce an empty list."""
        mgr = _make_manager(temp_env)
        assert mgr.list_wrappers() == []

    def test_list_wrappers_skips_non_executable(self, temp_env: dict[str, Path]) -> None:
        """A wrapper-looking file that is not executable should be skipped."""
        wrapper = temp_env["bin_dir"] / "notexec"
        wrapper.write_text(
            "#!/usr/bin/env bash\n"
            "# Generated by fplaunchwrapper\n"
            'ID="org.test.notexec"\n'
        )
        # Explicitly NOT chmod'ing it
        mgr = _make_manager(temp_env)
        assert mgr.list_wrappers() == []

    def test_list_wrappers_verbose_warning_on_unreadable(
        self, temp_env: dict[str, Path], capsys: pytest.CaptureFixture[str]
    ) -> None:
        """OSError reading a non-wrapper, executable file should be logged in verbose mode.

        Covers lines 104-106 (the except OSError branch).
        """
        # A non-wrapper file that IS executable will fall into the
        # else branch and trigger item.read_text(); mock that to raise.
        legacy = temp_env["bin_dir"] / "broken"
        legacy.write_text("#!/bin/bash\necho broken\n")
        legacy.chmod(0o755)

        mgr = _make_manager(temp_env, verbose=True)

        real_read_text = Path.read_text

        def _raise(self: Path, *args: object, **kwargs: object) -> str:
            if self == legacy:
                raise OSError("synthetic read failure")
            return real_read_text(self, *args, **kwargs)

        with patch.object(Path, "read_text", _raise):
            wrappers = mgr.list_wrappers()

        # The broken file is skipped, list is empty.
        assert wrappers == []
        captured = capsys.readouterr()
        assert "broken" in captured.err
        assert "Could not read" in captured.err


# ---------------------------------------------------------------------------
# show_info
# ---------------------------------------------------------------------------


class TestShowInfoBranches:
    """Cover the show_info branches: success, missing, emit mode (line 156)."""

    def test_show_info_success_with_preference_file(
        self, temp_env: dict[str, Path]
    ) -> None:
        """show_info returns True and surfaces the stored preference."""
        _make_wrapper(temp_env["bin_dir"], "firefox", "org.mozilla.firefox")
        (temp_env["config_dir"] / "firefox.pref").write_text("flatpak")
        mgr = _make_manager(temp_env)
        assert mgr.show_info("firefox") is True

    def test_show_info_nonexistent_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """show_info for a missing wrapper must return False (line 134-136 branch)."""
        mgr = _make_manager(temp_env)
        assert mgr.show_info("ghost") is False

    def test_show_info_emit_mode_no_config_dir(self) -> None:
        """show_info with config_dir=None prints the emit-mode line (line 156)."""
        tmp = Path(tempfile.mkdtemp(prefix="fpwrapper_show_info_emit_"))
        try:
            bin_dir = tmp / "bin"
            config_dir = tmp / "config"
            bin_dir.mkdir()
            config_dir.mkdir()
            _make_wrapper(bin_dir, "firefox", "org.mozilla.firefox")
            mgr = WrapperManager(
                bin_dir=str(bin_dir), config_dir=str(config_dir)
            )
            # Force config_dir to None to exercise the emit-mode branch
            mgr.config_dir = None
            assert mgr.show_info("firefox") is True
        finally:
            shutil.rmtree(tmp, ignore_errors=True)


# ---------------------------------------------------------------------------
# set_preference
# ---------------------------------------------------------------------------


class TestSetPreferenceBranches:
    """Cover all set_preference branches (156, 220-221, 242, 255, 257-259)."""

    def test_set_preference_existing_wrapper_returns_true(
        self, temp_env: dict[str, Path]
    ) -> None:
        """Happy path: wrapper exists, preference is written to the .pref file."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        mgr = _make_manager(temp_env)
        assert mgr.set_preference("firefox", "flatpak") is True
        assert (
            temp_env["config_dir"] / "firefox.pref"
        ).read_text().strip() == "flatpak"

    def test_set_preference_nonexistent_wrapper_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """Missing wrapper -> returns False (line 245-247)."""
        mgr = _make_manager(temp_env)
        assert mgr.set_preference("ghost", "system") is False

    def test_set_preference_invalid_value_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """An invalid preference string is rejected up front (line 229-235)."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        mgr = _make_manager(temp_env)
        assert mgr.set_preference("firefox", "not-a-real-pref") is False
        # The .pref file should not be created.
        assert not (temp_env["config_dir"] / "firefox.pref").exists()

    def test_set_preference_bin_dir_none_returns_false(self) -> None:
        """set_preference with bin_dir=None returns False (lines 219-221)."""
        mgr = WrapperManager(emit_mode=True)
        mgr.bin_dir = None
        assert mgr.set_preference("firefox", "system") is False

    def test_set_preference_config_dir_none_raises(self) -> None:
        """set_preference with config_dir=None and emit_mode=False raises RuntimeError (line 242)."""
        tmp = Path(tempfile.mkdtemp(prefix="fpwrapper_set_pref_cfg_"))
        try:
            bin_dir = tmp / "bin"
            config_dir = tmp / "config"
            bin_dir.mkdir()
            config_dir.mkdir()
            _make_wrapper(bin_dir, "firefox")
            mgr = WrapperManager(bin_dir=str(bin_dir), config_dir=str(config_dir))
            # Force config_dir to None to exercise the guard
            mgr.config_dir = None
            mgr.emit_mode = False
            with pytest.raises(RuntimeError, match="config_dir is required"):
                mgr.set_preference("firefox", "system")
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_set_preference_oserror_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """An OSError while writing the .pref file should return False."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        mgr = _make_manager(temp_env)
        # The atomic write path calls ``tempfile.mkstemp``; raising OSError
        # there is what causes ``set_preference`` to return False.
        import tempfile as _tempfile

        def fake_mkstemp(*args, **kwargs):
            raise OSError("synthetic disk full")

        with patch.object(_tempfile, "mkstemp", fake_mkstemp):
            assert mgr.set_preference("firefox", "system") is False

# ---------------------------------------------------------------------------
# set_preference_all
# ---------------------------------------------------------------------------


class TestSetPreferenceAllBranches:
    """Cover the happy path, no-wrappers case, and the failed>0 path (lines 282, 284)."""

    def test_set_preference_all_happy_path(
        self, temp_env: dict[str, Path]
    ) -> None:
        """All wrappers get the new preference and the count is returned."""
        for name in ("firefox", "chrome", "vlc"):
            _make_wrapper(temp_env["bin_dir"], name)
        mgr = _make_manager(temp_env)
        count = mgr.set_preference_all("auto")
        assert count == 3
        for name in ("firefox", "chrome", "vlc"):
            assert (
                temp_env["config_dir"] / f"{name}.pref"
            ).read_text().strip() == "auto"

    def test_set_preference_all_no_wrappers_returns_zero(
        self, temp_env: dict[str, Path]
    ) -> None:
        """With no wrappers, set_preference_all returns 0."""
        mgr = _make_manager(temp_env)
        assert mgr.set_preference_all("flatpak") == 0

    def test_set_preference_all_invalid_preference_returns_zero(
        self, temp_env: dict[str, Path]
    ) -> None:
        """An invalid preference short-circuits to 0 before any writes."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        mgr = _make_manager(temp_env)
        assert mgr.set_preference_all("bogus") == 0
        assert not (temp_env["config_dir"] / "firefox.pref").exists()

    def test_set_preference_all_partial_failure(
        self, temp_env: dict[str, Path]
    ) -> None:
        """When some wrappers can't be updated, the failed branch runs (lines 282, 284).

        We force one wrapper to be missing between list_wrappers() and the
        inner set_preference() by deleting it from disk after the list is
        built. The remaining wrapper still gets updated.
        """
        for name in ("firefox", "chrome"):
            _make_wrapper(temp_env["bin_dir"], name)
        mgr = _make_manager(temp_env)

        # Patch set_preference so that the second call returns False
        original_set_pref = mgr.set_preference
        calls = {"n": 0}

        def _patched(name: str, preference: str) -> bool:
            calls["n"] += 1
            if calls["n"] == 2:
                return False
            return original_set_pref(name, preference)

        with patch.object(mgr, "set_preference", _patched):
            count = mgr.set_preference_all("flatpak")

        assert count == 1


# ---------------------------------------------------------------------------
# create_alias
# ---------------------------------------------------------------------------


class TestCreateAliasBranches:
    """Cover create_alias happy path, duplicate, missing source, and OSError."""

    def test_create_alias_happy_path_writes_aliases_file(
        self, temp_env: dict[str, Path]
    ) -> None:
        """A fresh alias is written to the 'aliases' file in config_dir."""
        mgr = _make_manager(temp_env)
        assert mgr.create_alias("ff", "firefox") is True
        aliases_file = temp_env["config_dir"] / "aliases"
        assert aliases_file.exists()
        assert "ff:firefox" in aliases_file.read_text()

    def test_create_alias_duplicate_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """Re-creating the same alias returns False (lines 371-373)."""
        mgr = _make_manager(temp_env)
        assert mgr.create_alias("ff", "firefox") is True
        assert mgr.create_alias("ff", "chrome") is False

    def test_create_alias_validate_target_missing_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """validate_target=True + missing target -> returns False (lines 348-352)."""
        mgr = _make_manager(temp_env)
        assert (
            mgr.create_alias("ff", "nonexistent", validate_target=True) is False
        )
        # No aliases file should be written.
        assert not (temp_env["config_dir"] / "aliases").exists()

    def test_create_alias_collision_with_existing_wrapper(
        self, temp_env: dict[str, Path]
    ) -> None:
        """An alias name colliding with an existing wrapper still succeeds (line 341-345)."""
        _make_wrapper(temp_env["bin_dir"], "browser")
        mgr = _make_manager(temp_env)
        assert mgr.create_alias("browser", "firefox") is True
        # The aliases file is created despite the warning.
        assert (temp_env["config_dir"] / "aliases").exists()

    def test_create_alias_invalid_target_chars_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """Target with disallowed characters is rejected (lines 332-337)."""
        mgr = _make_manager(temp_env)
        assert mgr.create_alias("ff", "bad/target") is False
        assert mgr.create_alias("ff", "bad target") is False

    def test_create_alias_bin_dir_none_returns_false(self) -> None:
        """create_alias with bin_dir=None returns False (lines 308-310)."""
        mgr = WrapperManager(emit_mode=True)
        mgr.bin_dir = None
        assert mgr.create_alias("ff", "firefox") is False

    def test_create_alias_oserror_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """An OSError while writing the aliases file returns False (lines 385-387)."""
        mgr = _make_manager(temp_env)
        aliases_file = temp_env["config_dir"] / "aliases"

        real_write_text = Path.write_text

        def _raise(self: Path, *args: object, **kwargs: object) -> int:
            if self == aliases_file:
                raise OSError("synthetic disk error")
            return real_write_text(self, *args, **kwargs)

        with patch.object(Path, "write_text", _raise):
            assert mgr.create_alias("ff", "firefox") is False


# ---------------------------------------------------------------------------
# remove_wrapper
# ---------------------------------------------------------------------------


class TestRemoveWrapperBranches:
    """Cover remove_wrapper for missing wrappers, force=True, and user-cancelled."""

    def test_remove_wrapper_nonexistent_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """Removing a missing wrapper returns False (lines 172-174)."""
        mgr = _make_manager(temp_env)
        assert mgr.remove_wrapper("ghost", force=True) is False

    def test_remove_wrapper_force_true_removes_file_and_prefs(
        self, temp_env: dict[str, Path]
    ) -> None:
        """force=True bypasses the prompt and cleans up wrapper + prefs."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        (temp_env["config_dir"] / "firefox.pref").write_text("flatpak")
        (temp_env["config_dir"] / "firefox.env").write_text("FOO=bar")
        mgr = _make_manager(temp_env)
        assert mgr.remove_wrapper("firefox", force=True) is True
        assert not (temp_env["bin_dir"] / "firefox").exists()
        assert not (temp_env["config_dir"] / "firefox.pref").exists()
        assert not (temp_env["config_dir"] / "firefox.env").exists()

    def test_remove_wrapper_user_cancels_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """force=False with Confirm.ask returning False should not delete (line 180)."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        mgr = _make_manager(temp_env)
        with patch("rich.prompt.Confirm") as mock_confirm:
            mock_confirm.ask.return_value = False
            assert mgr.remove_wrapper("firefox") is False
        # The wrapper is still there.
        assert (temp_env["bin_dir"] / "firefox").exists()

    def test_remove_wrapper_bin_dir_none_returns_false(self) -> None:
        """remove_wrapper with bin_dir=None returns False (lines 162-164)."""
        mgr = WrapperManager(emit_mode=True)
        mgr.bin_dir = None
        assert mgr.remove_wrapper("firefox", force=True) is False

    def test_remove_wrapper_invalid_name_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """Invalid wrapper names are rejected by validate_wrapper_name."""
        mgr = _make_manager(temp_env)
        assert mgr.remove_wrapper("../etc/passwd", force=True) is False
        assert mgr.remove_wrapper("-flag", force=True) is False

    def test_remove_wrapper_config_dir_none_raises(self) -> None:
        """config_dir=None with emit_mode=False raises RuntimeError (line 187)."""
        tmp = Path(tempfile.mkdtemp(prefix="fpwrapper_rm_cfg_"))
        try:
            bin_dir = tmp / "bin"
            config_dir = tmp / "config"
            bin_dir.mkdir()
            config_dir.mkdir()
            _make_wrapper(bin_dir, "firefox")
            mgr = WrapperManager(bin_dir=str(bin_dir), config_dir=str(config_dir))
            mgr.config_dir = None
            mgr.emit_mode = False
            with pytest.raises(RuntimeError, match="config_dir is required"):
                mgr.remove_wrapper("firefox", force=True)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_remove_wrapper_oserror_returns_false(
        self, temp_env: dict[str, Path]
    ) -> None:
        """An OSError while unlinking the wrapper returns False (lines 213-215)."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        mgr = _make_manager(temp_env)
        wrapper_path = temp_env["bin_dir"] / "firefox"

        real_unlink = Path.unlink

        def _raise(self: Path, *args: object, **kwargs: object) -> None:
            if self == wrapper_path:
                raise OSError("synthetic unlink failure")
            return real_unlink(self, *args, **kwargs)

        with patch.object(Path, "unlink", _raise):
            assert mgr.remove_wrapper("firefox", force=True) is False

    def test_remove_wrapper_cleans_scripts_dir(
        self, temp_env: dict[str, Path]
    ) -> None:
        """A scripts/<name>/ directory inside config_dir should be removed."""
        _make_wrapper(temp_env["bin_dir"], "firefox")
        scripts_dir = temp_env["config_dir"] / "scripts" / "firefox"
        scripts_dir.mkdir(parents=True)
        (scripts_dir / "pre.sh").write_text("#!/bin/sh\necho pre\n")
        mgr = _make_manager(temp_env)
        assert mgr.remove_wrapper("firefox", force=True) is True
        assert not scripts_dir.exists()

    def test_remove_wrapper_refuses_escape_scripts_dir(
        self, temp_env: dict[str, Path], monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """A scripts_dir that escapes config_dir is refused (lines 206-209)."""
        _make_wrapper(temp_env["bin_dir"], "firefox")

        # Build a scripts_dir under config_dir, then symlink the parent
        # scripts directory to point at a location outside config_dir.
        outside = temp_env["temp_dir"] / "outside"
        outside.mkdir()
        outside_target = outside / "firefox"
        outside_target.mkdir()
        (outside_target / "pre.sh").write_text("#!/bin/sh\n")

        # Create scripts/<name> as a symlink that resolves outside config_dir
        scripts_link = temp_env["config_dir"] / "scripts" / "firefox"
        scripts_link.parent.mkdir(parents=True, exist_ok=True)
        try:
            scripts_link.symlink_to(outside_target)
        except (OSError, NotImplementedError):
            pytest.skip("symlinks not supported on this filesystem")

        mgr = _make_manager(temp_env)
        assert mgr.remove_wrapper("firefox", force=True) is False
        # The wrapper itself should still be removed (unlink happened first)
        assert not (temp_env["bin_dir"] / "firefox").exists()


# ---------------------------------------------------------------------------
# discover_features
# ---------------------------------------------------------------------------


class TestDiscoverFeatures:
    """discover_features just prints and calls display_wrappers."""

    def test_discover_features_runs_without_wrappers(
        self, temp_env: dict[str, Path]
    ) -> None:
        """discover_features with no wrappers still prints the feature list."""
        mgr = _make_manager(temp_env)
        # Should not raise.
        mgr.discover_features()

    def test_discover_features_runs_with_wrappers(
        self, temp_env: dict[str, Path], capsys: pytest.CaptureFixture[str]
    ) -> None:
        """discover_features prints the feature list and a wrapper table."""
        _make_wrapper(temp_env["bin_dir"], "firefox", "org.mozilla.firefox")
        mgr = _make_manager(temp_env)
        mgr.discover_features()
        captured = capsys.readouterr()
        # The feature list mentions "fplaunchwrapper" or "Features"
        assert "fplaunchwrapper" in captured.out or "Feature" in captured.out


# ---------------------------------------------------------------------------
# main() CLI entry point - cover the unknown-command default (line 509)
# ---------------------------------------------------------------------------


class TestMainCLIDefault:
    """The 'unknown command' branch in main() returns 0 (line 509)."""

    def test_main_with_no_subcommand_returns_zero(
        self, temp_env: dict[str, Path]
    ) -> None:
        """Bare 'fplaunch-manage' invocation goes through the list branch."""
        with patch("sys.argv", ["fplaunch-manage"]):
            with patch("lib.manage.WrapperManager") as mock_cls:
                mock_manager = mock_cls.return_value
                result = main()
        assert result == 0
        mock_manager.display_wrappers.assert_called_once()

    def test_main_unknown_subcommand_falls_through_to_default(
        self,
    ) -> None:
        """An unknown subcommand reaches the final return 0 (line 509)."""
        from argparse import Namespace
        from lib import manage as manage_mod

        fake_args = Namespace(command="totally-bogus-cmd")
        with patch("sys.argv", ["fplaunch-manage", "totally-bogus-cmd"]):
            with patch.object(manage_mod.argparse.ArgumentParser, "parse_args") as mock_parse:
                mock_parse.return_value = fake_args
                with patch("lib.manage.WrapperManager"):
                    result = main()
        assert result == 0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
