#!/usr/bin/env python3
"""REAL execution tests for manage.py with coverage focus.

NO MOCKS - Tests actual code paths for wrapper management.
"""

import shutil
import tempfile
from pathlib import Path

# Import actual implementation
from lib.manage import WrapperManager


class TestWrapperManagerReal:
    """Test WrapperManager with REAL execution."""

    def setup_method(self) -> None:
        """Set up REAL test environment."""
        self.temp_dir = Path(tempfile.mkdtemp())
        self.bin_dir = self.temp_dir / "bin"
        self.config_dir = self.temp_dir / "config"

        # Create REAL directories
        self.bin_dir.mkdir(parents=True)
        self.config_dir.mkdir(parents=True)

        # Create sample wrappers
        self._create_wrapper("firefox", "org.mozilla.firefox")
        self._create_wrapper("chrome", "com.google.Chrome")

    def _create_wrapper(self, name: str, app_id: str) -> None:
        """Helper to create a real wrapper file."""
        wrapper = self.bin_dir / name
        wrapper.write_text(
            f"""#!/usr/bin/env bash
# Generated by fplaunchwrapper

NAME="{name}"
ID="{app_id}"
flatpak run "$ID" "$@"
"""
        )
        wrapper.chmod(0o755)

    def teardown_method(self) -> None:
        """Clean up REAL test environment."""
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def test_init_creates_real_object(self) -> None:
        """Test __init__ creates real WrapperManager object."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            verbose=True,
        )

        assert mgr.config_dir == self.config_dir
        assert mgr.bin_dir == self.bin_dir
        assert mgr.verbose is True
        assert mgr.emit_mode is False

    def test_init_reads_bin_dir_from_config(self) -> None:
        """Test __init__ reads bin_dir from config file."""
        bin_dir_file = self.config_dir / "bin_dir"
        bin_dir_file.write_text(str(self.bin_dir))

        mgr = WrapperManager(config_dir=str(self.config_dir))

        assert mgr.bin_dir == self.bin_dir

    def test_init_handles_missing_config_file(self) -> None:
        """Test __init__ handles missing bin_dir config gracefully."""
        mgr = WrapperManager(config_dir=str(self.config_dir))

        # Should use default ~/bin
        assert mgr.bin_dir == Path.home() / "bin"

    def test_init_creates_directories(self) -> None:
        """Test __init__ creates directories if missing."""
        new_config = self.temp_dir / "new_config"
        new_bin = self.temp_dir / "new_bin"

        WrapperManager(
            config_dir=str(new_config),
            bin_dir=str(new_bin),
        )

        assert new_config.exists()
        assert new_bin.exists()

    def test_init_emit_mode_doesnt_create_dirs(self) -> None:
        """Test __init__ in emit mode doesn't create directories."""
        new_config = self.temp_dir / "emit_config"
        new_bin = self.temp_dir / "emit_bin"

        WrapperManager(
            config_dir=str(new_config),
            bin_dir=str(new_bin),
            emit_mode=True,
        )

        assert not new_config.exists()
        assert not new_bin.exists()

    def test_list_wrappers_finds_real_wrappers(self) -> None:
        """Test list_wrappers() finds real wrapper files."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        wrappers = mgr.list_wrappers()

        assert len(wrappers) == 2
        names = [w["name"] for w in wrappers]
        assert "firefox" in names
        assert "chrome" in names

        # Verify IDs extracted
        firefox_wrapper = next(w for w in wrappers if w["name"] == "firefox")
        assert firefox_wrapper["id"] == "org.mozilla.firefox"

    def test_list_wrappers_empty_directory(self) -> None:
        """Test list_wrappers() with empty bin directory."""
        empty_bin = self.temp_dir / "empty"
        empty_bin.mkdir()

        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(empty_bin),
        )

        wrappers = mgr.list_wrappers()

        assert wrappers == []

    def test_list_wrappers_nonexistent_directory(self) -> None:
        """Test list_wrappers() with nonexistent directory."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.temp_dir / "nonexistent"),
            emit_mode=True,
        )

        wrappers = mgr.list_wrappers()

        assert wrappers == []

    def test_display_wrappers_shows_output(self) -> None:
        """Test display_wrappers() produces output."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        # Should not raise exception
        mgr.display_wrappers()

    def test_remove_wrapper_deletes_file(self) -> None:
        """Test remove_wrapper() deletes real file."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        wrapper = self.bin_dir / "firefox"
        assert wrapper.exists()

        result = mgr.remove_wrapper("firefox", force=True)

        assert result is True
        assert not wrapper.exists()

    def test_remove_wrapper_removes_preference_file(self) -> None:
        """Test remove_wrapper() removes associated preference file."""
        # Create preference file
        pref_file = self.config_dir / "firefox.pref"
        pref_file.write_text("flatpak")

        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.remove_wrapper("firefox", force=True)

        assert result is True
        assert not pref_file.exists()

    def test_remove_wrapper_removes_environment_file(self) -> None:
        """Test remove_wrapper() removes environment file."""
        env_file = self.config_dir / "firefox.env"
        env_file.write_text("MY_VAR=value")

        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        mgr.remove_wrapper("firefox", force=True)

        assert not env_file.exists()

    def test_remove_wrapper_nonexistent(self) -> None:
        """Test remove_wrapper() handles nonexistent wrapper."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.remove_wrapper("nonexistent", force=True)

        assert result is False

    def test_remove_wrapper_emit_mode(self) -> None:
        """Test remove_wrapper() in emit mode doesn't delete."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
            emit_mode=True,
        )

        wrapper = self.bin_dir / "firefox"
        assert wrapper.exists()

        result = mgr.remove_wrapper("firefox", force=True)

        # Returns True but doesn't delete
        assert result is True
        assert wrapper.exists()

    def test_set_preference_creates_file(self) -> None:
        """Test set_preference() creates real preference file."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.set_preference("firefox", "system")

        assert result is True
        pref_file = self.config_dir / "firefox.pref"
        assert pref_file.exists()
        assert pref_file.read_text() == "system"

    def test_set_preference_updates_existing(self) -> None:
        """Test set_preference() updates existing preference."""
        pref_file = self.config_dir / "firefox.pref"
        pref_file.write_text("flatpak")

        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.set_preference("firefox", "system")

        assert result is True
        assert pref_file.read_text() == "system"

    def test_set_preference_invalid_value(self) -> None:
        """Test set_preference() accepts any preference value (no validation)."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.set_preference("firefox", "invalid value!")

        assert result is True
        pref_file = self.config_dir / "firefox.pref"
        assert pref_file.exists()
        assert pref_file.read_text() == "invalid value!"

    def test_set_preference_all_sets_multiple(self) -> None:
        """Test set_preference_all() sets preference for all wrappers."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        count = mgr.set_preference_all("system")

        assert count == 2
        assert (self.config_dir / "firefox.pref").read_text() == "system"
        assert (self.config_dir / "chrome.pref").read_text() == "system"

    def test_show_info_displays_wrapper_info(self) -> None:
        """Test show_info() displays information."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.show_info("firefox")

        assert result is True

    def test_show_info_nonexistent_wrapper(self) -> None:
        """Test show_info() handles nonexistent wrapper."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.show_info("nonexistent")

        assert result is False

    def test_create_alias_creates_file(self) -> None:
        """Test create_alias() creates alias file."""
        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        result = mgr.create_alias("ff", "firefox")

        assert result is True
        aliases_file = self.config_dir / "aliases"
        assert aliases_file.exists()
        content = aliases_file.read_text()
        assert "ff:firefox" in content

    def test_create_alias_appends_to_existing(self) -> None:
        """Test create_alias() appends to existing aliases."""
        aliases_file = self.config_dir / "aliases"
        aliases_file.write_text("gc:chrome")

        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        mgr.create_alias("ff", "firefox")

        content = aliases_file.read_text()
        assert "gc:chrome" in content
        assert "ff:firefox" in content


class TestManagerIntegration:
    """Integration tests for WrapperManager."""

    def setup_method(self) -> None:
        """Set up test environment."""
        self.temp_dir = Path(tempfile.mkdtemp())
        self.bin_dir = self.temp_dir / "bin"
        self.config_dir = self.temp_dir / "config"
        self.bin_dir.mkdir()
        self.config_dir.mkdir()

    def teardown_method(self) -> None:
        """Clean up."""
        shutil.rmtree(self.temp_dir, ignore_errors=True)

    def test_full_workflow_create_configure_remove(self) -> None:
        """Test complete wrapper management workflow."""
        # Create wrapper
        wrapper = self.bin_dir / "testapp"
        wrapper.write_text(
            '#!/bin/bash\n# Generated by fplaunchwrapper\nID="com.example.Test"\n'
        )
        wrapper.chmod(0o755)

        mgr = WrapperManager(
            config_dir=str(self.config_dir),
            bin_dir=str(self.bin_dir),
        )

        # List wrappers
        wrappers = mgr.list_wrappers()
        assert len(wrappers) == 1

        # Set preference
        mgr.set_preference("testapp", "system")
        assert (self.config_dir / "testapp.pref").read_text().strip() == "system"

        # Create alias
        mgr.create_alias("ta", "testapp")

        # Remove wrapper
        mgr.remove_wrapper("testapp", force=True)
        assert not wrapper.exists()
