#!/usr/bin/env bash

# Common utility functions for fplaunchwrapper scripts

# Initialize standard paths and variables
init_paths() {
    CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers"
    BIN_DIR_FILE="$CONFIG_DIR/bin_dir"
    BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"
    
    # Load saved BIN_DIR if available
    if [ -f "$BIN_DIR_FILE" ]; then
        BIN_DIR=$(cat "$BIN_DIR_FILE")
    fi
}

# Validate that a directory is within the user's home
validate_home_dir() {
    local dir="$1"
    local operation="${2:-operation}"
    
    case "$dir" in
        "$HOME"/*|"$HOME")
            return 0
            ;;
        *)
            echo "Error: ${operation^} directory must be within your home directory ($HOME)" >&2
            echo "Path: $dir" >&2
            return 1
            ;;
    esac
}

# Check if a file is a wrapper generated by fplaunchwrapper
is_wrapper_file() {
    local file="$1"
    
    if [ -f "$file" ] && head -n 5 "$file" 2>/dev/null | grep -q '^# Generated by fplaunchwrapper$'; then
        return 0
    fi
    return 1
}

# Ensure config directory exists
ensure_config_dir() {
    CONFIG_DIR="${CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/flatpak-wrappers}"
    mkdir -p "$CONFIG_DIR"
}

# Get the systemd user unit directory
get_systemd_unit_dir() {
    echo "${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
}

# Stop and disable systemd units
cleanup_systemd_units() {
    local unit_prefix="${1:-flatpak-wrappers}"
    
    systemctl --user stop "${unit_prefix}.service" 2>/dev/null || true
    systemctl --user stop "${unit_prefix}.path" 2>/dev/null || true
    systemctl --user stop "${unit_prefix}.timer" 2>/dev/null || true
    systemctl --user disable "${unit_prefix}.service" 2>/dev/null || true
    systemctl --user disable "${unit_prefix}.path" 2>/dev/null || true
    systemctl --user disable "${unit_prefix}.timer" 2>/dev/null || true
    
    local unit_dir
    unit_dir=$(get_systemd_unit_dir)
    rm -f "$unit_dir/${unit_prefix}.service"
    rm -f "$unit_dir/${unit_prefix}.path"
    rm -f "$unit_dir/${unit_prefix}.timer"
    
    systemctl --user daemon-reload 2>/dev/null || true
}
