#!/usr/bin/env python3
"""Wrapper management functionality for fplaunchwrapper
Replaces fplaunch-manage bash script with Python implementation.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.table import Table

from .paths import get_default_config_dir, resolve_bin_dir
from .safety import (
    get_wrapper_id,
    is_wrapper_file,
)

console = Console()
console_err = Console(stderr=True)


class WrapperManager:
    """Manages Flatpak application wrappers."""

    def __init__(
        self,
        bin_dir: str | Path | None = None,
        config_dir: str | Path | None = None,
        verbose: bool = False,
        emit_mode: bool = False,
        emit_verbose: bool = False,
        **kwargs: Any,
    ) -> None:
        self.verbose = verbose
        self.emit_mode = emit_mode
        self.emit_verbose = emit_verbose
        self.config_dir = Path(config_dir) if config_dir else get_default_config_dir()

        self.bin_dir = resolve_bin_dir(
            explicit_dir=str(bin_dir) if bin_dir else None,
            config_dir=self.config_dir,
        )

        if not emit_mode:
            self.bin_dir.mkdir(parents=True, exist_ok=True)
            self.config_dir.mkdir(parents=True, exist_ok=True)

    def log(self, message: str, level: str = "info") -> None:
        """Log a message to stdout or stderr based on level.

        Error and warning messages go to stderr.
        Info and success messages go to stdout.
        Always prints regardless of verbose mode.
        """
        if level == "error":
            console_err.print(f"[red]ERROR:[/red] {message}")
        elif level == "warning":
            console_err.print(f"[yellow]WARN:[/yellow] {message}")
        elif level == "success":
            console.print(f"[green]✓[/green] {message}")
        elif level in ["info", "emit"]:
            console.print(message)
        else:
            console.print(message)

    def list_wrappers(self) -> list[dict[str, str]]:
        """List all installed wrappers."""
        wrappers: list[dict[str, str]] = []

        if not self.bin_dir.exists():
            return wrappers

        for item in self.bin_dir.iterdir():
            if item.is_file() and os.access(item, os.X_OK):
                if is_wrapper_file(str(item)):
                    wrapper_id = get_wrapper_id(str(item))
                    wrappers.append(
                        {
                            "name": item.name,
                            "path": str(item),
                            "id": wrapper_id or "unknown",
                        },
                    )
                else:
                    try:
                        content = item.read_text()
                        if "Generated by fplaunchwrapper" in content:
                            wrappers.append(
                                {
                                    "name": item.name,
                                    "path": str(item),
                                    "id": "unknown (legacy)",
                                },
                            )
                    except Exception:
                        pass

        return sorted(wrappers, key=lambda x: x["name"])

    def display_wrappers(self) -> None:
        """Display installed wrappers in a table."""
        wrappers = self.list_wrappers()
        if not wrappers:
            self.log("No wrappers found")
            return

        table = Table(title="Installed Flatpak Wrappers")
        table.add_column("Name", style="cyan")
        table.add_column("Application ID", style="magenta")
        table.add_column("Path", style="green")

        for w in wrappers:
            table.add_row(w["name"], w["id"], w["path"])

        console.print(table)

    def show_info(self, name: str) -> bool:
        """Show detailed information about a wrapper."""
        wrapper_path = self.bin_dir / name
        if not wrapper_path.exists():
            self.log(f"Wrapper not found: {name}", "error")
            return False

        if not is_wrapper_file(str(wrapper_path)):
            self.log(f"File is not a managed wrapper: {name}", "warning")
            return False

        wrapper_id = get_wrapper_id(str(wrapper_path))

        console.print(f"[bold]Wrapper Name:[/bold] {name}")
        console.print(f"[bold]Application ID:[/bold] {wrapper_id or 'unknown'}")
        console.print(f"[bold]Path:[/bold] {wrapper_path}")

        pref_file = self.config_dir / f"{name}.pref"
        if pref_file.exists():
            pref = pref_file.read_text().strip()
            console.print(f"[bold]Launch Preference:[/bold] {pref}")
        else:
            console.print("[bold]Launch Preference:[/bold] none (will prompt)")

        return True

    def remove_wrapper(self, name: str, force: bool = False) -> bool:
        """Remove a wrapper and its associated files."""
        wrapper_path = self.bin_dir / name
        if not wrapper_path.exists():
            self.log(f"Wrapper not found: {name}", "error")
            return False

        if not force:
            from rich.prompt import Confirm

            if not Confirm.ask(f"Are you sure you want to remove wrapper '{name}'?"):
                return False

        if self.emit_mode:
            self.log(f"Would remove wrapper: {wrapper_path}", "emit")
            return True

        try:
            wrapper_path.unlink()

            pref_file = self.config_dir / f"{name}.pref"
            if pref_file.exists():
                pref_file.unlink()

            env_file = self.config_dir / f"{name}.env"
            if env_file.exists():
                env_file.unlink()

            scripts_dir = self.config_dir / "scripts" / name
            if scripts_dir.exists():
                shutil.rmtree(scripts_dir)

            self.log(f"Removed wrapper: {name}", "success")
            return True
        except Exception as e:
            self.log(f"Failed to remove {name}: {e}", "error")
            return False

    def set_preference(self, name: str, preference: str) -> bool:
        """Set launch preference for a wrapper."""
        wrapper_path = self.bin_dir / name
        if not wrapper_path.exists():
            self.log(f"Wrapper not found: {name}", "error")
            return False

        if self.emit_mode:
            self.log(f"Would set preference for {name} to {preference}", "emit")
            return True

        try:
            pref_file = self.config_dir / f"{name}.pref"
            pref_file.write_text(preference)
            self.log(f"Preference for {name} set to {preference}", "success")
            return True
        except Exception as e:
            self.log(f"Failed to set preference: {e}", "error")
            return False

    def set_preference_all(self, preference: str) -> int:
        """Set launch preference for all wrappers.

        Returns the number of wrappers updated.
        """
        wrappers = self.list_wrappers()
        updated = 0
        for wrapper in wrappers:
            if self.set_preference(wrapper["name"], preference):
                updated += 1
        self.log(f"Updated preference for {updated} wrappers", "success")
        return updated

    def create_alias(
        self,
        alias_name: str,
        target: str,
        validate_target: bool = False,
    ) -> bool:
        """Create an alias for a wrapper.

        Args:
            alias_name: The alias name to create
            target: The target wrapper name or Flatpak ID
            validate_target: If True, verify target exists before creating alias

        Returns:
            True if alias was created successfully, False otherwise
        """
        # Input validation
        if not alias_name or not alias_name.strip():
            self.log("Empty alias name rejected", "error")
            return False
        if not target or not target.strip():
            self.log("Empty target name rejected", "error")
            return False

        alias_name = alias_name.strip()
        target = target.strip()

        # Validate alias_name for path traversal and dangerous characters
        # Alias names should be simple identifiers, not paths
        if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*$", alias_name):
            self.log(
                f"Invalid alias name '{alias_name}': must be alphanumeric starting with letter",
                "error",
            )
            return False

        # Also validate target to prevent injection
        if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9._-]*$", target):
            self.log(
                f"Invalid target '{target}': must be alphanumeric starting with letter",
                "error",
            )
            return False

        # Check for collision with existing wrapper
        wrapper_path = self.bin_dir / alias_name
        if wrapper_path.exists():
            self.log(
                f"Warning: alias '{alias_name}' collides with existing wrapper",
                "warning",
            )

        # Validate target if requested
        if validate_target:
            target_wrapper = self.bin_dir / target
            if not target_wrapper.exists():
                self.log(f"Target wrapper not found: {target}", "error")
                return False

        if self.emit_mode:
            self.log(f"Would create alias: {alias_name} -> {target}", "emit")
            return True

        try:
            aliases_file = self.config_dir / "aliases"

            # Read existing aliases
            existing_aliases: dict[str, str] = {}
            if aliases_file.exists():
                for line in aliases_file.read_text().splitlines():
                    if ":" in line:
                        k, v = line.split(":", 1)
                        existing_aliases[k.strip()] = v.strip()

            # Check if alias already exists
            if alias_name in existing_aliases:
                self.log(f"Alias '{alias_name}' already exists", "error")
                return False

            # Add new alias
            existing_aliases[alias_name] = target

            # Write sorted aliases
            sorted_aliases = sorted(existing_aliases.items())
            aliases_file.write_text(
                "\n".join(f"{k}:{v}" for k, v in sorted_aliases) + "\n"
            )
            self.log(f"Created alias: {alias_name} -> {target}", "success")
            return True
        except Exception as e:
            self.log(f"Failed to create alias: {e}", "error")
            return False

    def list_managed_files(
        self,
        app_name: str | None = None,
        file_type: str | None = None,
    ) -> dict[str, list[dict[str, str]]]:
        """List all managed files for an application or all applications.

        Args:
            app_name: Specific application name, or None for all apps
            file_type: Filter by type: "wrappers", "prefs", "env", or "all"

        Returns:
            Dict mapping app names to lists of file info dicts
        """
        result: dict[str, list[dict[str, str]]] = {}

        def add_file(app: str, ftype: str, path: Path) -> None:
            if app not in result:
                result[app] = []
            result[app].append({"type": ftype, "path": str(path)})

        wrappers = self.list_wrappers()

        for wrapper in wrappers:
            name = wrapper["name"]
            if app_name and name != app_name:
                continue

            if file_type in (None, "all", "wrappers"):
                add_file(name, "wrapper", self.bin_dir / name)

            if file_type in (None, "all", "prefs"):
                pref_file = self.config_dir / f"{name}.pref"
                if pref_file.exists():
                    add_file(name, "pref", pref_file)

            if file_type in (None, "all", "env"):
                env_file = self.config_dir / f"{name}.env"
                if env_file.exists():
                    add_file(name, "env", env_file)

        # Add aliases file if exists
        aliases_file = self.config_dir / "aliases"
        if aliases_file.exists():
            result["_aliases"] = [{"type": "aliases", "path": str(aliases_file)}]

        return result

    def discover_features(self) -> None:
        """Discover and display available features and capabilities."""
        console.print("[bold]fplaunchwrapper Features:[/bold]")
        console.print("  • Wrapper generation for Flatpak apps")
        console.print("  • Preference management (system/flatpak)")
        console.print("  • Alias creation for shortcuts")
        console.print("  • Pre/post launch scripts")
        console.print("  • Systemd integration for auto-updates")
        self.display_wrappers()


def main() -> int:
    """Command-line interface for wrapper management."""
    parser = argparse.ArgumentParser(
        description="Manage Flatpak application wrappers",
    )

    subparsers = parser.add_subparsers(dest="command", help="Management command")

    # List command
    list_parser = subparsers.add_parser("list", help="List all wrappers")
    list_parser.add_argument(
        "--all", "-a", action="store_true", help="List all wrappers"
    )

    # Search/discover command
    subparsers.add_parser("search", help="Search for wrappers")
    subparsers.add_parser("discover", help="Discover wrappers (alias for search)")

    # Remove command
    remove_parser = subparsers.add_parser("rm", help="Remove a wrapper")
    remove_parser.add_argument("name", help="Wrapper name to remove")
    remove_parser.add_argument("--force", action="store_true", help="Force removal")

    # Cleanup command
    subparsers.add_parser("cleanup", help="Clean up obsolete wrappers")

    # Set preference command
    pref_parser = subparsers.add_parser("set-pref", help="Set launch preference")
    pref_parser.add_argument("name", help="Wrapper name")
    pref_parser.add_argument("preference", help="Launch preference (system/flatpak)")

    args = parser.parse_args()

    # Handle commands
    if args.command == "search" or args.command == "discover":
        # Create a manager and call discover_features
        manager = WrapperManager()
        manager.discover_features()
        return 0
    elif args.command == "rm":
        manager = WrapperManager()
        if manager.remove_wrapper(args.name, force=args.force):
            return 0
        return 1
    elif args.command == "cleanup":
        manager = WrapperManager()
        result = manager.list_wrappers()
        # Return count of wrappers cleaned (simplified)
        return len(result) > 0 if result else 0
    elif args.command == "set-pref":
        manager = WrapperManager()
        if manager.set_preference(args.name, args.preference):
            return 0
        return 1
    elif args.command == "list" or args.command is None:
        manager = WrapperManager()
        manager.display_wrappers()
        return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
