#!/usr/bin/env bash
set_pref() {
    name="$1"
    choice="$2"
    if [ "$choice" != "system" ] && [ "$choice" != "flatpak" ]; then
        echo "Invalid choice: use 'system' or 'flatpak'"
    fi
    pref_file="$CONFIG_DIR/$name.pref"
    read -r -p "Set preference for '$name' to '$choice'? (y/n): " confirm
    if [[ $confirm =~ ^[Yy]$ ]]; then
        echo "$choice" > "$pref_file"
        echo "Set preference for $name to $choice"
    else
        echo "Cancelled."
    fi
}

remove_pref() {
    name="$1"
    pref_file="$CONFIG_DIR/$name.pref"
    if [ -f "$pref_file" ]; then
        read -r -p "Remove preference for '$name'? (y/n): " confirm
        if [[ $confirm =~ ^[Yy]$ ]]; then
            rm "$pref_file"
            echo "Removed preference for $name"
        else
            echo "Removal cancelled."
        fi
    else
        echo "No preference found for $name"
    fi
}

set_pref_all() {
    pref="$1"
    if [ "$pref" != "system" ] && [ "$pref" != "flatpak" ]; then
        echo "Invalid preference: use 'system' or 'flatpak'"
    fi
    read -r -p "Set preference to '$pref' for all wrappers? (y/n): " confirm
    if [[ $confirm =~ ^[Yy]$ ]]; then
        for script in "$BIN_DIR"/*; do
            if [ -f "$script" ] && grep -q "Generated by fplaunchwrapper" "$script" 2>/dev/null; then
                name=$(basename "$script")
                echo "$pref" > "$CONFIG_DIR/$name.pref"
            fi
        done
        echo "Set preference to $pref for all wrappers"
    else
        echo "Cancelled."
    fi
}