#!/usr/bin/env python3
"""Robust Python utilities for fplaunchwrapper
This script provides secure implementations of critical operations.
"""

from __future__ import annotations

import contextlib
import hashlib
import os
import re
import sys
import tempfile
import time
import unicodedata
from pathlib import Path
from typing import Any

try:
    from .paths import get_default_config_dir, get_lock_dir, ensure_dir
except ImportError:
    from lib.paths import get_default_config_dir, get_lock_dir, ensure_dir

# Constants for file operations
# Can be overridden via environment variables for testing/customization
MAX_FILE_SIZE = int(os.environ.get("FPWRAPPER_MAX_FILE_SIZE", 100_000))  # 100KB limit
BUFFER_SIZE = int(os.environ.get("FPWRAPPER_BUFFER_SIZE", 8192))
DEFAULT_LOCK_TIMEOUT = float(os.environ.get("FPWRAPPER_LOCK_TIMEOUT", 30.0))

# Regex pattern for sanitizing strings - matches special characters that need escaping
_SANITIZE_PATTERN = re.compile(r'([\\"\'$`();&|<>\t\n\r])')


def sanitize_string(input_str: str) -> str:
    """Safely sanitize a string for use in Python code.

    Uses regex substitution for efficiency over sequential .replace() calls.
    """
    if not input_str:
        return ""
    return _SANITIZE_PATTERN.sub(r"\\\1", input_str)


def canonicalize_path_no_resolve(path: str | Path) -> Path | None:
    """Normalize a path without resolving symlinks."""
    try:
        path_str = str(path)

        if path_str.startswith("~"):
            path_str = str(Path(path_str).expanduser())

        if not Path(path_str).is_absolute():
            path_str = str(Path(path_str).resolve())

        return Path(Path(path_str).resolve())

    except (TypeError, ValueError, OSError):
        return None


def validate_home_dir(dir_path: str | Path) -> str | None:
    """Validate that a directory is within HOME.

    Returns the normalized absolute path string if the directory is within the user's HOME,
    otherwise returns None. Accepts string or Path-like input.
    """
    try:
        dir_str = str(dir_path)

        if dir_str.startswith("~"):
            dir_str = str(Path(dir_str).expanduser())

        abs_dir = str(Path(dir_str).resolve())

        if Path(abs_dir).is_symlink():
            abs_dir = str(Path(abs_dir).resolve())

        home = str(Path.home())
        if abs_dir == home or abs_dir.startswith(home + os.sep):
            return str(abs_dir)

        return None
    except (TypeError, ValueError, OSError):
        return None


def is_wrapper_file(file_path: str | Path) -> bool:
    """Check if a file is a valid wrapper script."""
    try:
        if not Path(file_path).is_file():
            return False
        if not os.access(file_path, os.R_OK):
            return False
        if Path(file_path).is_symlink():
            return False

        size = Path(file_path).stat().st_size
        if size > MAX_FILE_SIZE:
            return False

        with Path(file_path).open(encoding="utf-8", errors="ignore") as f:
            content = f.read(min(BUFFER_SIZE, size))

        if any(ord(c) < 32 and c not in "\t\n\r" for c in content):
            return False

        if not re.match(r"^#!.*(bash|sh)", content, re.MULTILINE):
            return False

        if "Generated by fplaunchwrapper" not in content:
            return False

        name_match = re.search(r"^NAME=[^\n]*", content, re.MULTILINE)
        id_match = re.search(r"^ID=[^\n]*", content, re.MULTILINE)

        if not name_match or not id_match:
            return False

        id_value = re.search(r'ID="([^"]*)"', id_match.group())
        return not (
            not id_value or not re.match(r"^[A-Za-z0-9._-]+$", id_value.group(1))
        )
    except (IOError, OSError, UnicodeDecodeError, re.error):
        return False


def get_wrapper_id(file_path: str | Path) -> str | None:
    """Extract the wrapper ID from a wrapper script.

    Returns the ID string when found, otherwise returns None.
    """
    try:
        with Path(file_path).open(encoding="utf-8", errors="ignore") as f:
            content = f.read(BUFFER_SIZE)

        id_match = re.search(r'^ID="([^"]*)"', content, re.MULTILINE)
        if id_match:
            return id_match.group(1)

        comment_match = re.search(r"Flatpak ID:\s*([^\s\n]+)", content)
        if comment_match:
            return comment_match.group(1)

        return None
    except (IOError, OSError, UnicodeDecodeError, re.error):
        return None


def sanitize_id_to_name(id_str: str) -> str:
    """Sanitize a Flatpak ID to a safe name."""
    try:
        name = id_str.rsplit(".", maxsplit=1)[-1].lower()

        try:
            name = unicodedata.normalize("NFKD", name)
            name = "".join(c for c in name if not unicodedata.combining(c))
        except ImportError:
            pass

        with contextlib.suppress(UnicodeError):
            name = name.encode("ascii", "ignore").decode("ascii")

        name = re.sub(r"[^a-z0-9_\-]", "-", name)

        name = re.sub(r"^\-+|\-+$", "", name)
        name = re.sub(r"\-+", "-", name)

        if not name:
            hash_obj = hashlib.sha256(id_str.encode("utf-8"))
            name = f"app-{hash_obj.hexdigest()[:8]}"

        return name[:100]

    except (TypeError, AttributeError, UnicodeDecodeError, re.error):
        try:
            return f"app-{hashlib.sha256(id_str.encode('utf-8')).hexdigest()[:8]}"
        except (TypeError, AttributeError, UnicodeDecodeError):
            return "app-fallback"


def find_executable(cmd: str) -> str | None:
    """Find an executable in PATH with security checks."""
    try:
        if "/" in cmd:
            if Path(cmd).is_file() and os.access(cmd, os.X_OK):
                # Resolve symlinks to prevent symlink attacks
                return str(Path(cmd).resolve())
            return None

        for path_dir in os.getenv("PATH", "").split(":"):
            if not path_dir:
                continue
            exe_path = str(Path(path_dir) / cmd)
            if Path(exe_path).is_file() and os.access(exe_path, os.X_OK):
                # Resolve symlinks to prevent symlink attacks
                return str(Path(exe_path).resolve())

        return None
    except (TypeError, OSError, AttributeError):
        return None


def safe_mktemp(
    template: str = "tmp.XXXXXX", dir_param: str | None = None,
) -> str | None:
    """Create a secure temporary file.

    Returns the created temporary file path, or None on failure.
    """
    try:
        if dir_param and Path(dir_param).is_dir():
            tdir = dir_param
        else:
            tdir = tempfile.gettempdir()

        if "XXXXXX" in template:
            parts = template.split("XXXXXX", 1)
            prefix = parts[0] if parts[0] else None
            suffix = parts[1] if len(parts) > 1 else ""
        else:
            prefix = template
            suffix = ""

        fd, path = tempfile.mkstemp(prefix=prefix, suffix=suffix, dir=tdir)
        os.close(fd)
        return path
    except (IOError, OSError, ValueError):
        return None


def acquire_lock(
    lock_name: str = "fplaunch",
    timeout_seconds: float = DEFAULT_LOCK_TIMEOUT,
    lock_dir: Path | None = None,
) -> bool | None:
    """Acquire a file-based lock with timeout.

    Uses a file-based lock with PID tracking for stale lock detection.
    Lock is stored as a file containing the PID of the holding process.

    Args:
        lock_name: Name of the lock
        timeout_seconds: How long to wait for lock acquisition
        lock_dir: Directory for lock files (defaults to config-based locks)
    """
    try:
        if lock_dir is None:
            config_dir = get_default_config_dir()
            ensure_dir(config_dir)
            lock_dir = get_lock_dir()
        ensure_dir(lock_dir)

        lockfile = lock_dir / f"{lock_name}.lock"
        pidfile = lock_dir / f"{lock_name}.pid"

        start_time = time.time()
        end_time = start_time + timeout_seconds

        while time.time() < end_time:
            try:
                if lockfile.exists():
                    if _cleanup_stale_lock(lockfile, pidfile):
                        continue

                lockfile.mkdir(parents=True, exist_ok=False)
                pidfile.write_text(str(os.getpid()))
                return True
            except FileExistsError:
                time.sleep(0.1)
                continue
            except OSError:
                time.sleep(0.1)
                continue

        return False  # Timeout

    except (IOError, OSError, PermissionError, RuntimeError):
        return False


def _cleanup_stale_lock(lockfile: Path, pidfile: Path) -> bool:
    """Check if lock is stale and clean it up if the process is dead.

    Returns True if lock was cleaned up, False otherwise.
    """
    try:
        if not pidfile.exists():
            with contextlib.suppress(OSError):
                lockfile.rmdir()
            return True

        try:
            stored_pid = int(pidfile.read_text().strip())
        except (ValueError, OSError):
            with contextlib.suppress(OSError):
                lockfile.rmdir()
                pidfile.unlink(missing_ok=True)
            return True

        try:
            os.kill(stored_pid, 0)
            return False
        except OSError:
            pass

        with contextlib.suppress(OSError):
            lockfile.rmdir()
            pidfile.unlink(missing_ok=True)
        return True

    except (OSError, ValueError, IOError):
        return False


def release_lock(lock_name: str = "fplaunch", lock_dir: Path | None = None) -> bool | None:
    """Release a file-based lock."""
    try:
        if lock_dir is None:
            lock_dir = get_lock_dir()
        lockfile = lock_dir / f"{lock_name}.lock"
        pidfile = lock_dir / f"{lock_name}.pid"

        if pidfile.exists():
            stored_pid = pidfile.read_text().strip()
            if stored_pid == str(os.getpid()):
                with contextlib.suppress(FileNotFoundError):
                    lockfile.rmdir()  # lockfile is a directory, not a file
                with contextlib.suppress(FileNotFoundError):
                    pidfile.unlink()
                return True

        return False

    except (IOError, OSError, PermissionError):
        return False


def get_temp_dir() -> str:
    """Get the best available temporary directory."""
    temp_dir = tempfile.gettempdir()
    if temp_dir and Path(temp_dir).is_dir() and os.access(temp_dir, os.W_OK):
        return temp_dir

    fallback_cache_dir = str(Path.home() / ".cache")
    if Path(fallback_cache_dir).is_dir() and os.access(fallback_cache_dir, os.W_OK):
        return fallback_cache_dir

    return tempfile.gettempdir()


if __name__ == "__main__":
    # Command line interface for testing
    if len(sys.argv) < 2:
        sys.exit(1)

    operation = sys.argv[1]

    if operation == "canonicalize_path":
        if len(sys.argv) != 3:
            sys.exit(1)
        result: Any = canonicalize_path_no_resolve(sys.argv[2])
    elif operation == "validate_home":
        if len(sys.argv) != 3:
            sys.exit(1)
        result = validate_home_dir(sys.argv[2])
    elif operation == "sanitize_name":
        if len(sys.argv) != 3:
            sys.exit(1)
        result = sanitize_id_to_name(sys.argv[2])
    elif operation == "find_executable":
        if len(sys.argv) != 3:
            sys.exit(1)
        result = find_executable(sys.argv[2])
    elif operation == "is_wrapper_file":
        if len(sys.argv) != 3:
            sys.exit(1)
        result = is_wrapper_file(sys.argv[2])
    elif operation == "get_wrapper_id":
        if len(sys.argv) != 3:
            sys.exit(1)
        result = get_wrapper_id(sys.argv[2])
    elif operation == "safe_mktemp":
        if len(sys.argv) < 3:
            sys.exit(1)
        result = safe_mktemp(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None)
    else:
        sys.exit(1)

    # Print result if not None
    if result is None:
        sys.exit(1)
    if isinstance(result, bool):
        sys.exit(0 if result else 1)
    print(result)
