#!/usr/bin/env python3
"""Safety mechanisms for fplaunchwrapper.

This module handles all security boundaries including:
- Input validation and sanitization
- Path traversal prevention
- Wrapper file validation
- Test environment detection
- Safe launch checks
"""

from __future__ import annotations

import logging
import os
import re
import sys
from pathlib import Path

from .exceptions import (
    ForbiddenNameError,
    InvalidFlatpakIdError,
    PathTraversalError,
    SafetyError,
)

from .python_utils import (
    canonicalize_path_no_resolve,
    get_wrapper_id,
    is_wrapper_file,
    sanitize_id_to_name,
    sanitize_string,
    validate_home_dir,
)

UTILS_IMPORTED = True

__all__ = [
    "ForbiddenNameError",
    "InvalidFlatpakIdError",
    "PathTraversalError",
    "SafetyError",
    "canonicalize_path_no_resolve",
    "get_wrapper_id",
    "is_test_environment",
    "is_wrapper_file",
    "safe_launch_check",
    "sanitize_id_to_name",
    "sanitize_string",
    "validate_flatpak_id",
    "validate_home_dir",
]


def is_test_environment() -> bool:
    """Check if we're running in a test environment.

    Detection order:
    1. FPWRAPPER_TEST_ENV="true" -> True, "false" -> False
    2. sys.argv contains "test" -> True
    3. PYTEST_CURRENT_TEST environment variable set -> True
    4. pytest or unittest in sys.modules -> True
    """
    env_override = os.environ.get("FPWRAPPER_TEST_ENV")
    if env_override is not None:
        return env_override.lower().strip() == "true"

    explicit_test_arg = any((arg or "").lower() == "test" for arg in sys.argv)
    if explicit_test_arg:
        return True

    if os.environ.get("PYTEST_CURRENT_TEST"):
        return True

    return "pytest" in sys.modules or "unittest" in sys.modules


def validate_flatpak_id(flatpak_id: str) -> bool:
    """Validate a Flatpak ID format.

    Valid IDs: org.mozilla.Firefox, com.example.App123
    Must contain at least one dot, only alphanumeric, hyphens, underscores, dots.
    Must start with a letter.
    """
    if not flatpak_id or not isinstance(flatpak_id, str):
        return False

    if "." not in flatpak_id:
        return False

    if (
        flatpak_id.startswith(".")
        or flatpak_id.startswith("-")
        or flatpak_id.startswith("_")
    ):
        return False

    if flatpak_id.endswith("."):
        return False

    return bool(re.match(r"^[A-Za-z][A-Za-z0-9._-]*$", flatpak_id))


def is_dangerous_wrapper(wrapper_path: Path) -> bool:
    """Check if a wrapper script contains dangerous direct browser launches.

    Looks for flatpak run commands that bypass the wrapper's normal launch
    mechanism (e.g., a wrapper that launches firefox directly instead of
    the intended Flatpak app).

    Note: This is a defense-in-depth check. Wrappers are generated by this
    tool and should not contain such content by design. This function catches
    cases where a wrapper was manually edited or corrupted.
    """
    try:
        if wrapper_path.exists():
            content = wrapper_path.read_text()
            # Check for direct browser launches via flatpak run that would
            # bypass the intended app. Only flag specific known patterns
            # where the run command does NOT match the wrapper's own ID.
            dangerous_patterns = [
                "flatpak run org.mozilla.firefox",
                "flatpak run com.google.Chrome",
                "flatpak run org.chromium.Chromium",
            ]
            return any(pattern in content for pattern in dangerous_patterns)
    except (IOError, OSError, UnicodeDecodeError):
        pass
    return False


def _is_direct_browser_launch(app_name: str) -> bool:
    """Check if this is a direct browser launch."""
    browser_names = ["firefox", "chrome", "chromium", "google-chrome"]
    return app_name.lower() in browser_names


def safe_launch_check(
    app_name: str, wrapper_path: str | Path | None = None
) -> bool:
    """Perform safety checks before launching an application."""
    if wrapper_path:
        wrapper_path_obj = (
            Path(wrapper_path) if isinstance(wrapper_path, str) else wrapper_path
        )
        if is_dangerous_wrapper(wrapper_path_obj):
            logging.error("safety: blocked dangerous wrapper: %s", wrapper_path)
            return False

    if is_test_environment():
        if _is_direct_browser_launch(app_name):

            logging.warning(
                "safety: blocked direct browser launch in test environment: %s",
                app_name,
            )
            return False
        return True

    return True
