"""Phase 10: Concurrency / linearizability verification.

Real multi-threaded and multi-process tests against the wrapper
manager and generator. Verifies that:

1. Concurrent ``set_preference`` calls on the same wrapper serialize
   into one of the legal total orderings (linearizability).
2. Concurrent ``generate_wrapper`` / ``remove_wrapper`` on the same
   wrapper never produces a half-written executable on disk.
3. Two processes using separate ``WrapperManager`` instances over
   the same ``bin_dir`` / ``config_dir`` converge to a consistent
   state.
4. ``remove_wrapper`` interleaved with ``set_preference`` cannot
   resurrect a wrapper or leave a dangling ``.pref`` / ``.env``
   pointing at a missing binary.

The existing test suite relies on serial execution; these tests
use ``threading`` and ``multiprocessing`` to exercise the actual
concurrency surface called out as a limitation in
``docs/FORMAL_VERIFICATION_REPORT.md``.
"""
from __future__ import annotations

import multiprocessing
import shutil
import tempfile
import threading
from pathlib import Path
from typing import Any

import pytest

from lib.generate import WrapperGenerator
from lib.manage import WrapperManager
from lib.python_utils import atomic_write_text


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _setup_manager(tmp_path: Path) -> tuple[WrapperManager, Path, Path]:
    """Create a WrapperManager pointed at isolated dirs under tmp_path."""
    bin_dir = tmp_path / "bin"
    config_dir = tmp_path / "config"
    bin_dir.mkdir()
    config_dir.mkdir()
    mgr = WrapperManager(bin_dir=str(bin_dir), config_dir=str(config_dir))
    return mgr, bin_dir, config_dir


def _seed_wrapper(bin_dir: Path, config_dir: Path, name: str = "firefox") -> str:
    """Create a minimal valid wrapper file on disk; returns its name."""
    wrapper_path = bin_dir / name
    wrapper_path.write_text(
        "#!/bin/sh\n# Generated by fplaunchwrapper for org.test.app\nexit 0\n"
    )
    wrapper_path.chmod(0o755)
    return name


def _barrier(n: int) -> threading.Barrier:
    return threading.Barrier(n)


# ---------------------------------------------------------------------------
# TestLinearizability: concurrent set_preference on the same wrapper
# ---------------------------------------------------------------------------


class TestLinearizability:
    """Concurrent ``set_preference`` calls on a single wrapper must produce a
    state that corresponds to *some* serial execution of those calls.

    The legal serial orders are any permutation of {system, flatpak, auto}.
    After all threads complete, the persisted ``.pref`` file must contain
    *exactly one* of those three values, never empty, never a fragment.
    """

    PREFERENCES = ("system", "flatpak", "auto")

    def test_concurrent_set_preference_serialize_to_one_value(
        self, tmp_path: Path
    ) -> None:
        mgr, bin_dir, config_dir = _setup_manager(tmp_path)
        _seed_wrapper(bin_dir, config_dir, "firefox")

        n_threads = 16
        n_iterations = 5
        barrier = _barrier(n_threads)
        errors: list[BaseException] = []
        error_lock = threading.Lock()

        def worker(idx: int) -> None:
            try:
                # Spin until all threads are at the barrier so they
                # race as tightly as possible.
                barrier.wait(timeout=10)
                for j in range(n_iterations):
                    pref = self.PREFERENCES[(idx + j) % len(self.PREFERENCES)]
                    ok = mgr.set_preference("firefox", pref)
                    if not ok:
                        raise AssertionError(
                            f"set_preference returned False in worker {idx}"
                        )
            except BaseException as e:  # noqa: BLE001 - propagate to test
                with error_lock:
                    errors.append(e)

        threads = [
            threading.Thread(target=worker, args=(i,)) for i in range(n_threads)
        ]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30)
        for t in threads:
            assert not t.is_alive(), "Worker thread hung"

        assert not errors, f"Worker errors: {errors!r}"

        pref_file = config_dir / "firefox.pref"
        assert pref_file.exists(), "Preference file missing after concurrent writes"
        content = pref_file.read_text().strip()
        assert content in self.PREFERENCES, (
            f"Concurrent writes left .pref in illegal state: {content!r}"
        )
        # Sanity: the wrapper still exists
        assert (bin_dir / "firefox").exists()

    def test_concurrent_set_preference_does_not_corrupt_partial_write(
        self, tmp_path: Path
    ) -> None:
        """Even under racing writes, ``.pref`` must never be partially written.

        ``atomic_write_text`` guarantees this at the primitive level; this test
        verifies the property end-to-end via the manager API.
        """
        mgr, bin_dir, config_dir = _setup_manager(tmp_path)
        _seed_wrapper(bin_dir, config_dir, "firefox")

        n_threads = 12
        barrier = _barrier(n_threads)

        def worker(idx: int) -> None:
            barrier.wait(timeout=10)
            for _ in range(20):
                pref = self.PREFERENCES[idx % len(self.PREFERENCES)]
                assert mgr.set_preference("firefox", pref)

        threads = [
            threading.Thread(target=worker, args=(i,)) for i in range(n_threads)
        ]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30)

        # Read .pref *while another writer is active* — but here writers are
        # done; instead, verify the temp-file residue is gone.
        pref_file = config_dir / "firefox.pref"
        assert pref_file.exists()
        # No leftover .tmp siblings in the config dir
        leftovers = [p for p in config_dir.iterdir() if p.name.endswith(".tmp")]
        assert not leftovers, f"Temp file residue after concurrent writes: {leftovers}"


# ---------------------------------------------------------------------------
# TestConcurrentGenerateRemove: generate vs. remove races
# ---------------------------------------------------------------------------


class TestConcurrentGenerateRemove:
    """``generate_wrapper`` racing with ``remove_wrapper`` on the same name must
    produce a deterministic, recoverable end state — never a half-written
    executable and never a dangling ``.pref``/``.env`` for a missing wrapper.
    """

    def test_repeated_generate_idempotent_under_concurrency(
        self, tmp_path: Path
    ) -> None:
        bin_dir = tmp_path / "bin"
        bin_dir.mkdir()
        config_dir = tmp_path / "config"
        config_dir.mkdir()
        gen = WrapperGenerator(
            bin_dir=str(bin_dir), config_dir=str(config_dir)
        )

        n_threads = 8
        barrier = _barrier(n_threads)
        ok_count = 0
        lock = threading.Lock()

        def worker() -> None:
            nonlocal ok_count
            barrier.wait(timeout=10)
            for _ in range(5):
                if gen.generate_wrapper("org.test.firefox"):
                    with lock:
                        ok_count += 1

        threads = [threading.Thread(target=worker) for _ in range(n_threads)]
        for t in threads:
            t.start()
        for t in threads:
            t.join(timeout=30)

        wrapper = bin_dir / "firefox"
        assert wrapper.exists(), "Wrapper missing after concurrent generation"
        # Idempotence: the same content regardless of which thread "won"
        content = wrapper.read_text()
        assert "Generated by fplaunchwrapper" in content or "#!/bin/sh" in content
        # All threads reported success — generation is intentionally
        # idempotent (it succeeds as long as the wrapper ends up valid).
        assert ok_count == n_threads * 5

    def test_remove_then_concurrent_pref_does_not_resurrect(
        self, tmp_path: Path
    ) -> None:
        """If remove_wrapper succeeds while set_preference races, the .pref
        file must NOT be left behind pointing at a missing binary."""
        mgr, bin_dir, config_dir = _setup_manager(tmp_path)
        _seed_wrapper(bin_dir, config_dir, "firefox")
        mgr.set_preference("firefox", "system")

        # Simulate the race with a tight thread pair
        barrier = _barrier(2)
        results: dict[str, bool] = {}

        def do_remove() -> None:
            barrier.wait(timeout=10)
            # skip the Confirm prompt by injecting force=True
            results["remove"] = mgr.remove_wrapper("firefox", force=True)

        def do_set() -> None:
            barrier.wait(timeout=10)
            results["set"] = mgr.set_preference("firefox", "auto")

        t1 = threading.Thread(target=do_remove)
        t2 = threading.Thread(target=do_set)
        t1.start()
        t2.start()
        t1.join(timeout=15)
        t2.join(timeout=15)

        # Whichever order executed, we must end in a consistent state:
        # either the wrapper exists with a .pref, or it doesn't and there's
        # no .pref pointing at it.
        wrapper_exists = (bin_dir / "firefox").exists()
        pref_exists = (config_dir / "firefox.pref").exists()
        # Dangling .pref for missing wrapper is the bug we want to prevent
        assert not (pref_exists and not wrapper_exists), (
            f"Dangling .pref for removed wrapper. "
            f"results={results!r} wrapper_exists={wrapper_exists} "
            f"pref_exists={pref_exists}"
        )


# ---------------------------------------------------------------------------
# TestCrossProcess: two processes, same directories
# ---------------------------------------------------------------------------


def _proc_generate(
    bin_dir_str: str, config_dir_str: str, app_id: str, out_q: Any
) -> None:
    """Worker run in a subprocess for ``test_cross_process_generate_no_partial``."""
    try:
        gen = WrapperGenerator(
            bin_dir=bin_dir_str, config_dir=config_dir_str
        )
        ok = gen.generate_wrapper(app_id)
        out_q.put(("ok", ok))
    except BaseException as e:  # noqa: BLE001
        out_q.put(("error", repr(e)))


def _proc_remove(
    bin_dir_str: str, config_dir_str: str, name: str, out_q: Any
) -> None:
    """Worker run in a subprocess for cross-process remove races."""
    try:
        mgr = WrapperManager(bin_dir=bin_dir_str, config_dir=config_dir_str)
        out_q.put(("ok", mgr.remove_wrapper(name, force=True)))
    except BaseException as e:  # noqa: BLE001
        out_q.put(("error", repr(e)))


class TestCrossProcess:
    """Two processes operating on the same ``bin_dir``/``config_dir`` must
    converge to a state where every wrapper on disk is a complete, valid
    wrapper script — no zero-byte files, no broken symlinks.
    """

    def test_cross_process_generate_no_partial_artifacts(
        self, tmp_path: Path
    ) -> None:
        bin_dir = tmp_path / "bin"
        config_dir = tmp_path / "config"
        bin_dir.mkdir()
        config_dir.mkdir()

        # Use spawn to avoid fork-related state bleed
        ctx = multiprocessing.get_context("spawn")
        procs = []
        q: Any = ctx.Queue()
        app_ids = [
            "org.test.firefox",
            "org.test.terminal",
            "org.test.editor",
            "org.test.player",
        ]
        for app_id in app_ids:
            p = ctx.Process(
                target=_proc_generate,
                args=(str(bin_dir), str(config_dir), app_id, q),
            )
            p.start()
            procs.append(p)
        for p in procs:
            p.join(timeout=20)

        results = [q.get(timeout=5) for _ in range(len(procs))]
        for tag, value in results:
            assert tag == "ok", f"Subprocess error: {value!r}"
            assert value is True, "Subprocess generation returned False"

        # Every wrapper that should exist does, and is non-empty + executable
        for app_id in app_ids:
            expected_name = app_id.rsplit(".", 1)[-1]
            wrapper = bin_dir / expected_name
            assert wrapper.exists(), f"Missing wrapper for {app_id}"
            assert wrapper.stat().st_size > 0, f"Empty wrapper for {app_id}"
            assert wrapper.stat().st_mode & 0o111, f"Non-executable wrapper {app_id}"
            # No temp file residue
        leftovers = [p for p in bin_dir.iterdir() if p.name.endswith(".tmp")]
        assert not leftovers, f"Temp residue after cross-process generation: {leftovers}"

    def test_cross_process_remove_converges(self, tmp_path: Path) -> None:
        bin_dir = tmp_path / "bin"
        config_dir = tmp_path / "config"
        bin_dir.mkdir()
        config_dir.mkdir()

        # Pre-populate
        gen = WrapperGenerator(bin_dir=str(bin_dir), config_dir=str(config_dir))
        for app_id in ("org.test.firefox", "org.test.terminal"):
            assert gen.generate_wrapper(app_id)

        assert (bin_dir / "firefox").exists()
        assert (bin_dir / "terminal").exists()

        ctx = multiprocessing.get_context("spawn")
        procs = []
        q: Any = ctx.Queue()
        for name in ("firefox", "terminal"):
            p = ctx.Process(
                target=_proc_remove,
                args=(str(bin_dir), str(config_dir), name, q),
            )
            p.start()
            procs.append(p)
        for p in procs:
            p.join(timeout=20)

        results = [q.get(timeout=5) for _ in range(len(procs))]
        for tag, value in results:
            assert tag == "ok", f"Subprocess error: {value!r}"
            assert value is True

        assert not (bin_dir / "firefox").exists()
        assert not (bin_dir / "terminal").exists()
        # No dangling .pref files
        assert not (config_dir / "firefox.pref").exists()
        assert not (config_dir / "terminal.pref").exists()


# ---------------------------------------------------------------------------
# TestStateInvariantsAfterRace: post-condition checks after arbitrary races
# ---------------------------------------------------------------------------


class TestStateInvariantsAfterRace:
    """No matter how the races resolve, the filesystem must obey invariants:
    - every wrapper on disk is non-empty, executable, and parseable
    - every .pref file's name corresponds to an existing wrapper
    - no temp files are left behind
    """

    @pytest.mark.parametrize("seed", [1, 2, 3, 4, 5])
    def test_random_mixed_workload_invariants(
        self, tmp_path: Path, seed: int
    ) -> None:
        import random

        random.seed(seed)
        bin_dir = tmp_path / "bin"
        config_dir = tmp_path / "config"
        bin_dir.mkdir()
        config_dir.mkdir()
        gen = WrapperGenerator(bin_dir=str(bin_dir), config_dir=str(config_dir))
        mgr = WrapperManager(bin_dir=str(bin_dir), config_dir=str(config_dir))

        # Seed a stable set of wrappers first
        seeded = [
            ("org.test.firefox", "firefox"),
            ("org.test.terminal", "terminal"),
            ("org.test.editor", "editor"),
        ]
        for app_id, _name in seeded:
            assert gen.generate_wrapper(app_id)

        actions = [
            ("set_pref", ("firefox", "system")),
            ("set_pref", ("terminal", "auto")),
            ("remove", ("editor",)),
            ("set_pref", ("editor", "flatpak")),  # post-remove
            ("set_pref", ("firefox", "flatpak")),
            ("set_pref", ("terminal", "system")),
            ("remove", ("firefox",)),
            ("set_pref", ("firefox", "auto")),  # post-remove
        ]
        random.shuffle(actions)

        threads = []
        barrier = _barrier(len(actions))

        def run(action: tuple) -> None:
            barrier.wait(timeout=10)
            kind = action[0]
            try:
                if kind == "set_pref":
                    mgr.set_preference(action[1][0], action[1][1])
                elif kind == "remove":
                    mgr.remove_wrapper(action[1][0], force=True)
            except Exception:  # noqa: BLE001 - we're stress-testing
                pass

        for action in actions:
            t = threading.Thread(target=run, args=(action,))
            threads.append(t)
            t.start()
        for t in threads:
            t.join(timeout=30)

        # Invariant 1: every wrapper on disk is non-empty and executable
        for p in bin_dir.iterdir():
            if p.name.endswith(".tmp"):
                continue
            if p.is_file():
                assert p.stat().st_size > 0, f"Empty wrapper on disk: {p}"
                assert p.stat().st_mode & 0o111, f"Non-executable wrapper: {p}"

        # Invariant 2: .pref files reference existing wrappers OR are harmless
        # leftover from a remove-after-set race. The latter is acceptable
        # because remove_wrapper cleans it up; here we just check no .pref
        # references a name with no wrapper *unless* the remove ran AFTER the
        # set — in which case remove should have cleaned it. We treat a
        # dangling .pref as a BUG.
        for p in config_dir.iterdir():
            if p.suffix == ".pref":
                name = p.stem
                wrapper = bin_dir / name
                assert wrapper.exists(), (
                    f"Dangling .pref: {p} (no wrapper {wrapper})"
                )

        # Invariant 3: no temp residue
        assert not list(bin_dir.glob("*.tmp"))
        assert not list(config_dir.glob("*.tmp"))
